### ISSUE TITLE
Couldn't clone Stable Diffusion  

### ISSUE THREAD

**Issue by JaydizDume** [LykosAI/StabilityMatrix#1]
when I started stable-diffusion-webui, this error appears. Does anyone know its cause and how to fix it, please?

![Screenshot_4](https://github.com/LykosAI/StabilityMatrix/assets/137836659/a46f671e-1277-4227-8023-566344d147a6)

**Comment by ionite34** [comment]
It seems there is a certificate issue from git during the clone. Are you in a company network or using some custom root certificates by chance? We will look to add a toggle option to choose between the OpenSSL / Windows certificate authority / Disable SSL for git.

**Comment by JaydizDume** [comment]
I think most likely I am accidentally using some custom root certificates. Thanks for the answer
