### ISSUE TITLE
 FaceSwapLab fails to install

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#100]
FaceSwaplab is an extension that I loaded in A1111, but it fails.

Possibly the same reason Roop also fails.
***   running egg_info
***   writing insightface.egg-info\PKG-INFO
***   writing dependency_links to insightface.egg-info\dependency_links.txt
***   writing entry points to insightface.egg-info\entry_points.txt
***   writing requirements to insightface.egg-info\requires.txt
***   writing top-level names to insightface.egg-info\top_level.txt
***   reading manifest file 'insightface.egg-info\SOURCES.txt'
***   writing manifest file 'insightface.egg-info\SOURCES.txt'
***   D:\All-Temps\pip-build-env-mkae5o_0\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
***   !!
***   
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***   
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
***           to the `packages` configuration field.
***   
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***   
***           You can read more about "package discovery" on setuptools documentation page:
***   
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***   
***           If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
***           already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***   
***           You can read more about "package data files" on setuptools documentation page:
***   
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***   
***   
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
Lots more errors, which I think is caused by the issues above.

I found the following which I think is addressing the above problem:

If you encounter issues with dependencies or during the installation, it's recommended to install the dependencies manually from the root of your directory.

Windows:

.\venv\Scripts\activate
cd .\extensions\sd-webui-faceswaplab\
pip install -r .\requirements.txt

Linux/MacOS:

source venv/bin/activate
cd ./extensions/sd-webui-faceswaplab/
pip install -r ./requirements.txt

Please ensure that you have already set up the virtual environment (venv) before executing these commands.

If you plan on using the GPU, please use requirements-gpu.txt instead of requirements.txt when installing.

However when I try to run it I get this error:

D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv>.\venv\Scripts\activate
The system cannot find the path specified.

D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv>cd .\extensions\sd-webui-faceswaplab\
The system cannot find the path specified.

D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv>pip install -r .\requirements.txt

**Comment by mohnjiles** [comment]
Hi, could you try again from the `D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\` directory? Since you are already inside the `venv` directory, commands/paths starting with `.\venv` won't work.

**Comment by drdancm** [comment]
I finally got help from a programmer friend and got the faceswaplab prebuilt insightface package installed just fine, but in spite of having done that, I still got the insightface not found error.
