### ISSUE TITLE
No audio backend is available

### ISSUE THREAD

**Issue by agarzon** [LykosAI/StabilityMatrix#101]
Fresh install in two different PC (Win10 and Win11) both with 3090 and 32 GRAM
Version v2.3.3
Portable mode.

```python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
Launching Web UI with arguments: --xformers --api --skip-python-version-check --administrator
C:\SD\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
```

**Comment by drdancm** [comment]
I have the same problem, on two Win10 computers (HP Z820 and HPZ840), since audio is only used to signal end of processing etc. I did not consider this an important issue.
Same error message torchaudio etc.

**Comment by ionite34** [comment]
I think this is mainly from us installing torch audio when it's not actually needed, such no backend was installed. I'll look into removing the torch audio install for A1111, in the meantime this warning should not affect anything.
