### ISSUE TITLE
Unabe to update CompyUI

### ISSUE THREAD

**Issue by syddharth** [LykosAI/StabilityMatrix#102]
The app is stuck from long time, at updating the ComfyUI package. There seems to be no acivity in the background.
Why can't I manually go into the project folder and do a git pull?

**Comment by eephyne** [comment]
Same here, it seem to copy the content of the git repo without the .git folder so we can only update via the app. don't really know why but its annoying since I can't update it at all like that

**Comment by ionite34** [comment]
Should be fixed since v2.4.1
