### ISSUE TITLE
The Japanese translation of the Model Browser is typo'd.

### ISSUE THREAD

**Issue by mattyatea** [LykosAI/StabilityMatrix#1024]
### Proposal

You might want to correct the Japanese translation of Model Browser because it is typo'd as Model Brouser.

**Comment by MakotoUwaya** [comment]
Thank you for previously merging the correction to the Japanese resource (fixing the “Model Browser” typo). 
However, it looks like the change was unintentionally overwritten by a subsequent commit. 
Would you mind re‑applying the fix?

Commit that removed the change: https://github.com/LykosAI/StabilityMatrix/commit/1c76ade59fc7bd125a6e246d2e7feb296d7d2955

Thanks in advance!

**Comment by mohnjiles** [comment]
> Thank you for previously merging the correction to the Japanese resource (fixing the “Model Browser” typo). However, it looks like the change was unintentionally overwritten by a subsequent commit. Would you mind re‑applying the fix?
> 
> Commit that removed the change: [1c76ade](https://github.com/LykosAI/StabilityMatrix/commit/1c76ade59fc7bd125a6e246d2e7feb296d7d2955)
> 
> Thanks in advance!

Thanks for the heads up!

It seems it has been updated to モデルブラウザ recently from one of our translators. Would this work too? If so I'll get that into the next update. 

Thanks!
