### ISSUE TITLE
New CogStudio package not working

### ISSUE THREAD

**Issue by fbauer-kunbus** [LykosAI/StabilityMatrix#1031]
### What happened?

Did somebody successfully run the new CogStudio package?
When I start it I get this:

```
File Not Found
Fetching 2 files: 100%|██████████| 2/2 [00:00<00:00, 100.19it/s]
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

I could run it but it hang indefinitely at 14% when I ran 'text-to-video' without giving any output on the console.
Stopped an relaunched it two times - now at third time it never even starts to create something.

**I would very much prefer if such new packages would be TESTED EXTENSIVELY before launching them to the public.**

### Version

2.12.4

### What Operating System are you using?

Windows

**Comment by SayanSama** [comment]
Can confirm I also get no progress on either Txt2Vid and Img2Vid after waiting for 10 minutes. Console log is the same as OP.
Tested on windows 11 with both chrome and firefox.
![image](https://github.com/user-attachments/assets/408d7da9-ea66-4ac4-a4cd-09b1b6275af3)
.

**Comment by dallas4u** [comment]
Same error, just installed last night, error immediate when starting for the first (and every) time.

**Comment by mohnjiles** [comment]
There are several large downloads it has to go through, and on my 2gig connection it takes several minutes. If you have a slower connection it will take even longer. Please be patient and watch the progress bars in the UI. The console output does not show much at all.

**Comment by mohnjiles** [comment]
Having all the models downloaded already, it took me approximately 10 minutes to go from "Generate Video" clicked to a result. If you are running a fresh install, you have several tens of GBs of models to download first. On a fairly respectable 100Mbit/s connection, the actual video model will take *eighteen minutes* to download on its own. There are many other files it needs to download on top of that. 

The UI does not show this progress very well, I agree, but you must have some patience.

**Comment by dallas4u** [comment]
BINGO.  Just generated an initial t2v and it took around 7min or so to generate using 2b, and looks pretty good. I'm on a 1gig connection, but was much quicker than I expect for the initial generation... I just wasn't giving it time.

**Comment by fbauer-kunbus** [comment]
Sorry, how stupid is it to not give feedback on the console about this massive downloads in the background - like each and every other installation is doing it. What are those developers even thinking ...

**Comment by fbauer-kunbus** [comment]
Obviously comes down to CogStudio loading massive amounts of model data in the background without showing the progress on the console or even mentioning it once
