### ISSUE TITLE
[Question] ComfyUI

### ISSUE THREAD

**Issue by za-wa-n-go** [LykosAI/StabilityMatrix#113]
StabilityMatrix and independent ComfyUI results are different.
This is subjective, but often the results generated by StabilityMatrix are not better.
We would like to make the results match.
Is it possible?

**Comment by za-wa-n-go** [comment]
<img width="826" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/118154415/b3e24573-54bd-485b-8607-014034f2c7c3">

**Comment by za-wa-n-go** [comment]
The only difference between the two is the configuration of the venv, so I know the cause is there, but I am wondering which one affects the generated results.

**Comment by ionite34** [comment]
Do you know if the other install is using xformers? We install it as part of the standard recommended instructions for ComfyUI.

Try launching with argument `--disable-xformers` and see if that matches the other install
<img width="166" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/3116652a-7f3e-4afc-a0b4-d331482055fd">

**Comment by za-wa-n-go** [comment]
thanks.
Both were using xformers, so I tried disabling it, but the results were different.

**Comment by za-wa-n-go** [comment]
After a while I tried again and got different results.
They all have the same settings, the only difference is whether the startup is StabilityMatrix or the independent ComfyUI.
I would like to determine the cause of this problem, as it is highly inconvenient when we want to share workflows with others.

![Work_0_093510_00001_](https://github.com/LykosAI/StabilityMatrix/assets/118154415/d6b7ca89-ecb4-4c90-831a-f1c7346043a2)
![Work_0_093741_00001_](https://github.com/LykosAI/StabilityMatrix/assets/118154415/35121a74-0b68-483f-9586-fc9b8e528833)

**Comment by za-wa-n-go** [comment]
SDXL-base-1.0

I am concerned about the fact that Matrix seems to be of lower quality.

![Work_0_100137_00001_](https://github.com/LykosAI/StabilityMatrix/assets/118154415/b7887776-7724-4d0e-81e1-0298dbd24f8c)
![Work_0_100229_00001_](https://github.com/LykosAI/StabilityMatrix/assets/118154415/a815ab5f-75e2-4c76-ba9b-dfed0eb357fb)
