### ISSUE TITLE
[Feature Request] Support for Fooocus-MRE

### ISSUE THREAD

**Issue by Jisevind** [LykosAI/StabilityMatrix#115]
Please consider adding support for Fooocus-MRE.

https://github.com/MoonRide303/Fooocus-MRE

**Comment by mohnjiles** [comment]
Hi, thanks for the suggestion! This was added in [v2.4.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.4.0)

**Comment by Jisevind** [comment]
Thank you! 😀
