### ISSUE TITLE
Packages: Error Updating ... [WinError 5] Access is denied

### ISSUE THREAD

**Issue by WSJUSA** [LykosAI/StabilityMatrix#120]
Running Update on a Package (case is Comfyui) received the following permissions error

Error Updating Comfyui

Venv creation failed with code 1: 
Permissions Error: [WinError 5] Access is denied:
'<path to StabilityMatrix in folder Documents>\\Packages\\Comfyui\\venv\\Scripts\\python.

Not sure why StabilityMatrix would want to be creating venv which already exists.  I tried assigned Users group with Full Control and Modify on venv and all sub dirs and files. That didn't work :(

What am i missing on setting up StabilityMatrix to be able to updated the Packages?

**Comment by ionite34** [comment]
Should be fixed in newer versions above 2.0
