### ISSUE TITLE
Fooocus release version cannot find pygit2 module

### ISSUE THREAD

**Issue by GatesDA** [LykosAI/StabilityMatrix#124]
I installed a fresh copy of Fooocus (version: release) and am getting the following error on launch.  I suspect this might be connected to the new 2.0 release.

It works if I install the main branch instead.

```
Traceback (most recent call last):
  File "C:\stable-diffusion\StabilityMatrix\Data\Packages\Fooocus\launch.py", line 6, in <module>
    from modules.launch_util import is_installed, run, python, \
  File "C:\stable-diffusion\StabilityMatrix\Data\Packages\Fooocus\modules\launch_util.py", line 9, in <module>
    import pygit2
ModuleNotFoundError: No module named 'pygit2'
```

**Comment by mohnjiles** [comment]
Thanks for the report! Seems the package author changed the format of their releases, it seems meant to be installed via their installer. We will be removing the option to install via Releases until we can find a way to support it again. You will still be able to install the main branch (or any branches, should they exist in the future) instead.

**Comment by bigmouth-GD** [comment]
The fooocus distribution I installed isn't the latest version and doesn't have an update option. Should I install a branch version

**Comment by KloneBaker** [comment]
> The fooocus distribution I installed isn't the latest version and doesn't have an update option. Should I install a branch version

This is just my opinion, but if you **really like** fooocus, it would be better to install it the way they intended it, since **for now** Stability Matrix according to the comment above yours, doesn't seem to support **new versions** of fooocus. 🤷‍♂️

**Comment by mohnjiles** [comment]
> This is just my opinion, but if you **really like** fooocus, it would be better to install it the way they intended it, since **for now** Stability Matrix according to the comment above yours, doesn't seem to support **new versions** of fooocus. 🤷‍♂️

Sorry for the confusion - if anything, the "branch mode" installation we've done as a temporary fix will be a more up-to-date (but also possibly more experimental/bleeding-edge) version of Fooocus than the typical "Release mode" installation that is currently not working.
