### ISSUE TITLE
I can't install FaceSwap Lab

### ISSUE THREAD

**Issue by DARKDEYMON** [LykosAI/StabilityMatrix#125]
I try to install https://glucauze.github.io/sd-webui-faceswaplab/ in my web ui,  I try install withought StabilityMatrix and it works
I thing is a enviroment variable trouble

`  running egg_info
  writing insightface.egg-info\PKG-INFO
  writing dependency_links to insightface.egg-info\dependency_links.txt
  writing entry points to insightface.egg-info\entry_points.txt
  writing requirements to insightface.egg-info\requires.txt
  writing top-level names to insightface.egg-info\top_level.txt
  reading manifest file 'insightface.egg-info\SOURCES.txt'
  writing manifest file 'insightface.egg-info\SOURCES.txt'
  C:\Users\HP\AppData\Local\Temp\pip-build-env-9coiw00b\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
  !!
  
          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.
  
          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
          to the `packages` configuration field.
  
          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
  
          You can read more about "package discovery" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
  
          If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
          already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.
  
          You can read more about "package data files" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
  
  
          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************
  
  !!
    check.warn(importable)
  C:\Users\HP\AppData\Local\Temp\pip-build-env-9coiw00b\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
  !!
  
          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.data.images' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.
  
          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'insightface.data.images' is explicitly added
          to the `packages` configuration field.
  
          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
  
          You can read more about "package discovery" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
  
          If you don't want 'insightface.data.images' to be distributed and are
          already explicitly excluding 'insightface.data.images' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.
  
          You can read more about "package data files" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
  
  
          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************
  
  !!
    check.warn(importable)
  C:\Users\HP\AppData\Local\Temp\pip-build-env-9coiw00b\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
  !!
  
          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.data.objects' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.
  
          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'insightface.data.objects' is explicitly added
          to the `packages` configuration field.
  
          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
  
          You can read more about "package discovery" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
  
          If you don't want 'insightface.data.objects' to be distributed and are
          already explicitly excluding 'insightface.data.objects' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.
  
          You can read more about "package data files" on setuptools documentation page:
  
          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
  
  
          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************
  
  !!
    check.warn(importable)
  creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  creating build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
  copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
  creating build\lib.win-amd64-cpython-310\insightface\data\objects
  copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
  copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
  running build_ext
  building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
  creating build\temp.win-amd64-cpython-310
  creating build\temp.win-amd64-cpython-310\Release
  creating build\temp.win-amd64-cpython-310\Release\insightface
  creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty
  creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d
  creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh
  creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh\cython
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\Users\HP\AppData\Local\Temp\pip-build-env-9coiw00b\overlay\Lib\site-packages\numpy\core\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\Scripts\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\Scripts\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
  mesh_core.cpp
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: '=': conversin de 'int' a 'float'; posible prdida de datos
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IC:\Users\HP\AppData\Local\Temp\pip-build-env-9coiw00b\overlay\Lib\site-packages\numpy\core\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\Scripts\include -IC:\Users\HP\Documents\StabilityMatrix\Packages\stable-diffusion-webui\venv\Scripts\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.obj
  mesh_core_cython.cpp
  insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp(36): fatal error C1083: No se puede abrir el archivo incluir: 'Python.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects`

**Comment by mohnjiles** [comment]
Thanks for the report! As a temporary workaround, could you try following Step VIII on [this page](https://github.com/Gourieff/sd-webui-reactor#viii-for-windows-users-if-you-still-cannot-build-insightface-for-some-reasons-or-just-dont-want-to-install-visual-studio-or-vs-c-build-tools---do-the-following)?

**Comment by drdancm** [comment]
Same problem with insightface as the main issue. Another face swap programs (Gouieff Reactor) has the same problem, so I wonder if the problem has to do with the portable packaging.

**Comment by drdancm** [comment]
I got Step VIII on the linked page (posted by mohhjiles) to finally work, however, it still got the cannot find insightface package.
Has the newest 2.45 update addressed this issue?

Thanks!

**Comment by drdancm** [comment]
I still have the insight face cannot be found problem after having installed StabMatrix v 2.45. Unfortunately none of the various face-swap developers make their programs one click install, there are always required pieces that have to be first installed. I was glad to read that you don't have to install MS Visual Studio etc. because it turns out you can install a prebuilt package instead which takes up far less space. However even after installing it successfully, things don't work.

**Comment by KINGLIFER** [comment]
Same here. should I just install Stable Matrix regular and not with portable status?

**Comment by agarzon-orangerine** [comment]
> Thanks for the report! As a temporary workaround, could you try following Step VIII on [this page](https://github.com/Gourieff/sd-webui-reactor#viii-for-windows-users-if-you-still-cannot-build-insightface-for-some-reasons-or-just-dont-want-to-install-visual-studio-or-vs-c-build-tools---do-the-following)?

This workaround did the trick. 😊

**Comment by drdancm** [comment]
This is what I got:

(venv) D:\STABLEDIFF\Data\Packages\stable-diffusion-webui>python -m pip install -U pip
Requirement already satisfied: pip in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (23.2.1)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

(venv) D:\STABLEDIFF\Data\Packages\stable-diffusion-webui>

but then I went ahead and it looks like it installed insightface.

Next time I launched SD I got an error message about downloading inswapper but unable to find it.
I launched again and this time there was no error.
FaceSwap Lab now shows up.

And now it works ! Finally !
Thanks !

**Comment by drdancm** [comment]
For anyone who is thinking of using FaceSwapLab, you might also consider using Gourieff Reactor, or Reactor-Force (for 8Gb minimum VRAM inVidia GPU - it's much faster !). I find the interface much simpler and it too has a batch mode. I've got it working fine on A1111.
