### ISSUE TITLE
UI Improvement Suggestions

### ISSUE THREAD

**Issue by Deven-dreamLand** [LykosAI/StabilityMatrix#131]
I think it can be improved to add an output picture icon, so that the output directory of several programs in the collection together, easy to browse and edit the generated pictures, I believe he will be more useful!
Some procedure do not have their own image library, and it is very tedious to open folders layer by layer to view and find images. I believe this change can make it easier.
![output-01](https://github.com/LykosAI/StabilityMatrix/assets/134496440/ff19a43a-ee0e-42ab-a351-8244fbb08f26)
![output-02](https://github.com/LykosAI/StabilityMatrix/assets/134496440/d8959150-8bc1-4ae6-8159-b1f815a61773)

**Comment by drdancm** [comment]
Great idea.

**Comment by drdancm** [comment]
I'm surprised no one else thinks this is a good idea.
