### ISSUE TITLE
why and there other  failed code 1

### ISSUE THREAD

**Issue by YesserFA** [LykosAI/StabilityMatrix#134]
pip install failed with code 2: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118\r\nCollecting torch\r\n  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)\r\n     ------                                   0.4/2.6 GB 128.4 kB/s eta 4:43:50\r\nERROR: Exception:\r\nTraceback (most recent call last):\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher\r\n    yield\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read\r\n    data = self._fp_read(amt) if not fp_closed else b""\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read\r\n    return self._fp.read(amt) if amt is not None else self._fp.read()\r\n  File "http\client.py", line 466, in read\r\n  File "socket.py", line 705, in readinto\r\n  File "ssl.py", line 1274, in recv_into\r\n  File "ssl.py", line 1130, in read\r\nTimeoutError: The read operation timed out\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper\r\n    status = run_func(*args)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper\r\n    return func(self, options, args)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 377, in run\r\n    requirement_set = resolver.resolve(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve\r\n    result = self._result = resolver.resolve(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve\r\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve\r\n    self._add_to_criteria(self.state.criteria, r, parent=None)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria\r\n    if not criterion.candidates:\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__\r\n    return bool(self._sequence)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__\r\n    return any(self)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>\r\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built\r\n    candidate = func()\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link\r\n    self._link_candidate_cache[link] = LinkCandidate(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__\r\n    super().__init__(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__\r\n    self.dist = self._prepare()\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare\r\n    dist = self._prepare_distribution()\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution\r\n    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement\r\n    return self._prepare_linked_requirement(req, parallel_builds)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 609, in _prepare_linked_requirement\r\n    local_file = unpack_url(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url\r\n    file = get_http_url(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url\r\n    from_path, content_type = download(link, temp_dir.path)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__\r\n    for chunk in chunks:\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar\r\n    for chunk in iterable:\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks\r\n    for chunk in response.raw.stream(\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream\r\n    data = self.read(amt=amt, decode_content=decode_content)\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read\r\n    with self._error_catcher():\r\n  File "contextlib.py", line 153, in __exit__\r\n  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher\r\n    raise ReadTimeoutError(self._pool, None, "Read timed out.")\r\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.\r\n'

**Comment by ionite34** [comment]
Seems this may be a network issue during the pip download, can only suggest retrying or using a different network
