### ISSUE TITLE
LDSR link folder is not being created on Stable Diffusion WebUI

### ISSUE THREAD

**Issue by Seantourage** [LykosAI/StabilityMatrix#139]
Similar to bug #97 the LDSR folder isn't being symlinked.

I have 2.4.0 and the remove shared checkpoints directory option enabled to ensure that it wasn't being linked

Might also be the same with BLIP if someone can confirm

**Comment by ionite34** [comment]
Added in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.4.6
