### ISSUE TITLE
Feature Request: The console display should fill the width of the SM window or be wordwrapped

### ISSUE THREAD

**Issue by brknsoul** [LykosAI/StabilityMatrix#145]
Currently, the console display seems to be limited to a width of 80 characters, while the SM window can be much wider than that.

This results in truncation.

Suggest either filling the entire width of the window, or at the very least, allow wordwrapping.

![image](https://github.com/LykosAI/StabilityMatrix/assets/1969381/1bc8675e-46ac-42e6-aa28-9d6367ddd56b)

**Comment by xedis** [comment]
You got more than i did!
![image](https://github.com/LykosAI/StabilityMatrix/assets/4144634/d39c9a91-8ed7-4745-86d6-e6f3f05f3272)

**Comment by ionite34** [comment]
This seems to be something related to the rich console module that SD.Next uses for logging that's doing the wrapping on their end. You can override this by setting the `COLUMNS` environment variable on the settings page, the default is 80 I believe.

<img width="392" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/d20023a7-3e80-4455-9ced-3f2a784d2135">

**Comment by brknsoul** [comment]
> This seems to be something related to the rich console module that SD.Next uses for logging that's doing the wrapping on their end. You can override this by setting the `COLUMNS` environment variable on the settings page, the default is 80 I believe.
> 
> <snip>

This works perfectly!
![image](https://github.com/LykosAI/StabilityMatrix/assets/1969381/1f864165-b5aa-4a82-a49f-9f6d9d135e3a)

Thank you!
