### ISSUE TITLE
Fooocus and Fooocus-MRE installation misses ./repositories/ComfyUI-from-StabilityAI-Official contents

### ISSUE THREAD

**Issue by darkvertex** [LykosAI/StabilityMatrix#146]
Hi!

I kept getting errors that the module `comfy.cli_args` could not be found. After some issue perusing over the original Fooocus github project, I found this comment:
https://github.com/lllyasviel/Fooocus/issues/169#issuecomment-1694882475

and so I went into the installed package and `./repositories/ComfyUI-from-StabilityAI-Official` was an empty directory.

I deleted the empty dir, then ran `git clone https://github.com/comfyanonymous/ComfyUI ComfyUI-from-StabilityAI-Official` and it fixed my deployment. (Same thing for the -MRE variant.)

I'm on Windows 11 using the latest stable release of Stability Matrix as of the time of writing this message.

**Comment by mohnjiles** [comment]
Hi, thanks for the report! 

Did this happen after a fresh install or update? Also, which version of the packages were you using when you had the error?  Thanks!

**Comment by darkvertex** [comment]
Fresh install, I believe. 

I'm sorry but this was too long ago and I don't remember the versions.
