### ISSUE TITLE
ISSUE INSTALLING SD WEBUI AND FOOCUS

### ISSUE THREAD

**Issue by Ramam001** [LykosAI/StabilityMatrix#148]
![image](https://github.com/LykosAI/StabilityMatrix/assets/77449795/7049f1cd-d9e8-47d6-beb2-68f90447ed6a)

+ I INSTALLED comfy ui portable, how do i import the package

**Comment by mohnjiles** [comment]
Hi, sorry about that, the symbolic links we use for the shared model directory do not work on FAT32/exFAT/BTRFS hard drives. To resolve the error in the screenshot, you can try moving Stability Matrix to a NTFS/ext4 drive, or during the installation you can select the Advanced Options cogwheel, and choose to disable the symlinks.

If you have installed ComfyUI outside of Stability Matrix, you would need to move that folder into your install directory at `.\Data\Packages`, and then it should show up for import on the Packages tab in Stability Matrix.

**Comment by Ramam001** [comment]
> Hi, sorry about that, the symbolic links we use for the shared model directory do not work on FAT32/exFAT/BTRFS hard drives. To resolve the error in the screenshot, you can try moving Stability Matrix to a NTFS/ext4 drive, or during the installation you can select the Advanced Options cogwheel, and choose to disable the symlinks.
> 
> If you have installed ComfyUI outside of Stability Matrix, you would need to move that folder into your install directory at `.\Data\Packages`, and then it should show up for import on the Packages tab in Stability Matrix.

thanks but ive external ssd and its exFAT, unfortunatly due to data backuped i cant change its type,    yes i did imported it there but it also showing some kind of error, please provide support for exfat as its very famous for external ssds

**Comment by Ramam001** [comment]
as the stable difusion launcher is absolute this is my only option

**Comment by mohnjiles** [comment]
Sorry about that! You can still install the packages, you just won't be able to use the Shared Model folder on exFAT. 

When installing a new package, select the Cogwheel button and then select "Configuration" or "None" from the "Shared Model Folder Strategy" dropdown. You will have to manage importing checkpoints yourself, but the rest of it should work fine.

<img width="560" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/33761/3dd51345-edc4-464d-b4d2-91d0abfc01b0">

**Comment by Ramam001** [comment]
Thanks, is there any way to configure shared model by editing xml like in comfy ui there is
