### ISSUE TITLE
Feature Request: Add stable-diffusion-webui-ux

### ISSUE THREAD

**Issue by jurandfantom** [LykosAI/StabilityMatrix#150]
Hi there, would be great to see https://github.com/anapnoe/stable-diffusion-webui-ux   on installation list. Sorry, I was try to find how to mark that as enchantment

**Comment by drdancm** [comment]
Yes, this package looks very interesting. I would love to have this available.

**Comment by drdancm** [comment]
This package is now available and runs well.
