### ISSUE TITLE
ComfyUI Manager do not appear 

### ISSUE THREAD

**Issue by h34d1sd34d** [LykosAI/StabilityMatrix#152]
Hi,

I would like to add the ComfyUI manager in my Stability Matrix version but it's not working (maybe I did a mistake by installing)

I use the first install method with CMD in custom_nodes dirextory with git clone and it's look like great installed : 
StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

but after relauch, no manager visible in ComfyUI.

In my Standalone version, it's work. (I was use the 2nd method by .bat file)

Any help ? Thanks a lot ! :)

**Comment by h34d1sd34d** [comment]
https://github.com/ltdrdata/ComfyUI-Manager

**Comment by tobecwb** [comment]
I also tried to install ComfyUI Manager, and at startup time, Python reports that a module is missing (GitPython).

For some reason, ComfyUI inside StabilityMatrix doesn't have this module.

After installing it manually, ComfyUI Manager starts normally.

How to install:
For reference, I am using Stability Matrix in **portable mode**, in a **Windows** environment, installed in **D:\StabilityMatrix** (make the necessary changes in your case).

1. Activate the ComfyUI Python environment within StabilityMatrix
Open a prompt or terminal (change the path to correct location in your case)
`cd D:\StabilityMatrix\Data\Packages\ComfyUI`
`venv\Scripts\activate`

2. Install the missing module
`pip install GitPython`

3. Install ComfyUI Manager (if not already done)
`cd custom_nodes`
`git clone https://github.com/ltdrdata/ComfyUI-Manager.git`

You can close the terminal and start ComfyUI again through Stability Matrix

**Comment by ionite34** [comment]
Implemented with built-in extensions management in newer version, simply search for ComfyUI-Manager and install, https://github.com/LykosAI/StabilityMatrix/releases

<img width="315" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/27d284db-08df-46f1-9252-535a9d1e482f">

<img width="625" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/df046025-c5d9-4606-92e4-0769937e3a5f">

**Comment by Kelthic** [comment]
> I also tried to install ComfyUI Manager, and at startup time, Python reports that a module is missing (GitPython).
> 
> For some reason, ComfyUI inside StabilityMatrix doesn't have this module.
> 
> After installing it manually, ComfyUI Manager starts normally.
> 
> How to install: For reference, I am using Stability Matrix in **portable mode**, in a **Windows** environment, installed in **D:\StabilityMatrix** (make the necessary changes in your case).
> 
> 1. Activate the ComfyUI Python environment within StabilityMatrix
>    Open a prompt or terminal (change the path to correct location in your case)
>    `cd D:\StabilityMatrix\Data\Packages\ComfyUI`
>    `venv\Scripts\activate`
> 2. Install the missing module
>    `pip install GitPython`
> 3. Install ComfyUI Manager (if not already done)
>    `cd custom_nodes`
>    `git clone https://github.com/ltdrdata/ComfyUI-Manager.git`
> 
> You can close the terminal and start ComfyUI again through Stability Matrix

You saved my life tho, thank you
