### ISSUE TITLE
Fooocus MRE does not offer latest update from 2.0.78 to 2.0.78.2

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#158]
On one computer, fresh install I believe, installed Fooocus MRE 2.0.78.2, but another computer is stuck on 2.0.78, which does not have ControlNet features.
Checking for update does not offer any even though the update became available 4 days ago.

**Comment by drdancm** [comment]
I uninstalled the current version and then installed it once again and that fixed the problem. So anyone else who has this problem should do the same.

**Comment by gmthedoc** [comment]
Try to install again using this settings:
![immagine](https://github.com/LykosAI/StabilityMatrix/assets/397693/8ee31504-b4dd-4722-9a02-fff1086a6721)

**Comment by drdancm** [comment]
Thanks for the help, but the good news is, that possibly after the latest  2.50 StabMatrix update, Fooocus has now updated to version 2.0.93. 

So, everything is fixed and working fine !
