### ISSUE TITLE
How can I install a python package ?

### ISSUE THREAD

**Issue by justarmadillo** [LykosAI/StabilityMatrix#159]
If I need to install python package on a **portable** AUTOMATIC1111 how can I do it ?

**Comment by mohnjiles** [comment]
Hi, you can use the python.exe inside the virtualenv to install python packages. For example, `<path_to_your_install>\Data\Packages\stable-diffusion-webui\venv\Scripts\python.exe -m pip <pip_packages_here>`

We do plan on making this an option in the UI at some point also, sorry for the trouble!

**Comment by ionite34** [comment]
Python Packages manager was added from package menu ![image](https://github.com/LykosAI/StabilityMatrix/assets/13956642/88bf4cee-fad0-4f05-bc33-487b60d78726)

**Comment by rostamiani** [comment]
Cannot find python package manager

**Comment by rostamiani** [comment]
Cannot find python package manager

**Comment by cen070** [comment]
> Cannot find python package manager
Took me a bit to find it too. It's under the 3 dot menu for each package. 
![2024-03-01 23_22_37-Stability Matrix](https://github.com/LykosAI/StabilityMatrix/assets/17262837/cfc42014-995b-40cf-a302-b7b1dc4abbcf)
