### ISSUE TITLE
Running StabilityMatrix on Visual Studio 2022

### ISSUE THREAD

**Issue by arafatx** [LykosAI/StabilityMatrix#160]
## Issue Running Project in Visual Studio 2022

Hello everyone,

I apologize for the off-topic post. This isn't directly related to issues in **StabilityMatrix**, but I'm encountering challenges when trying to run the project in **Visual Studio 2022**.

![Error Screenshot](https://github.com/LykosAI/StabilityMatrix/assets/4420157/5a841a16-bf5c-4d40-bade-98fa690f937b)

- **Platform**: Windows 11

### Troubleshooting Steps Taken:
- [x] Reinstalled Visual Studio 2022
- [x] Reinstalled MSIX extension
- [x] Reinstalled necessary .NET components
- [x] Engaged with BingChat and ChatGPT-4  with various solutions but none of them working 

Does anyone have insights on specific configurations needed to run this project in VS2022? I'm wondering if it might run without issues on **Visual Studio 2019** (though I haven't tested it). Any advice or guidance would be greatly appreciated.

**Comment by arafatx** [comment]
My bad, I think this is designed to work with VS code

**Comment by mohnjiles** [comment]
Hi, we actually use Rider primarily, but the issue here is that the `StabilityMatrix` project is our old WPF project that is no longer maintained - you'll need to set `StabilityMatrix.Avalonia` as the Startup Project and try again.

Sorry about that!

**Comment by arafatx** [comment]
Thank you got it. Changed to StabilityMatrix.Avalonia and it's working.
