### ISSUE TITLE
Add "Download Version" button in modelbrowser

### ISSUE THREAD

**Issue by Walmann** [LykosAI/StabilityMatrix#17]
Currently you can only download the newest version of a model when using the model browser. 
In the search querry results the "modelVersions" entry is a list of versions, so there should be too hard to implement?

**Comment by CHollman82** [comment]
2nd. This is important, it's not just versions/revisions either, some entries on CivitAI have multiple different models/extensions on the same page and right now it seems to just pick one randomly. Recently tried to import a TI with both a positive and negative embedding and it only imported the negative embedding, not the (more important) positive one.

**Comment by ionite34** [comment]
Added button for viewing all versions and files of versions for download - in https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.2.0

<img width="825" alt="all_versions_download" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/2c8faa2e-56c7-4e44-9f51-73e5b130ab94">
