### ISSUE TITLE
Feature Request:For inference

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#172]
would it be Possible to get Controlnet/OpenPose/DWPose for inference and also for inference something to help with art Styles etc something   like integrade StylePile,SDXL Styles or G-Prompter or even the Next Diffusion Prompter with it if its possible that is also if possible Clip Skip would be good to have too
Would it Be Possible to make inference Run with Invoke and A1111 and Fooocus+MRE as well Not just Comfy

**Comment by ionite34** [comment]
ControlNet/T2I is definitely coming next, looking to add a customizable steps control where you can add new steps and rearrange them. Quick UI preview:

![drag_config_3](https://github.com/LykosAI/StabilityMatrix/assets/13956642/034af0a4-41e3-4ae0-9fd2-d22a4542e0d2)
