### ISSUE TITLE
How to integrate ComfyUI windows portable in StabilityMatrix, to use Inference

### ISSUE THREAD

**Issue by ViratX** [LykosAI/StabilityMatrix#173]
Hi, 
So I downloaded the ComfyUI_windows_portable from official github: 
https://github.com/comfyanonymous/ComfyUI/releases/tag/latest

I've put entire self contained folder in the "StabilityMatrix\Packages\" directory. 

Upon importing it in StabilityMatrix and launching, I get the following error: 

```
E:\StabilityMatrix\Packages\ComfyUI_windows_portable\venv\Scripts\python.exe: can't open file 'E:\\StabilityMatrix\\Packages\\ComfyUI_windows_portable\\main.py': [Errno 2] No such file or directory

Process finished with exit code 2
``` 
I have no idea if it's relevant, but I think the correct directory would be: E:\StabilityMatrix\Packages\ComfyUI_windows_portable\ComfyUI\main.py
(instead of '\\ComfyUI_windows_portable\\main.py')

Please help me resolve this as I am not that technical, but I can follow instructions to fix it on my end.
If there's any way to install the ComfyUI_windows_portable from within the StabilityMatrix, I am will to do that too.
Looking forward to using Inference.

**Comment by ionite34** [comment]
The local package import currently only works with venv based packages, Stability Matrix has its own embedded Python distribution used to manage the venvs, so the portable ComfyUI is not supported.

You can click "add package" on the bottom of the packages page to install a new ComfyUI:
<img width="925" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/86691bb4-722b-45b1-b69b-d107ba99e2a2">

<img width="922" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/3c858f73-0e25-4ed4-9fbb-a8be0fbebecb">

**Comment by drdancm** [comment]
The way Comfy was presented is confusing. It was only I saw the Inference announcement that I figured out how to get the Inference interface that uses the Comfy underlying engine. Without the Inference interface I had no idea how to use the thing.

I had to test the idea that starting Inference would launch Comfy or not. I found that it could.
I wonder how many other less experienced people will have the same confusion as I did.

**Comment by drdancm** [comment]
As shown above you can install ComfyUI easily from inside StabilityM. Then just look for the Inference Icon on the left hand side (it is the 3rd icon from the top, just below the Launch icon. 

You might want to just delete ComfyUI, that you installed outside of StabilityM, so you don't waste storage space on an extra copy.

You don't need to launch ComfyUI from the usual Launch page, you can do it from inside Inference. There is a Launch Button on the Top Right Hand side (it says Launch, immediately to the left of the 3 vertical dots).
