### ISSUE TITLE
Can I manage pre-existing installs?

### ISSUE THREAD

**Issue by bbecausereasonss** [LykosAI/StabilityMatrix#174]
I already have auto's, comfy setup. Can they be managed with this?

**Comment by ionite34** [comment]
If you have a standard install (root folder containing "venv") of one of the auto or comfy you can move one to the `Data/Packages` folder of Stability Matrix and it will show up to import locally. On import it will move models into the shared folders that can be used by other packages as well.

![1000006416.png](https://github.com/LykosAI/StabilityMatrix/assets/13956642/fffb9472-44d4-4cb9-a3a5-03bd605bf758)
