### ISSUE TITLE
Custom packages

### ISSUE THREAD

**Issue by aolko** [LykosAI/StabilityMatrix#176]
Allow users to define custom packages so they can install any UIs just like https://pinokio.computer/

**Comment by katyukuki** [comment]
"I am really looking forward to the custom package feature and am hoping that there will be support for adding EasyDiffusion as well. Thank you!"
[easydiffusion](https://github.com/easydiffusion/easydiffusion)

**Comment by agora-coffee** [comment]
I would like to integrate Kohya into Stability Matrix for LORAS training
