### ISSUE TITLE
Requested Feedback on Inference and Comfy

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#178]
The way Comfy was presented is confusing. It was only after I saw the Inference announcement that I figured out how to get the Inference interface that uses the Comfy underlying engine. Without the Inference interface, I had no idea how to use it. I was going to watch some Comfy tutorials on ytube, but it turned out I did not need to do that yet.

I wonder how many other less experienced people will have the same confusion as I did. 

I had to test the idea that starting Inference would launch Comfy or not. I found that it could.

I expected the Comfy page to reflect what was being processed from Inference, but I could not see any evidence for that.

There was also at some point an error message saying that there was interference from another process using the "engine?".  Don't know what prompted that message. Perhaps because I clicked to see the Comfy web browser page?

Since you wanted feedback, here is more:

1 Instead of showing in list of Packages  Invoke, Fooocus, Comfy etc,  why not show Inference-Comfy ?
That would be a lot more clearer.

2 When launching,  **END  with showing the INFERENCE PAGE** (more familiar look), rather than the rather forbidding Comfy page, when you launch Comfy rather than from the Inference icon on the side,  which unless you have spent time learning to use, is difficult to put to immediate use, other than getting the demo Cup.

3 A really useful bit of help would be a Preset Filter for Models. With StabMatrix, because of the excellent share feature, we end up with too many models, so being able to type the first few letters of what we want would be a terrific, handy time saver. It wold also be good to have a button for filtering SDXL vs SD 1.5 also.

4 Perhaps it would also be helpful to most people to have the option in Inference, of remembering the settings (models, FreeU, Hires Fix, Upscale, and especially the Negative Prompt and the Prom,pt itself (ideally in Preference Setup everyone could simple show what they want with mark in a checkbox next to these parameters. It is more likely that you use the same settings you used before than something completely different. In any case you are no worse off than having the standard, default, settings.

5 Right now I don't see any ControlNET features and I'm guessing it's coming but all this takes a lot of time and work.

In any case it's really GOOD !   THANKS !

**Comment by ionite34** [comment]
Thanks for the feedback, for (4) remembering the current settings, this is already possible - just need to use the top right menu to save the current project as file. Previously opened projects will be restored on launch.

**Comment by drdancm** [comment]
ionite34,

That's great news. I wish all the packages had that option. Thanks !
