### ISSUE TITLE
add settings for the proxy server?

### ISSUE THREAD

**Issue by solomon-s2020** [LykosAI/StabilityMatrix#180]
StabilityMatrix is a great software. Can I add settings for the proxy server?

**Comment by ionite34** [comment]
Hm, like for Stability Matrix's network communications? It would apply to things like civitai model downloads for example. But I don't think we can affect proxy usage by the Python processes, (like if a webui tries to git clone) would that still be useful for you?

**Comment by catshitz** [comment]
I think he means the StabilityMatrix.exe, and yes, downloading models from civitai in Stability Matrix(in order to properly get and archive the metadata files), it's necessary to add a proxy option in setting page.

**Comment by blackholeearth** [comment]
hello..!!!!!!! ............. should i do it ?  

i press download  confmy ui..  it fails to install..    

it says   "" github host not resolved....""

but i can open  google youtube github etc via  via web browser..

**Comment by dennisdebel** [comment]
Same issue here. Somehow the app seems to ignore my vpn. Setting env variables and git proxy doesnt seem to help. 

> hello..!!
> 
> i press download comfy ui.. it fails to install..
> 
> it says "" github host not resolved....""
> 
> but i can open google youtube github etc via via web browser..
> 
> Unpacking resources
> Unpacking resources
> Could not install ComfyUI (StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'D:\_LLM\StabilityMatrix_app\Data\Packages\ComfyUI'...
> fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI/': Could not resolve host: github.com
> }
>    at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
>    at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
>    at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageOptions options, IProgress`1 progress, CancellationToken cancellationToken)
>    at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps))
> 
> ````
