### ISSUE TITLE
Kohya-ss GUI with Stability Matrix

### ISSUE THREAD

**Issue by noembryo** [LykosAI/StabilityMatrix#182]
Well, this is more something like a question.
My system has Python 2.7 installed (and I need) and that's why I used your incredible portable solution to run A1111 with great success.

Trying to train a LoRA now, and all the instructions are for Kohya-ss which uses its own web GUI.
I can't install it for the same reasons that I couldn't install A1111, but I was wondering, since most of its dependencies are included in the Stability Matrix's installation, if there was a way to run it using these portable libraries.

If this question is totally out of the scope of this project, please, disregard it and thank you for your time. 😃

**Comment by aolko** [comment]
#176

**Comment by ionite34** [comment]
Added since v2.8.0 https://github.com/LykosAI/StabilityMatrix/releases/latest
