### ISSUE TITLE
ModuleNotFoundError: No module named 'clip'

### ISSUE THREAD

**Issue by bingobongo-mx** [LykosAI/StabilityMatrix#184]
Hello, how should I proceed on ArchLinux. All installed, starting Lounch, getting this error.

"/home/user/StabilityMatrix-linux-x64/Data/Packages/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/evaluation.py", line 6, in <module>

**Comment by bingobongo-mx** [comment]
fixed it, I had --skip-install active, never mind

**Comment by mohnjiles** [comment]
Sorry about that, we mistakenly set the --skip-install option to default to Enabled. It should be fixed & default to Disabled in v2.5.3 or later.
