### ISSUE TITLE
Sentry and unhandled exceptions

### ISSUE THREAD

**Issue by bruno-garcia** [LykosAI/StabilityMatrix#187]
This isn't really an issue, just sharing some details about Sentry: I was peeking at the API usage of Sentry and noticed you have your own implementation of UnhandledException:

https://github.com/LykosAI/StabilityMatrix/blob/3866e57e2ebc7b5dbd0ccbd535309febf6770b72/StabilityMatrix/App.xaml.cs#L394-L397

Sentry sets the `mechanism`, which helps display crashes in Sentry vs non-crashes. With the read banner `unhandled`:

https://github.com/getsentry/sentry-dotnet/blob/407dc28dbd7f1c29059fc509a886b114a2c75b0b/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L32-L47

For example, non-crash vs crashed:

![image](https://github.com/LykosAI/StabilityMatrix/assets/1633368/a10eacf6-d85c-4951-9614-2c836c4f7113)

Sentry by default de-duplicates a capture that involves the same exception instance. So the second attempt to capture it will just drop the event:

https://github.com/getsentry/sentry-dotnet/blob/407dc28dbd7f1c29059fc509a886b114a2c75b0b/src/Sentry/Internal/DuplicateEventDetectionEventProcessor.cs#L14-L28

So it's possible that your code trying to capture the event with Sentry is not really resulting in a capture. Or, if yours run before Sentry's (you'd notice the `unhandled` missing), Sentry's default unhandled exception handling is not capturing it, but at least it's `Flush` is running. You can disable the default Sentry behavior:

https://docs.sentry.io/platforms/dotnet/configuration/disable-integrations/#disableappdomainunhandledexceptioncapture

But I'd recommend keeping the Sentry default integration, as we might continue to improve it and you get that for free. If you decide to remove it, worth adding `Flush` to your own, as we did.

One smaller thing: `Enhanced` is the default mode. We'd just not use that if not possible (e.g: Unity, NativeAOT, etc):

https://github.com/LykosAI/StabilityMatrix/blob/3866e57e2ebc7b5dbd0ccbd535309febf6770b72/StabilityMatrix/App.xaml.cs#L95

https://github.com/getsentry/sentry-dotnet/blob/407dc28dbd7f1c29059fc509a886b114a2c75b0b/src/Sentry/SentryOptions.cs#L866

**Comment by ionite34** [comment]
Thanks for the insight. I think we were getting the behavior of not seeing the AppDomain exceptions not marked as "Unhandled". In this case I assume just getting rid of our `SentrySdk.CaptureException` and `logger?.LogCritical` (Since we also use the NLog Sentry integration for critical levels), would enable Sentry to automatically handle the AppDomain exception? 

Not sure if our shutdown and `Environment.Exit(1)` would interfere with the default integration capture?

**Comment by bruno-garcia** [comment]
> In this case I assume just getting rid of our SentrySdk.CaptureException and logger?.LogCritical

Right, the Sentry SDK will already deal with the NLog log levels

From [our docs](https://docs.sentry.io/platforms/dotnet/guides/nlog/), you can configure it though:
```
        // Debug and higher are stored as breadcrumbs (default is Info)
        o.MinimumBreadcrumbLevel = LogLevel.Debug;
        // Error and higher is sent as event (default is Error)
        o.MinimumEventLevel = LogLevel.Error;
```

> Though, not sure if our App Shutdown and Environment.Exit(1) in the CurrentDomain_UnhandledException function would interfere with the default integration capture?

Before calling `Environment.Exit` ideally you call `SentrySdk.Close` to force flush all events out.
We have an integration by default that should do this: https://github.com/getsentry/sentry-dotnet/blob/aa5fc75ff0f3b91e4d3c90f7e25b615ad501f0f9/src/Sentry/Integrations/AppDomainProcessExitIntegration.cs
But prob best to do it before hand to make sure (I found this hook from .NET kind of flaky back in the day)
