### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by CHollman82** [LykosAI/StabilityMatrix#19]
![image](https://github.com/LykosAI/StabilityMatrix/assets/3136566/97ce9b5a-de38-40c1-ae70-d32c940174c3)

**Comment by ionite34** [comment]
Hi @CHollman82, thanks for the report, this seems to occur when the chosen directory wasn't created. We now check and create directories in v1.1.4 so this should be fixed: https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.1.4

**Comment by CHollman82** [comment]
My bad, was trying to install to an external drive that was formatted exFAT, which doesn't support reparse points. I installed to an NTFS drive successfully.
