### ISSUE TITLE
Can't find python310._pth on install

### ISSUE THREAD

**Issue by AnotherRandomNameNotTaken** [LykosAI/StabilityMatrix#2]
![Screenshot 2023-06-27 214235](https://github.com/LykosAI/StabilityMatrix/assets/35236663/de22dbd9-6009-41ac-98d0-63efb3f200b9)

**Comment by ionite34** [comment]
We're currently investigating this issue. If you open `C:\Users\...\AppData\Roaming\StabilityMatrix\Assets\Python310` can you send a screenshot of all the files inside? If that folder exists? Thank you!

**Comment by AnotherRandomNameNotTaken** [comment]
Here is the screenshot as requested. It seems only 2 files are in there.
![Screenshot 2023-06-28 081702](https://github.com/LykosAI/StabilityMatrix/assets/35236663/3ac7993c-50f6-4683-8344-f233556d9481)

**Comment by ionite34** [comment]
We've found the root issue, which seems to have been related to spaces or special characters in usernames, this was fixed in release v1.1.2! https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.1.2
