### ISSUE TITLE
Allow easier install of SD.Next and CozyUI

### ISSUE THREAD

**Issue by ForgetfulWasAria** [LykosAI/StabilityMatrix#20]
Currently, Stability Matrix offers to install automatic1111, which is certainly the most popular and thus a very defensible choice. It would be nice if it offered the choice to install any of the three without cancelling out of the install process. Essentially, move the add packages pane to the main install. Perhaps there should be a short blurb explaining what each  one is:

* Automatic1111: The most popular and generally the first to receive new features.
* SD.Next: A fork of automatic1111 that focuses on user experience improvements while maintaining high compatibility with a111.
* CozyUI: Uses a node based interface that is extremely powerful but has a steep learning curve.

Also, I keep forgetting that "Packages" is where the webui is installed. Maybe it could be called "Install" instead?

**Comment by ionite34** [comment]
Added in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.0.0 with https://github.com/LykosAI/StabilityMatrix/commit/de59a796f7dcd0d8e45e3b968a3061b1252de145

<img width="825" alt="one_click" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/af831673-6bc6-4fa8-8f85-b59e2f06eafe">

First time prompt should now show all 3 packages as options with an explanation and thumbnail.

**Comment by ForgetfulWasAria** [comment]
Looks awesome, thanks!
