### ISSUE TITLE
Sadtalker

### ISSUE THREAD

**Issue by Revmagi** [LykosAI/StabilityMatrix#201]
To run SadTalker you need to put the external directory path into webui-user above the command line arguments. I have tried adding this to every possibly file and it is not working. How can I set this before the arguments saved and passed to the launch?

set SADTALKER_CHECKPOINTS=D:\SadTalker\checkpoints

**Comment by mohnjiles** [comment]
You should be able to add these to the Environment Variables in the Settings tab like so:
![image](https://github.com/LykosAI/StabilityMatrix/assets/33761/bba2c53e-398b-41a4-bebe-6f3bda30d364)

**Comment by JCharleston-CLN** [comment]
Thank you very much. I will give that a try.
