### ISSUE TITLE
dont know how to fix this 

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#204]
this error shows up when trying to launch Stable Diffusion WebUI 1.6.0
![error](https://github.com/LykosAI/StabilityMatrix/assets/137729901/20e2e943-7807-40cf-bbac-c2ebc6330b00)
i dont know how to fix that one

**Comment by ionite34** [comment]
This should be resolved with our updated shared folder process for the A1111 webui.
