### ISSUE TITLE
Process Exception while trying to install A1111

### ISSUE THREAD

**Issue by nealsolves** [LykosAI/StabilityMatrix#207]
Facing this error while installing --

**Process Exception:**

`pip install failed with code 2: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118\r\nCollecting torch==2.0.1\r\n  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)\r\n     ---------------------------------------- 2.6/2.6 GB 131.0 MB/s eta 0:00:00\r\nCollecting torchvision\r\n  Downloading https://download.pytorch.org/whl/cu118/torchvision-0.16.0%2Bcu118-cp310-cp310-win_amd64.whl (5.0 MB)\r\n     ---------------------------------------- 5.0/5.0 MB 106.2 MB/s eta 0:00:00\r\nCollecting filelock (from torch==2.0.1)\r\n  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/5e/5d/97afbafd9d584ff1b45fcb354a479a3609bd97f912f8f1f6c563cb1fae21/filelock-3.12.4-py3-none-any.whl.metadata\r\n  Downloading filelock-3.12.4-py3-none-any.whl.metadata (2.8 kB)\r\nCollecting typing-extensions (from torch==2.0.1)\r\n  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata\r\n  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)\r\nCollecting sympy (from torch==2.0.1)\r\n  Downloading https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)\r\n     ---------------------------------------- 5.7/5.7 MB 92.5 MB/s eta 0:00:00\r\nCollecting networkx (from torch==2.0.1)\r\n  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)\r\n     ---------------------------------------- 2.1/2.1 MB 21.9 MB/s eta 0:00:00\r\nCollecting jinja2 (from torch==2.0.1)\r\n  Downloading https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)\r\n     ---------------------------------------- 133.1/133.1 kB ? eta 0:00:00\r\nCollecting numpy (from torchvision)\r\n  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/cc/05/ef9fc04adda45d537619ea956bc33489f50a46badc949c4280d8309185ec/numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata\r\n  Downloading numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata (61 kB)\r\n     ---------------------------------------- 61.1/61.1 kB ? eta 0:00:00\r\nCollecting requests (from torchvision)\r\n  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata\r\n  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)\r\nINFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.\r\nCollecting torchvision\r\n  Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/59/af/426c2b90f5c4f8aba778746465af9e662680570e950e02379e91c6138285/torchvision-0.16.0-cp310-cp310-win_amd64.whl.metadata\r\n  Downloading torchvision-0.16.0-cp310-cp310-win_amd64.whl.metadata (6.6 kB)\r\n  Downloading https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)\r\n     ---------------------------------------- 4.9/4.9 MB 78.4 MB/s eta 0:00:00\r\nCollecting pillow!=8.3.*,>=5.3.0 (from torchvision)\r\n  Obtaining dependency information for pillow!=8.3.*,>=5.3.0 from https://files.pythonhosted.org/packages/23/ca/7296d769f62266c0f94bf76496bc77114e7a96d2de3d7bcba91d0ba2856f/Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata\r\n  Downloading Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata (9.6 kB)\r\nERROR: Exception:\r\nTraceback (most recent call last):\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher\r\n    yield\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read\r\n    data = self._fp_read(amt) if not fp_closed else b""\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read\r\n    return self._fp.read(amt) if amt is not None else self._fp.read()\r\n  File "http\client.py", line 466, in read\r\n  File "socket.py", line 705, in readinto\r\n  File "ssl.py", line 1274, in recv_into\r\n  File "ssl.py", line 1130, in read\r\nTimeoutError: The read operation timed out\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper\r\n    status = run_func(*args)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper\r\n    return func(self, options, args)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 377, in run\r\n    requirement_set = resolver.resolve(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve\r\n    result = self._result = resolver.resolve(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve\r\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve\r\n    failure_causes = self._attempt_to_pin_criterion(name)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion\r\n    criteria = self._get_updated_criteria(candidate)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria\r\n    self._add_to_criteria(criteria, requirement, parent=candidate)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria\r\n    if not criterion.candidates:\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__\r\n    return bool(self._sequence)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__\r\n    return any(self)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>\r\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built\r\n    candidate = func()\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link\r\n    self._link_candidate_cache[link] = LinkCandidate(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__\r\n    super().__init__(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__\r\n    self.dist = self._prepare()\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare\r\n    dist = self._prepare_distribution()\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution\r\n    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 532, in prepare_linked_requirement\r\n    metadata_dist = self._fetch_metadata_only(req)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 383, in _fetch_metadata_only\r\n    return self._fetch_metadata_using_link_data_attr(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 403, in _fetch_metadata_using_link_data_attr\r\n    metadata_file = get_http_url(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url\r\n    from_path, content_type = download(link, temp_dir.path)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__\r\n    for chunk in chunks:\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks\r\n    for chunk in response.raw.stream(\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream\r\n    data = self.read(amt=amt, decode_content=decode_content)\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read\r\n    with self._error_catcher():\r\n  File "contextlib.py", line 153, in __exit__\r\n  File "C:\Users\nilan\Documents\Gen AI\Tools\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher\r\n    raise ReadTimeoutError(self._pool, None, "Read timed out.")\r\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.\r\n'`

**Callstack**

at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(String args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.BasePackage.InstallCudaTorch(PyVenvRunner venvRunner, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.InstallPackage(String installLocation, TorchVersion torchVersion)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DoInstall()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Thre

**Comment by LadyFlames** [comment]
facing a Similar issue  while Re-installing 
![Näyttökuva (10)](https://github.com/LykosAI/StabilityMatrix/assets/137729901/689a6ec0-72f9-4d7a-9e77-ca1cc0c86be8) the list of the error is too long to fit in it

**Comment by ExLuck6** [comment]
same here, first time for me though, i am a newcomer, hello everyone

**Comment by LadyFlames** [comment]
first invoke has problems now SD Web UI problems but  the other ones meaning Fooocus,Fooocus MRE,Comfy,Inference work perfectly fine its only invoke and SD web ui that are facing major issues

**Comment by ExLuck6** [comment]
hmm, thank you for that info! I clicked the install button for fooocus MRE, it is currently installing, hopefully it will work, i am excited to use AI, its gonna be very fun! :D , I would use bing AI (i think they use dale) but i just felt restricted, plus my internet is not good and i have low internet quota/bandwiith monthly so it is great that i can use AI offline, i am mainly using it for fun/personal, it just looks cool

**Comment by Drun555** [comment]
I submitted PR to InvokeAI to change xFormers dependency from '~=0.0.19' to '0.0.20' - it should fix InvokeAI installation problem.

**Comment by mohnjiles** [comment]
Sorry folks, seems to be an issue with the xformers package. They released an update that is failing to build on Windows machines. You can follow along with the issue on their repo: https://github.com/facebookresearch/xformers/issues/886

If it is not fixed by them soon, we will release a hotfix to pin the xformers to a version that's known working.

**Comment by ExLuck6** [comment]
Thank you very much! You are the best!! I am updating stability matrix to the latest version right now, still downloading models/checkpoints/loras, haven't generated anything yet but i am very excited! :D , gonna use the a1111 ui when i finish updating the program

**Comment by ionite34** [comment]
Fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.5.4
