### ISSUE TITLE
Allow to choose installation directory

### ISSUE THREAD

**Issue by sgstq** [LykosAI/StabilityMatrix#21]
## Feature Request: Custom Directory for Installation

Hello there! 😊 First off, thanks for your amazing tool you're working on! 🙌

A potential enhancement could be:
- An option to install the project and its dependencies into a user-defined directory or disk. 

This feature would increase user flexibility and resource management. 💼👍 

Your consideration is much appreciated! 🙏

**Comment by ionite34** [comment]
Hi, thank you. On launch (starting from v1.1.0) there should be a prompt asking where you'd like the Data Directory to be, which is where it will install things like Web-UI Packages and Model checkpoints. Or you can choose "Portable Mode" to store in a "Data" folder next to the app exe, which you can move with the app to another drive or computer.

**Comment by sgstq** [comment]
Oh, nice! Tried the latest one (1.1.4) the prompt works. Thank you 🤗
