### ISSUE TITLE
Wrong character in terminal

### ISSUE THREAD

**Issue by noembryo** [LykosAI/StabilityMatrix#221]
This is a really minor issue, but I just wondering if there is a way to change the terminal font.
In my system (Windows 10 x64 22H2 with Greek locale), the characters that try to simulate a progress bar are displayed as their name codes:
![Term1](https://github.com/LykosAI/StabilityMatrix/assets/24675403/8244adf2-f60a-4f35-896f-90b948252a4f)
It's not something serious, just wanted to let you know about it and if there is a way to fix it.. 😃

**Comment by ionite34** [comment]
Fixed since https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.0
