### ISSUE TITLE
Batch Img2img doesn't work in A1111 1.6 package. Works in 1.5.2 Though

### ISSUE THREAD

**Issue by DoubleZeroziilch** [LykosAI/StabilityMatrix#222]
Had a lot of cuda core bug reports. 

Main error was: KeyError: 'save_to_dirs'

Previously I was using several extensions, as suggested by reddit I disabled all extensions. Issue still remained with a fresh install of the 1.6 a1111 package in the stability matrix UI with no extensions.

Needs fixing, I love 1.6 but however its implemented in stability matrix is heavily flawed. Could be A1111 1.6 itself, been seeing other people complaining about it as well being buggy. 

Reverted to 1.5.2, did the exact same batch command and it magically worked.

**Comment by ionite34** [comment]
Seems to be a package related issue in 1.6, should be resolved in latest versions.
