### ISSUE TITLE
An error occurred while installing AUTOMATIC1111 

### ISSUE THREAD

**Issue by ZhiyuXu0124** [LykosAI/StabilityMatrix#226]
**python version: 3.10.11
stability matrix version: 2.5.6**
**winodws10**
**error info:**

> pip install failed with code 1: 'Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting GitPython==3.1.32
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/67/50/742c2fb60989b76ccf7302c7b1d9e26505d7054c24f08cc7ec187faaaea7/GitPython-3.1.32-py3-none-any.whl (188 kB)
     -------------------------------------- 188.5/188.5 kB 1.4 MB/s eta 0:00:00
Collecting Pillow==9.5.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3e/14/0030e542f2acfea43635e55584c114e6cfd94d342393a5f71f74c172dc35/Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 16.0 MB/s eta 0:00:00
Collecting accelerate==0.21.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/70/f9/c381bcdd0c3829d723aa14eec8e75c6c377b4ca61ec68b8093d9f35fc7a7/accelerate-0.21.0-py3-none-any.whl (244 kB)
     ------------------------------------- 244.2/244.2 kB 14.6 MB/s eta 0:00:00
Collecting basicsr==1.4.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz (172 kB)
     ---------------------------------------- 172.5/172.5 kB ? eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting blendmodes==2022
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a9/1a/fc3216efda12211fd50823a720fed817e6d936ecacd9531277207c4e9838/blendmodes-2022-py3-none-any.whl (10 kB)
Collecting clean-fid==0.1.35
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/70/56/0dfc83e0fe455cfe6272b23a65039b4101c63a4e7446801e26178b675fbf/clean_fid-0.1.35-py3-none-any.whl (26 kB)
Collecting einops==0.4.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/df/bf/18c6c753fe699c44e3d6013d75074e15f139f9a9adbaeb108f61d73d18d1/einops-0.4.1-py3-none-any.whl (28 kB)
Collecting fastapi==0.94.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f5/07/8e950c4bcb953a0bcbb41e0d7b1d5496f9792edfd0dc2cd518cd7a42f948/fastapi-0.94.0-py3-none-any.whl (56 kB)
     ---------------------------------------- 56.3/56.3 kB ? eta 0:00:00
Collecting gfpgan==1.3.8
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/80/a2/84bb50a2655fda1e6f35ae57399526051b8a8b96ad730aea82abeaac4de8/gfpgan-1.3.8-py3-none-any.whl (52 kB)
     ---------------------------------------- 52.2/52.2 kB ? eta 0:00:00
Collecting gradio==3.41.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/df/e7/e0b548208ff5db6323ad974f094e9435adb0a377f35274196fb74adaf58a/gradio-3.41.2-py3-none-any.whl (20.1 MB)
     --------------------------------------- 20.1/20.1 MB 59.4 MB/s eta 0:00:00
Collecting httpcore==0.15
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ad/b9/260603ca0913072a10a4367c2dca9998706812a8c1f4558eca510f85ae16/httpcore-0.15.0-py3-none-any.whl (68 kB)
     ---------------------------------------- 68.4/68.4 kB ? eta 0:00:00
Collecting inflection==0.5.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/59/91/aa6bde563e0085a02a435aa99b49ef75b0a4b062635e606dab23ce18d720/inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting jsonmerge==1.8.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/37/1b/05dd6fd53a76a73e898f3d2b60d02ee90af9e11de2f8e3802a6262fa1ca9/jsonmerge-1.8.0.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting kornia==0.6.7
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7a/7f/5ec91cec58e02a41b1b0ea0fe9f0b2506cb68d497cf94382d464b2af77f4/kornia-0.6.7-py2.py3-none-any.whl (565 kB)
     ------------------------------------- 565.1/565.1 kB 34.7 MB/s eta 0:00:00
Collecting lark==1.1.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/cb/c0/a670f7247fd552ea94d02aed37ecaed3198448f01a402a805c12f2a4db76/lark-1.1.2-py2.py3-none-any.whl (104 kB)
     ---------------------------------------- 104.7/104.7 kB ? eta 0:00:00
Collecting numpy==1.23.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/03/ae6c3c307f9c5c7516de3df3e764ebb1de33e54e197f0370992138433ef4/numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
     --------------------------------------- 14.6/14.6 MB 73.0 MB/s eta 0:00:00
Collecting omegaconf==2.2.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/98/c3/f00dcd6935c11555db6ad55bdada58706120974cacf9a861a7b948ea0619/omegaconf-2.2.3-py3-none-any.whl (79 kB)
     ---------------------------------------- 79.3/79.3 kB ? eta 0:00:00
Collecting open-clip-torch==2.20.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/70/b9/a9f2c37f998c20be57fed0128934f4a311c6596c1f6b9c2fe358b26125bc/open_clip_torch-2.20.0-py3-none-any.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB ? eta 0:00:00
Collecting piexif==1.1.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2c/d8/6f63147dd73373d051c5eb049ecd841207f898f50a5a1d4378594178f6cf/piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting psutil==5.9.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/86/f3/23e4e4e7ec7855d506ed928756b04735c246b14d9f778ed7ffaae18d8043/psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
     ---------------------------------------- 255.1/255.1 kB ? eta 0:00:00
Collecting pytorch_lightning==1.9.4
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ce/ac/09980114432e759e56e8ff35c16d05dd7c8c0f512c9a88a91c5110272a1f/pytorch_lightning-1.9.4-py3-none-any.whl (827 kB)
     -------------------------------------- 827.8/827.8 kB 5.2 MB/s eta 0:00:00
Collecting realesrgan==0.3.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b2/3e/e2f79917a04991b9237df264f7abab2b58cf94748e7acfb6677b55232ca1/realesrgan-0.3.0-py3-none-any.whl (26 kB)
Collecting resize-right==0.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1d/08/c5c0640a08d7b373f1175c536462862054ee32145dae457c89916cd568d2/resize_right-0.0.2-py3-none-any.whl (8.9 kB)
Collecting safetensors==0.3.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/39/7b/c785536dc1307214f4def6e6ddd772c9a76d3b5798f2961644fac10f373d/safetensors-0.3.1-cp310-cp310-win_amd64.whl (263 kB)
     ---------------------------------------- 263.7/263.7 kB ? eta 0:00:00
Collecting scikit-image==0.21.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f3/93/65601f7577d6fd49ec23bf8fb58c04d8170b06a1544452ae2ea9f59bf11f/scikit_image-0.21.0-cp310-cp310-win_amd64.whl (22.8 MB)
     --------------------------------------- 22.8/22.8 MB 72.5 MB/s eta 0:00:00
Collecting timm==0.9.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/29/90/94f5deb8d76e24a89813aef95e8809ca8fd7414490428480eda19b133d4a/timm-0.9.2-py3-none-any.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 135.2 MB/s eta 0:00:00
Collecting tomesd==0.1.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0c/02/367c67c8f510313f143a7818e92254a5f861c7d94c98ad6a08d25db52fee/tomesd-0.1.3-py3-none-any.whl (11 kB)
Collecting torchdiffeq==0.2.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2c/9b/b9c3e17f261e30f630511390e0dd33fc529073f1f2db222a1f09dc49a1ae/torchdiffeq-0.2.3-py3-none-any.whl (31 kB)
Collecting torchsde==0.2.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (59 kB)
     ---------------------------------------- 59.2/59.2 kB ? eta 0:00:00
Collecting transformers==4.30.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5b/0b/e45d26ccd28568013523e04f325432ea88a442b4e3020b757cf4361f0120/transformers-4.30.2-py3-none-any.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 50.8 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1 (from GitPython==3.1.32)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fd/5b/8f0c4a5bb9fd491c277c21eff7ccae71b47d43c4446c9d0c6cff2fe8c2c4/gitdb-4.0.11-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.7/62.7 kB ? eta 0:00:00
Collecting packaging>=20.0 (from accelerate==0.21.0)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl (53 kB)
     ---------------------------------------- 53.0/53.0 kB ? eta 0:00:00
Collecting pyyaml (from accelerate==0.21.0)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
     ---------------------------------------- 145.3/145.3 kB ? eta 0:00:00
Requirement already satisfied: torch>=1.10.0 in f:\ufffd�Ŀ�ļ�\stabilitymatrix-win-x64\data\packages\stable-diffusion-webuienv\lib\site-packages (from accelerate==0.21.0) (2.0.1+cu118)
Collecting addict (from basicsr==1.4.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting future (from basicsr==1.4.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz (840 kB)
     ------------------------------------- 840.9/840.9 kB 55.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting lmdb (from basicsr==1.4.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/66/05/21a93eed7ff800f7c3b0538eb12bde89660a44693624cd0e49141beccb8b/lmdb-1.4.1-cp310-cp310-win_amd64.whl (100 kB)
     ---------------------------------------- 100.1/100.1 kB ? eta 0:00:00
Collecting opencv-python (from basicsr==1.4.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/38/d2/3e8c13ffc37ca5ebc6f382b242b44acb43eb489042e1728407ac3904e72f/opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
     --------------------------------------- 38.1/38.1 MB 54.7 MB/s eta 0:00:00
Requirement already satisfied: requests in f:\ufffd�Ŀ�ļ�\stabilitymatrix-win-x64\data\packages\stable-diffusion-webuienv\lib\site-packages (from basicsr==1.4.2) (2.31.0)
Collecting scipy (from basicsr==1.4.2)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3a/98/3041681b3a0fef0f59033861a05d846aa1d284b07b531ce35b1b97cc2e93/scipy-1.11.3-cp310-cp310-win_amd64.whl (44.1 MB)
     --------------------------------------- 44.1/44.1 MB 59.4 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of basicsr to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tb-nightly (from basicsr) (from versions: none)
ERROR: No matching distribution found for tb-nightly

**Comment by ZhiyuXu0124** [comment]
Maybe it's because of the python version?
But how can I change the python version in matrix version
![1698837769343](https://github.com/LykosAI/StabilityMatrix/assets/56537567/8800f7e3-2b25-4491-94ba-c2c71877c898)

**Comment by Kagenokami** [comment]
I can confirm that I also received the same or similar error when attempting to install AUTOMATIC11111 using Stability Matrix. Is anyone attempting to fix this? I'd like to use SM to access SD, but if it won't run...

**Comment by CSmith1998** [comment]
I'd like to add that I also received this same, or similar, issue when attempting to install the ComfyUI package.
