### ISSUE TITLE
AsyncConnectionPool - issue

### ISSUE THREAD

**Issue by Jelared** [LykosAI/StabilityMatrix#232]
import gradio  # noqa: F401
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>
    from gradio import utils
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 353, in <module>
    class AsyncRequest:
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
    self._transport = self._init_transport(
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
  File "D:\Creation - AI\Stability Matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

Process finished with exit code 1

I need you help ?

**Comment by ivaxsirc** [comment]
the same problem, i've tried with the first version 1.0.1, diferent drive folder, nothing works

thks 

#> Looks like I'm getting the same after a clean install of StabilityMatrix and SD Web UI, and default launch options:
> 
> ```
> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> Version: 1.6.0
> Commit hash: <none>
> Launching Web UI with arguments: --xformers --api --skip-python-version-check
> Traceback (most recent call last):
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\launch.py", line 48, in <module>
>     main()
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\launch.py", line 44, in main
>     start()
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\modules\launch_utils.py", line 432, in start
>     import webui
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\webui.py", line 13, in <module>
>     initialize.imports()
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\modules\initialize.py", line 21, in imports
>     import gradio  # noqa: F401
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
>     import gradio.components as components
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
>     from gradio.components.annotated_image import AnnotatedImage
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>
>     from gradio import utils
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 353, in <module>
>     class AsyncRequest:
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 372, in AsyncRequest
>     client = httpx.AsyncClient()
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_client.py", line 1397, in __init__
>     self._transport = self._init_transport(
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_client.py", line 1445, in _init_transport
>     return AsyncHTTPTransport(
>   File "K:\Program Files\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\httpx\_transports\default.py", line 275, in __init__
>     self._pool = httpcore.AsyncConnectionPool(
> TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
> 
> Process finished with exit code 1
> ```

**Comment by CircleD5** [comment]
I also get the same problem after a clean install

**Comment by CircleD5** [comment]
OK, I found, by selecting the Master branch when installing automatic1111 webui with StablityMatrix, the above error no longer occurs!

**Comment by CircleD5** [comment]
If you want to use an older version of Webui,
First go to the Webui folder already installed using CMD, activate the venv environment and run the command "pip install httpx==0.24.1". (For more detailed instructions, please see the Automatic1111 bug report above.)

**Comment by mohnjiles** [comment]
Hi folks, sorry about that, seems to be an issue with the 1.6.0 version of A1111's webUI. We should have a fix for this in the next update. In the meantime, you can try the fix mentioned above, by installing httpx it should fix the issue.

**Comment by mohnjiles** [comment]
This should be fixed as of the latest v2.6.0 version of Stability Matrix. Please feel free to reopen this issue if the problem persists. Thanks!
