### ISSUE TITLE
Invoke AI fails to generate image: error Input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags

### ISSUE THREAD

**Issue by chozabu** [LykosAI/StabilityMatrix#237]
Trying out stability matrix, the inbuilt inference and fooocus-mre seem to work fine, but InvokeAI fails on a regular text-to-image prompt with the error:

`error Input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags`

Installing InvokeAI directly from their own repo, I didn't encounter the issue, only when installed through stability matrix

related issue at invoke tracker here: https://github.com/invoke-ai/InvokeAI/issues/4998

**Comment by centomila** [comment]
Same problem. I've also tried to update to 3.3post3 and then to 3.4rc

Tested with Stability Matrix 2.5.6 and 2.5.7 on Windows 11 Pro with nVidia GPU


```
Input tag 'metadata_accumulator' found using 'type' does not match any of the expected tags: 'denoise_latents', 'ip_adapter',...
Path: body.batch.graph.nodes.metadata_accumulator
```

**Comment by alecs91ro** [comment]
Can confirm, i have the same issue.

**Comment by chozabu** [comment]
Hmm, It's working for me now, having removed and reinstalled the invokeAI package (for a second time)
@alecs91ro @centomila

**Comment by psychedelicious** [comment]
@ionite34 
Hi, InvokeAI contributor here, wanted to add some detail which may be helpful.

We unintentionally had an RC release get marked as a stable release (3.4.xyz). This has been rectified. The current stable release is 3.3.0. 

The error in this ticket indicates that the UI build was not updated along with the python backend. I'm not sure how SM handles installation, so it's not immediately clear how this happened. We had a number of reports with the same error, but AFAIK they were all from installs via SM.

I believe wiping out the invokeai pip package and reinstalling it should fix the issue, as @chozabu noted. Hope this helps. Please @ me if there's anything you need to help get InvokeAI installing via SM.

**Comment by centomila** [comment]
I solved with a new installation too. 🥳

My standalone invokeai was working fine (3.4.0rc2), so i tought was a Stability Matrix problem with models or permissions.

Thanks to all InvokeAI and Stabilty Matrix contributors 💖

**Comment by chozabu** [comment]
> @ionite34 Hi, InvokeAI contributor here, wanted to add some detail which may be helpful.
> 
> We unintentionally had an RC release get marked as a stable release (3.4.xyz). This has been rectified. The current stable release is 3.3.0.
> 
> The error in this ticket indicates that the UI build was not changed, but the backend was updated to this RC release. I'm not sure how SM handles installation, so it's not immediately clear how this happened. We had a number of reports with the same error, but AFAIK they were all from installs via SM.
> 
> I believe wiping out the invokeai pip package and reinstalling it should fix the issue, as @chozabu noted. This works because the latest version is now the stable 3.3.0 version.

Thanks for the info, always nice to catch more of these details!

marking as closed
