### ISSUE TITLE
SD.Next on detected AMD cards on Windows.

### ISSUE THREAD

**Issue by brknsoul** [LykosAI/StabilityMatrix#24]
`--use-directml` should be a listed (and, by default, enabled) option on AMD cards in Windows for SD.Next.

**Comment by oh-pi** [comment]
AIso pulling [This](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#windows) instead for standard automatic1111 when amd is detected in windows install
