### ISSUE TITLE
UI Constantly Visually Glitching

### ISSUE THREAD

**Issue by Vesperindustrial** [LykosAI/StabilityMatrix#249]
The UI constantly flickers with visual glitching in random parts of the window regardless of the size of the window and regardless of which section and happens whether or not the window is in focus or even being moused over. This only happens with the Stability Matrix window and no other on my computer. It is too quick of a flicker to capture in a screenshot. The actual software is perfectly usable  even while its ongoing however.

**Comment by centomila** [comment]
I've had a simlar problem with another app based on Avalonia for the UI libraries and I solved disabling G-Sync. It's a long shot, but worth a try.

**Comment by Vesperindustrial** [comment]
Thanks for the idea, but unfortunately I don't have a gsync display actually

**Comment by ionite34** [comment]
Aware of this issue currently, though not really sure what it's caused by. Might be some upstream issue with https://github.com/AvaloniaUI/Avalonia but will have to experiment more to narrow it down.

**Comment by ionite34** [comment]
Seems to be caused by https://github.com/AvaloniaUI/Avalonia/issues/10306 which may be fixed by a SkiaSharp 3 when they update

**Comment by ionite34** [comment]
From v2.7.0 onwards we added the `--opengl` launch argument to optionally use OpenGL instead of the WinUI composition renderer, you can try to see if it eliminates the artifacts but some menu transparency may not work in that mode.

**Comment by pagurobt** [comment]
> From v2.7.0 onwards we added the `--opengl` launch argument to optionally use OpenGL instead of the WinUI composition renderer, you can try to see if it eliminates the artifacts but some menu transparency may not work in that mode.

Hi, im having glitches in the app UI too, where can i put this line to try to solve it? ty
