### ISSUE TITLE
How can I change Python version?

### ISSUE THREAD

**Issue by GalenMarek14** [LykosAI/StabilityMatrix#251]
A1111 says it needs Python 3.10.6 and not above but Stability uses 3.10.11. I tried installing just A111 alone but couldn't solve some errors, while Stability lets me install it, other errors show up. I don't know if it's related to the Python version but want to try it anyway. How can I make Stability use 3.10.6 instead?
![image](https://github.com/LykosAI/StabilityMatrix/assets/148660654/1d3b4277-e58c-47cb-8c08-dd4a7594fafd)

**Comment by davecazz** [comment]
This is critical actually, with 8GB of VRAM. python 3.10.11 takes about 30 minutes to generate an image with SDXL and --midvramsdxl enabled. while 3.10.6 on the same computer takes 10 seconds. 

it would be great if there was a way to replace the python310 folder with a different version even if its not built into the app.
