### ISSUE TITLE
AggregateException when downloading certain models

### ISSUE THREAD

**Issue by GatesDA** [LykosAI/StabilityMatrix#254]
![Screenshot 2023-11-13 041210](https://github.com/LykosAI/StabilityMatrix/assets/144708/76c5ca2f-273d-426d-a8e8-9098127fb0ca)

I've tried resetting the checkpoint cache, deleting StabilityMatrix.db, clearing the the InstalledModelHashes list in settings.json, and rebooting (all at the same time).

The previous version of ProtoVision XL downloads properly, and I get the same error with the 1.5 and XL versions of Faetastic.  I was getting the same error with AlbedoBase XL, but it updated to 1.2 and now I can download both the new version and the old 1.1 model I couldn't download before.

The model, .json, and thumbnail files briefly appear in Models/StableDiffusion when I try to download.

**Comment by CRCODE22** [comment]
Same here download does not work keeps failing.

**Comment by Doomed1986** [comment]
I have had this error before and im experiencing it again now, annoying as you've chosen a specific model you want and cant get it due to this error.  Suppose could just download the .chpt from the civit webiste, but then it wont have the thumbnail or settings file would it.
