### ISSUE TITLE
Support subdirectories for TI embeds in "Checkpoints" view

### ISSUE THREAD

**Issue by CHollman82** [LykosAI/StabilityMatrix#26]
When manually sorting TI embeds into subdirectories (which is supported by A1111) all but those remaining in the root directory disappear from the list in "Checkpoints"

Bonus: Allow creating new subdirectories and moving embeds/etc into them in the GUI.

![image](https://github.com/LykosAI/StabilityMatrix/assets/3136566/d0c593d7-eae5-4ba2-8954-55744d4731f9)

**Comment by ionite34** [comment]
Ability to create folders and move between folders is still WIP, but now the browser will display existing nested folders in https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.2.0, and you can drag onto an inner folder to import there :)

<img width="770" alt="checkpoint_folder_nesting" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/8e2e92fc-399b-4878-902d-79657d03800b">

**Comment by CHollman82** [comment]
Excellent work, thank you!
