### ISSUE TITLE
Comfy Manager  

### ISSUE THREAD

**Issue by jlitz** [LykosAI/StabilityMatrix#261]
Is there a way of installing the Comfy Manager?

**Comment by halr9000** [comment]
I'm sure that you can install it manually by working with the underlying filesystem. But you break it you bought it :D 

location: StabilityMatrix\Packages\ComfyUI

steps: https://github.com/ltdrdata/ComfyUI-Manager#installationmethod1-general-installation-method-comfyui-manager-only

brb am breaking it

**Comment by halr9000** [comment]
so far so good

![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/dd721b47-4150-46ea-8f2d-86c33bf894f1)

![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/2afac23a-d7eb-4910-8969-2cef9e37552c)

**Comment by TomLucidor** [comment]
Checking from this as well (ZIP file into the relative folder) but maybe it is a registration issue? https://github.com/LykosAI/StabilityMatrix/issues/152

**Comment by ionite34** [comment]
Implemented with extensions management in newer versions: https://github.com/LykosAI/StabilityMatrix/releases
