### ISSUE TITLE
Kohya_ss - Tcl wasn't installed properly

### ISSUE THREAD

**Issue by joli-coeur50** [LykosAI/StabilityMatrix#264]
I have had this problem on kohya for a few days,
when I click on a folder to select my checkpoint or my images, I have this message that appears. 

Can't find a usable init;tcl in the following directories : (...)
This probably means that Tcl wasn't installed properly

I'm on Linux Ubuntu, I've already tried on Linux Mint and Cinnamon, I have exactly the same problem...
I tried installing Tcl via the pip command, installing old versions of kohya, and many other things but nothing changes... it was working fine a few days ago, I don't know why. ..

Thanks for your help !

**Comment by ionite34** [comment]
Could you try `sudo apt-get install python3-tk`?

**Comment by joli-coeur50** [comment]
> Could you try `sudo apt-get install python3-tk`?

I think it's not yet operational for Linux...
Now I have the same error as this post:
https://github.com/LykosAI/StabilityMatrix/issues/276

waiting for an update...

also I don't know if insightface will be included

**Comment by joli-coeur50** [comment]
2.7.3 version is it Ok for install but I still have the same error with Tcl...

**Comment by OneHandead** [comment]
How you get the 2.7.3 version? i only can download 2.6.3, where is it?

**Comment by joli-coeur50** [comment]
sorry it's an error, it's 2.6.3

**Comment by ionite34** [comment]
Should be fixed since v2.8.1 https://github.com/LykosAI/StabilityMatrix/releases/latest
