### ISSUE TITLE
Add support for ruinedfooocus

### ISSUE THREAD

**Issue by runew0lf** [LykosAI/StabilityMatrix#265]
https://github.com/runew0lf/RuinedFooocus

**Comment by drdancm** [comment]
How is is this different from Fooocus ? or Fooocus-ControlNet ?

**Comment by runew0lf** [comment]
> How is is this different from Fooocus ? or Fooocus-ControlNet ?

If only there was a readme and changelog included in the repo...

**Comment by halr9000** [comment]
I'm helping https://github.com/runew0lf/RuinedFooocus#ruined-edition-features

**Comment by runew0lf** [comment]
> I'm helping https://github.com/runew0lf/RuinedFooocus#ruined-edition-features

but how is it different!! :D

**Comment by halr9000** [comment]
> > I'm helping https://github.com/runew0lf/RuinedFooocus#ruined-edition-features
> 
> but how is it different!! :D

🤷‍♂️

**Comment by mohnjiles** [comment]
This was added in v2.7.0. Thanks everyone!
