### ISSUE TITLE
add support for **CushyStudio**

### ISSUE THREAD

**Issue by rvion** [LykosAI/StabilityMatrix#266]
https://github.com/rvion/CushyStudio#readme

Cushy Studio is free and open source cross-platform application allowing you to **Discover**, **Run**, **Create** and **Share** Generative workflows called **Apps**. It offers a complete suit of tools allowing you explore all of what generative art has to offer, have fun, or automate your work. It builds uppon proven technologies like `ComfyUI`, `Stable Diffusion`, `ffmpeg`, `imagemagik`, and many more. It features a professional UI with dockable panes, tabs, and a power-user tools to be efficient

https://github.com/rvion/CushyStudio/assets/2150990/776b00f5-687e-4043-8dac-34dfe7bd2184

This project is already available, but I haven't yet posted much around. The release is very soon

some screenshots:

![](/rvion/CushyStudio/raw/master/docs/static/img/screenshots/2023-11-14-22-33-15.png)

![](/rvion/CushyStudio/raw/master/docs/static/img/screenshots/2023-11-15-00-16-10.png)

![](/rvion/CushyStudio/raw/master/docs/static/img/screenshots/2023-11-15-00-41-10.png)

---------

next version is coming in a few days, and features A LOT OF NEW STUFF AND QOL. 
I really think CushyStudio will soon become the main StableDiffusion frontend around the community.

sneak peak of next version:

https://github.com/LykosAI/StabilityMatrix/assets/2150990/a6725378-2d95-4599-b50c-de0a0faa6451

**Comment by rvion** [comment]
CushyStudio install with `git`, and only requires `node` `npm` to finish setup after cloning

**Comment by drdancm** [comment]
Looks really interesting.

**Comment by rvion** [comment]
This project has continuously worked on and is now closer to its first 1.0 release, I'll update the thread soon with a summary of what changed with the last 4000+ commits 😄 the future of AI playground is coming fast :)

**Comment by drdancm** [comment]
Is there a youtube video showing how it works?
