### ISSUE TITLE
Model Browser should allow blank search to show everything

### ISSUE THREAD

**Issue by CHollman82** [LykosAI/StabilityMatrix#27]
If I just want to browse what is available I expect that searching without entering a search term will list everything that matches the Model Type filter, why doesn't it?

**Comment by mohnjiles** [comment]
This is fixed in [v1.2.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.2.0) :)

Thanks for your feedback!

**Comment by CHollman82** [comment]
No, thank you! (and I'm sorry if the "why doesn't it?" sounded rude, I'm just autistic)
