### ISSUE TITLE
Sampler is unselected after switching tabs (LCM)

### ISSUE THREAD

**Issue by halr9000** [LykosAI/StabilityMatrix#272]
Sampler is going away after generation, preventing a subsequent job with the error "Sampler not selected". As you see top left, nothing's chosen. Just figured out repro. It may have something to do with the lcm sampler somehow? I know it's brand new, maybe comfyanonymous did something weird with it. Steps:

1. Choose model and all other minimum required settings to generate an image.
2. Set sampler to lcm
3. Generate an image
4. Go to Launch (to view console)
5. Go back to Inference, and sampler will be empty.
6. Choose any other sampler, generate image.
7. Go to Launch and back to Inference. Sampler will remain as it was.

![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/eda0a61d-ff18-4049-b267-039968669b9c)

**Comment by ionite34** [comment]
Should be resolved in newer versions: https://github.com/LykosAI/StabilityMatrix/releases
