### ISSUE TITLE
Cannot install on Ubuntu 22.04

### ISSUE THREAD

**Issue by OneHandead** [LykosAI/StabilityMatrix#276]
Hello, Im trying to install StableDiffusion A1111 on Ubuntu but when the download starts, this error happens, I tried to delete the folders and files created, but the error keep going
![image](https://github.com/LykosAI/StabilityMatrix/assets/151743187/917ad169-0f5c-4eae-a764-c847b0911502)

**Comment by joli-coeur50** [comment]
I have exactly the same error

**Comment by joli-coeur50** [comment]
Hello,
no i'm sorry it's exactly same, it working only if i drop kohya, but not if
i import it

16:46:48-777511 INFO     headless: False

16:46:48-780134 INFO     Load CSS...

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py",
line 439, in run_predict
    output = await app.get_blocks().process_api(
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py",
line 1384, in process_api
    result = await self.call_function(
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py",
line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py",
line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 877, in run_sync_in_worker_thread
    return await future
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 807, in run
    result = context.run(func, *args)
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py",
line 700, in wrapper
    response = f(*args, **kwargs)
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/library/common_gui.py",
line 244, in get_folder_path
    root = Tk()
  File
"/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Assets/Python310/lib/python3.10/tkinter/__init__.py",
line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive,
wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following
directories:
    /tools/deps/lib/tcl8.6
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/lib/tcl8.6
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/lib/tcl8.6
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/venv/library
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/library
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/kohya_ss/tcl8.6.12/library
/home/antoine/Bureau/StabilityMatrix-linux-x64/Data/Packages/tcl8.6.12/library



This probably means that Tcl wasn't installed properly.
