### ISSUE TITLE
Controlnet yaml files?

### ISSUE THREAD

**Issue by rexelbartolome** [LykosAI/StabilityMatrix#278]
Not entirely sure how StabilityMatrix handles the models for Controlnet but do I need to move the yaml files to StabilityMatrix's Controlnet models folder? Like do I drag and drop them here? Thanks

![image](https://github.com/LykosAI/StabilityMatrix/assets/88552647/64cb3b4c-2bdc-43b4-ac9f-27be7399053a)

**Comment by fmatulic** [comment]
Also wondering how to add all [the standard ControlNet models](https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main) without breaking the Matrix. I searched in the model browser but there are only 3 models there, which aren't suitable for typical preprocessors like Canny, OpenPose etc.

**Comment by mohnjiles** [comment]
As of v2.7.0 or later, you should be able to download these on the Model Browser tab under the "Hugging Face" section, and they'll get linked to the right place. Note that if you are using InvokeAI, you'll need to use the ones marked `ControlNet (Diffusers)`.
