### ISSUE TITLE
ComfyUI > Settings --cpu gets duplicated on settings save

### ISSUE THREAD

**Issue by demoran23** [LykosAI/StabilityMatrix#28]
To replicate, clear the LaunchArgs in settings.json for ComfyUI, open the settings, save it, and note that there are two instances of "--cpu".

Attempting to open the settings afterwards will cause the app to crash, due to the key being present in the Dictionary already.

**Comment by Zuzakiin** [comment]
I had same problem. Thank you for pointing out that it is within the settings.json in dat folder.
Temp fix is to manually delete the first cpu { } code bits. (the last one in the list would require comma deletion too.)
confirmed works now.

**Comment by ionite34** [comment]
Fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v1.2.0 with removed duplicate `--cpu` option in the VRAM card
