### ISSUE TITLE
Adding a description for LoRA describing the 'trigger words'

### ISSUE THREAD

**Issue by SoulxSlayer** [LykosAI/StabilityMatrix#282]
In the Checkpoints section, I think it would be amazing to have a small section where the 'trigger words' are given, which can be retrieved from CivitAI . In the current JSON, there isn't any information for that, so I'm not sure if the API by CivitAI returns that, but if it's possible, that would truly make the workflows efficient, as checking for trigger words everytime is a little painful (although it's great that StabilityMatrix provides a link to the CivitAI page).

![image](https://github.com/LykosAI/StabilityMatrix/assets/43785565/74e8acf2-b497-4ac7-b85f-99d6181378fb)

**Comment by ionite34** [comment]
Added since v2.7.0-dev.3, should have release soon
