### ISSUE TITLE
Installing for rocm on a system where no NVIDIA gpu is discovered but AMD is discovered always installs CUDA

### ISSUE THREAD

**Issue by jrmoserbaltimore** [LykosAI/StabilityMatrix#307]
Stability Matrix has a setting for preferred pytorch backend.  No matter what is selected for ComfyUI, AIII, or others, it always installs the nvidia CUDA version.  When explicitly selecting rocm, it installs CUDA.  There is a lot of code to detect AMD && !NVIDIA and install rocm, but none of that seems to do anything in 2.6.7 at least.

**Comment by XANi** [comment]
Similar problem, after installing any package with ROCM version of PyTorch selected I get message about NVIDIA driver not installed. 

the AMD card shows up in settings, `rocminfo` also returns the card

version 2.11.4

**Comment by lordkitsuna** [comment]
Having this same issue, best i can get out of any interface is cpu generation. Can't get anything to actually use my 6800xt

**Comment by SpoiledCoding** [comment]
I have this same issue. Only way I can use Comfy is if I manually uninstall the pytorch packages and reinstall the ones for rocm. :/

**Comment by Juanpintoselso33** [comment]
same issue here

**Comment by XANi** [comment]
despise deep developer wishes, bug do not disappear when you stop looking at them. Go away @github-actions bot
