### ISSUE TITLE
How do you configure commandline arguments for AUTOMATIC 1111?

### ISSUE THREAD

**Issue by Totoro51212** [LykosAI/StabilityMatrix#312]
Hello, I use automatic1111 within StabilityMatrix, and I've tried using configuring the launch options for automatic1111 within the menu. It doesn't accept the arguments that would normally go into webui-user.bat in the standalone automatic1111, but all the arguments that are in the launch options seem to be the same as the ones in the commandline arguments list. Additionally, is a process to install the cudnn files for kohya_ss?

**Comment by ionite34** [comment]
What arguments do you need to set? If they are not already a preset option you can enter it as a custom argument if you scroll to the bottom.
