### ISSUE TITLE
Bug? - Going to Settings, than press Back on Mouse

### ISSUE THREAD

**Issue by Manniala** [LykosAI/StabilityMatrix#326]
This is more a cosmetic thing, but still think i need to report it.

v2.7.0.0 - StabilityMatrix

If you go to settings, and than press (think button 5) on mouse, like you would in a browser, the setting page closes, and you go back to the page you were before, but you can no longer press the Settings button, it still stands as active.

To get around this,m you have to press one of the other options on the left menu (icons), before you again can go into Settings.

![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/d12aa16e-302b-4b81-b474-61edf0c8db92)

What i thought would had happen, was it went back to Settings from Interface, (Settings > Interface) and not back to Model Browser, Package...

**Comment by ionite34** [comment]
So we haven't actually implemented the back button states yet, didn't realize the functionality was implicitly enabled with mouse 5. Will take a look to see if we can fix it.
