### ISSUE TITLE
[ComfyUI] new Hugging Interface and IPAdapter issues

### ISSUE THREAD

**Issue by DarKDinDoN** [LykosAI/StabilityMatrix#327]
Hello,

Thanks for the new HuggingFace download feature.

Two things related to this feature:
- It is not possible to download both "CLIP VISION (Diffusers)" models. Since both have the same folder name and file name, one will overwrite the other.
- It would be nice if ComfyUI's folder configuration could be updated with these two folders ("clip_vision" and "ipadapter"). For the moment, the program still expects to find the files in the "ComfyUI" package and not the global "Models" folder in StabilityMatrix.
- (optional) find a solution for long folder names. Once in ComfyUI, long folder/files names prevent nodes from being clearly visible. I could rename them manually, but I don't know if this will be a problem later on, when the models are updated.

**Comment by ionite34** [comment]
Should be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.3
