### ISSUE TITLE
[ComfyUI] invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

### ISSUE THREAD

**Issue by Ryder17z** [LykosAI/StabilityMatrix#329]
```
ERROR:root:Failed to validate prompt for output 9:
ERROR:root:* CheckpointLoaderSimple 4:
ERROR:root:  - Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in []
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
got prompt
ERROR:root:Failed to validate prompt for output 9:
ERROR:root:* CheckpointLoaderSimple 4:
ERROR:root:  - Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in []
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

I just installed ComfyUI normally so i'm not sure why this happened. I tried to run the default prompt and no settings have been changed.

**Comment by ionite34** [comment]
Seems comfy is not finding any models, could you double check the shared model folder setting for the comfyui package you're using? If using the default config mode, on startup it should show the model paths being added in the console like:
```
Adding extra search path checkpoints C:\...\Matrix\Data\Models\StableDiffusion
Adding extra search path vae L:\Image ML\Matrix\Data\Models\VAE
Adding extra search path loras L:\Image ML\Matrix\Data\Models\Lora
```

**Comment by Ryder17z** [comment]
To me it looks like it's assuming that XYZ is there, which seems weird.
If it had stated a more generic "no models found" or etc then this issue wouldn't be posted.

**Comment by ionite34** [comment]
Were you able to get the models discovered by ComfyUI afterwards, or is the missing models still an issue?

**Comment by Ryder17z** [comment]
They were found after being imported when running VoltaML instead. Which isn't ideal but it's now usable.
