### ISSUE TITLE
Comfy > After updating, unable to start.  Directory not empty.

### ISSUE THREAD

**Issue by demoran23** [LykosAI/StabilityMatrix#33]
I get a directory not empty error when trying to start the Comfy.  This will happen for a number of directories, and is caused due to the empty "put x here" files.

**Comment by ionite34** [comment]
Hm.. so it makes new junctions from the models directory on launch in case paths were moved (portable mode and what not). You can try deleting all the checkpoint folders in ComfyUI for now, but I'll add an update for detecting existing files and moving them into the shared folder before deleting.

**Comment by demoran23** [comment]
Just keep in mind that the moved files may already exist in the destination directory, as well (after a couple of iterations).

**Comment by Touitoui** [comment]
Issue was caused by placeholder files "put_XXX_here", downloaded with the recent update. 
Search and delete every `put_*` files inside X:\StabilityMatrix_data\Packages\ComfyUI\models and it will work again.

**Comment by demoran23** [comment]
Comfy has a file called Packages\ComfyUI\extra_model_paths.yaml.example, which is a template for the non-.example file used to provide overrides for where to find the models.

Generating this file instead of updating junctions is probably a better way to handle this kind of redirection.
