### ISSUE TITLE
[comfyui] BatchCreativeInterpolation

### ISSUE THREAD

**Issue by WeirdScienceX** [LykosAI/StabilityMatrix#332]
Trying out a new node https://github.com/banodoco/Steerable-Motion, and I encountered the following error, everything is up-to-date.  I downloaded and tried with a standalone comfyui, which works fine.

> Error occurred when executing BatchCreativeInterpolation:
> 
> Can't find a usable init.tcl in the following directories: 
>     C:/AI/StabilityMatrix/Assets/lib/tcl8.6 C:/AI/StabilityMatrix/Packages/ComfyUI/venv/lib/tcl8.6 C:/AI/StabilityMatrix/Packages/ComfyUI/lib/tcl8.6 C:/AI/StabilityMatrix/Packages/ComfyUI/venv/library C:/AI/StabilityMatrix/Packages/ComfyUI/library C:/AI/StabilityMatrix/Packages/ComfyUI/tcl8.6.12/library C:/AI/StabilityMatrix/Packages/tcl8.6.12/library
> 
> 
> 
> This probably means that Tcl wasn't installed properly.
> 
> 
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\steerable-motion\SteerableMotion.py", line 361, in combined_function
>     comparison_diagram, = plot_weight_comparison(cn_frame_numbers, cn_weights, ipadapter_frame_numbers, ipadapter_weights, buffer)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\steerable-motion\SteerableMotion.py", line 209, in plot_weight_comparison
>     plt.figure(figsize=(12, 8))
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
>     manager = new_figure_manager(
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\pyplot.py", line 465, in new_figure_manager
>     return _get_backend_mod().new_figure_manager(*args, **kwargs)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 3402, in new_figure_manager
>     return cls.new_figure_manager_given_figure(num, fig)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 3407, in new_figure_manager_given_figure
>     return cls.FigureCanvas.new_manager(figure, num)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backend_bases.py", line 1785, in new_manager
>     return cls.manager_class.create_with_canvas(cls, figure, num)
>   File "C:\AI\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 486, in create_with_canvas
>     window = tk.Tk(className="matplotlib")
>   File "C:\AI\StabilityMatrix\Assets\Python310\tkinter\__init__.py", line 2299, in __init__
>     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
>

**Comment by vlsech** [comment]
i have the exact same issue

**Comment by Kryptonic83** [comment]
same problem
