### ISSUE TITLE
Symlink mode bug.

### ISSUE THREAD

**Issue by solomon-s2020** [LykosAI/StabilityMatrix#338]
Packages\ComfyUI\models\controlnet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet\ControlNet  ........

When using Symlink Mode, create many ControlNet directories.

**Comment by ionite34** [comment]
Hm couldn't seem to replicate this with Comfy in symlink mode. Could you check `Data/Models/ControlNet` and see if there's a `ControlNet` junction inside referencing itself? If so remove the duplicate folder and try launching again. Then check the `Data/Models/ControlNet` folder to see if there are still any duplicate links created.

**Comment by solomon-s2020** [comment]
> Hm couldn't seem to replicate this with Comfy in symlink mode. Could you check `Data/Models/ControlNet` and see if there's a `ControlNet` junction inside referencing itself? If so remove the duplicate folder and try launching again. Then check the `Data/Models/ControlNet` folder to see if there are still any duplicate links created.

Yes, `Data/Models/ControlNet` same many ControlNet directories.   It's really strange that all the original safetensors files have disappeared.

**Comment by KINGLIFER** [comment]
Same for ipadapter 
data_path:  D:\Ai\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
[comfy_mtb] | ERROR -> Error during font caching: [WinError 1921] The name of the file cannot be resolved by the system: 'D:\\Ai\\Data\\Packages\\ComfyUI\\models\\ipadapter\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base\\base'

**Comment by KINGLIFER** [comment]
You guys also broke ComfyUI_IPAdapter_plus[ 🔗](https://github.com/cubiq/ComfyUI_IPAdapter_plus)
And your Discord needs someone to run it at least half properly. Got kids in there saying things isnt broken when it is. Just foolishness.

**Comment by KINGLIFER** [comment]
Is anyone going to even respond?

**Comment by ionite34** [comment]
Should be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.4
