### ISSUE TITLE
Clicking on Launch from the Packages pane does not launch the package

### ISSUE THREAD

**Issue by demoran23** [LykosAI/StabilityMatrix#34]
It only brings you to the launch pane.  It doesn't update the dropdown to the package in question, either.

Rather than having to click twice, launching from the packages pane should simply launch the package.

**Comment by ionite34** [comment]
Added in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.0.0 with https://github.com/LykosAI/StabilityMatrix/commit/de59a796f7dcd0d8e45e3b968a3061b1252de145
- Launch button should now both redirect to launch page and launch the package
