### ISSUE TITLE
Dubious Ownership

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#343]
I'm afraid I've had this issue in the past and somehow fixed it, but it's is back again.
I can't run any succesful extension updating scans

fatal: detected dubious ownership in repository at 'D:/STABLEDIFF/Data/Packages/stable-diffusion-webui'
'D:/STABLEDIFF/Data/Packages/stable-diffusion-webui' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-3275201317-2648292050-3080710396-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory D:/STABLEDIFF/Data/Packages/stable-diffusion-webui
fatal: detected dubious ownership in repository at 'D:/STABLEDIFF/Data/Packages/stable-diffusion-webui'
'D:/STABLEDIFF/Data/Packages/stable-diffusion-webui' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-3275201317-2648292050-3080710396-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory D:/STABLEDIFF/Data/Packages/stable-diffusion-webui
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0
Commit hash: <none>

When I use CMD to get to here:

D:/STABLEDIFF/Data/Packages/stable-diffusion-webui
I cannot run git, nor python

If I then go to:
D:/STABLEDIFF/Data/Packages/stable-diffusion-webui\venv

I still can't run the necessary command given during loading.  I'm sure it has to do with the portability.
Can someone please tell me how to get to where I can run git? I'm sure it's super simple to anyone who understands how things work.

Thanks

**Comment by an90ray** [comment]
try this. it will rewrite ownership
takeown /F C:\Username\sd.webui /R /D Y
icacls D:\Username\sd.webui /setowner "PC-name\Username" /T /C

**Comment by drdancm** [comment]
Thanks to an90ray for the help. 
I was able to solve the problem a different way.
Searched for git.exe and found the folder  PortableGit, I got into that folder and then I simply ran the command suggested in the error message and the problem was solved.

**Comment by rajivkumarprajapati123** [comment]
Just run the STABLE MATRIX as administrator.
