### ISSUE TITLE
How do I launch multiple apps?

### ISSUE THREAD

**Issue by nothingness6** [LykosAI/StabilityMatrix#360]
I installed Stable Diffusion WebUI, ComfyUI and Fooocus-ControlNet. When I tried to launch them at once, StabilityMatrix didn't let me do it. I have to stop one to launch another one. 
Is there an option for that? Or does StabilityMatrix not support it for now?

**Comment by johnwickstyle** [comment]
yo can only use one at a time. if you want to use MultiApp, then open menually
For example:
C:\StabilityMatrix-win-x64\Data\Packages\(choose your App)\Go to .bat file to open it.

**Comment by nothingness6** [comment]
> yo can only use one at a time. if you want to use MultiApp, then open menually For example: C:\StabilityMatrix-win-x64\Data\Packages(choose your App)\Go to .bat file to open it.

Thanks for the reply, but I found out that only Stable Diffusion has .bat file and rest of them have an only bunch of .py files.

**Comment by johnwickstyle** [comment]
> > yo can only use one at a time. if you want to use MultiApp, then open menually For example: C:\StabilityMatrix-win-x64\Data\Packages(choose your App)\Go to .bat file to open it.
> 
> Thanks for the reply, but I found out that only Stable Diffusion has .bat file and rest of them have an only bunch of .py files.

you can use https://github.com/comfyanonymous/ComfyUI/releases portable version if you want bat file for it.

**Comment by JarekDerp** [comment]
you can run Comfy using a bat file (it can be saved even on your desktop) if you write it like this:
```
cd C:\StabilityMatrix-win-x64\Data\Packages\ComfyUI
.\venv\Scripts\python.exe main.py --preview-method taesd --dont-upcast-attention --directml
```

The first line is a path to where you keep you ComfyUI installation inside Stability Matrix, and the second line contains all the run parameters you usually use with Stability Matix.
I think it might work the same for other launchers, you'd just have to modify the path (line 1) and main python script (line 2, the "main.py" part).
Using this script you can start ComfyUI even without starting up Stability Matrix.

**Comment by ionite34** [comment]
It's not supported in the single app instance for now, but we're planning on it.

Currently you can either launch multiple instances of Stability Matrix (which isn't technically supported as there may be issues in synchronizing settings between the instances) or you can manually invoke the entry points using the venvs we create. All packages will have a venv named `venv` in the package directory.

Some package provided `.bat` files may not work as expected if they use a global system python.

**Comment by nothingness6** [comment]
> It's not supported in the single app instance for now, but we're planning on being able to launch and manage multiple packages at the same time.
> 
> Currently you can either launch multiple instances of Stability Matrix (which isn't technically supported as there may be issues in synchronizing settings between the instances) or you can manually invoke the entry points using the venvs we create. All packages will have a venv named `venv` in the package directory.
> 
> Some package provided `.bat` files may not work as expected if they use a global system python.

Great news! I'll be looking forward to it. 
Btw, do you also have a plan adding the audio things such as Bark, Coqui or any other AI audio apps? It will be one stop AI apps solution then!
Thank you.
