### ISSUE TITLE
Explain the behavior of Settings/System/Select new Data Directory...

### ISSUE THREAD

**Issue by lednevandrey04** [LykosAI/StabilityMatrix#362]
I have two interfaces installed in the D:\StabilityMatrix\ directory: Stable Diffusion WebUI and ComfyUI. I want to use the downloaded models for both interfaces. And I want to store these models on another drive, for example F:\Data. From the Settings/System/Selec new Data Directory item in the StabilityMatrix application, it is clear that in this new directory F:\Data, data for the loaded models should be stored. But first, I installed the Stable Diffusion WebUI interface as a separate application. And I downloaded all the models for this interface, including the ControlNet module, before installing StabilityMatrix on the computer. Now I specified that the new data directory would be F:\Data, but now this folder is empty. And when I launch the ComfyUI interface and try to select a model, I get the message “undefined”. What folders should I move to the F:\Data folder?

In addition, in the D:\StabilityMatrix\ folder there is a \Models folder. How is this folder related to this question

**Comment by johnwickstyle** [comment]
make a shortcut of your   F:\Data in any folder then cut and paste all shortcut in to your stable Stable Diffusion Model folder.
Hope that's work.
