### ISSUE TITLE
Support fastsdcpu UI, a UI optimized to run Stable Diffusion on CPU

### ISSUE THREAD

**Issue by lrq3000** [LykosAI/StabilityMatrix#364]
FastSD CPU is a faster version of Stable Diffusion on CPU. Based on [Latent Consistency Models](https://github.com/luosiallen/latent-consistency-model).

It now supports SD-Turbo and SDXL-Turbo, and both txt2img and img2img.

The project lives at: https://github.com/rupeshs/fastsdcpu

Disclaimer: I am not the author, I am just a regular user since a few months. I use it on Windows 11, and it is very easy to install and use, and it is indeed very fast despite running only on CPU.

**Comment by rupeshs** [comment]
Thank you @lrq3000 for mentioning FastSD CPU.
