### ISSUE TITLE
Restart required when changing wildcard files for Dynamic Prompts extension

### ISSUE THREAD

**Issue by CHollman82** [LykosAI/StabilityMatrix#37]
First I want to say thank you so much for all the work you guys did on the last release, it fixed some very important issues and now I use StabilityMatrix exclusively and have abandoned my old installation of SD.

This is minor and involves an extension so not a huge priority I'm sure but I just thought I'd mention it. I used to be able to create/modify wildcard files (plaintext files) and use them with the Dynamic Prompts extension*  without restarting SD and when using StabilityMatrix this does not work, you have to click "Stop" and then "Launch" to restart SD, then it works.

*https://github.com/adieyal/sd-dynamic-prompts

**Comment by demoran23** [comment]
In the Wildcard Manager tab, hit Refresh Wildcards.
![image](https://github.com/LykosAI/StabilityMatrix/assets/6959036/a99f93cc-3e41-43a8-990b-4fb35a5e589a)

**Comment by CHollman82** [comment]
This works, thank you!
