### ISSUE TITLE
Heads tilted/rotated more than 45 degrees from vertical fail to swap

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#374]
Swapping faces that are tilted more than 45 degrees from the vertical (in the Z plane)  fail to swap. 

I have been able to fix that by simply rotation the image closer to the vertical and then I run Reactor and the swaps work. 

Therefore if Reactor detected the tilt angle, a bit of rotation prior to swapping should do the work. I'm sure this is a common problem and I'm surprised other people have not mentioned it.

Thanks for a great program !

**Comment by ionite34** [comment]
I think this should go in https://github.com/Gourieff/sd-webui-reactor or as a discussion perhaps? Thanks for the appreciation though, glad you like the program!

**Comment by drdancm** [comment]
Oops I meant to write that in Reactor  just as you noted. No wonder I could not find it there !!!
Thanks for letting me know.
