### ISSUE TITLE
Model not loaded -  size mismatch

### ISSUE THREAD

**Issue by lein1013** [LykosAI/StabilityMatrix#375]
I'm trying to get Stability Matrix running, and it seems there is an issue with the parameters of the function call to load the models
```
torch.Size([320, 320])
vs
torch.Size([320, 320, 1, 1])
```

![grafik](https://github.com/LykosAI/StabilityMatrix/assets/72338417/0cfd2926-44bb-4121-aa47-2edfb64933d5)

**Comment by ionite34** [comment]
Seems to be some model compatibility issue? Would recommend asking on the SD.Next GitHub for more information
