### ISSUE TITLE
Request for AMD 7900XTX Graphics Card Compatibility Enhancement in 'stabilityMatrix'

### ISSUE THREAD

**Issue by abassign** [LykosAI/StabilityMatrix#377]
I need to make a request for a change in the code of a program related to "stablediffusion" called "stabilitymatrix." The modification concerns the fact that the Linux version with an AMD 7900XTX graphics card only works when both the "WebUI" and "ComfyUI" packages are launched with the prefix "HSA_OVERRIDE_GFX_VERSION=11.0.0 python launch.py." This prefix is required for Python to recognize that an AMD 7900XTX card is being used. Unfortunately, this modification cannot currently be added to the "settings.json" file as it only expects the "LaunchCommand": "xyz.py" tag for the Python program to run, but not the full prefix to be used with the Python command. It would be very helpful for those with an AMD 7900XTX to have this option so that the ROCm-related system can identify the type of processor to use and avoid the error (139) that typically occurs in this case. I hope you can make this modification so that I can use your program fully, even with my graphics card.

**Comment by schmedes2** [comment]
I made a launch.sh file to use as the target and it launched fine but it didn't seem to make any difference. You might have better luck:

cd into the comfyui folder
sudo nano launch.sh
copy and paste below
close and save

replace main.py in the json with launch.sh

#!/bin/sh

export HSA_OVERRIDE_GFX_VERSION=11.0.0
export HIP_VISIBLE_DEVICES=0
export PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:512

python3 main.py

**Comment by mohnjiles** [comment]
Hi there, you should be able to add these to the Environment Variables section in the Settings tab of SM, then they should be picked up by the UIs.

![image](https://github.com/LykosAI/StabilityMatrix/assets/33761/69122bed-a3ad-4a11-a123-d27b626a5842)

**Comment by iHad168** [comment]
Please add `export HSA_OVERRIDE_GFX_VERSION=11.0.0` to default
I found it very well to successfully operate Stabilitymatrix

https://github.com/ROCm/ROCm/issues/2536
