### ISSUE TITLE
Console should be interactive

### ISSUE THREAD

**Issue by demoran23** [LykosAI/StabilityMatrix#38]
I ran into an issue where I couldn't update SD.Next because I'd changed a file that was under source control and it was like "Boy you better stash that before you ask me to pull".

Anyway, I ended up updating SD.Next manually, but when I started it up via Stability Matrix it just kind of hung there.

When I started it via the command line, I saw I was being prompted to download the default model (probably SDXL .9).

Unfortunately, even after successfully starting the ui via the command line, when I shut that down and tried via SM, it hung in the same place, for the same reason.

I think making the console interactive would not only surface these things, but allow people to deal with them as well.

**Comment by demoran23** [comment]
Also, I think the reason I was unable to update SD.Next was because I'd updated the builtin extensions via the ui, and this caused me to have git submodule differences that show up as unstaged changes.

**Comment by ionite34** [comment]
WIP for v2, adding a dropdown for sending any input to the subprocess:

```python
x = input("Enter input: ")
print(f"Result: {x!r}")
```
<img width="793" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/f747e465-f1cf-46ba-9875-03486dc105a1">

Through a sitecustomize.py audit hook we'll also get notified when `input()` is called for common things like (y/n), and there will be an interactive popup for these:

```python
x = input("Please confirm: (y/n)")

if x.lower() == "y":
    print(f"Result: {x!r} (Yes)")
else:
    print(f"Result: {x!r} (No)")
```
<img width="744" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/caced69c-5ac0-4ab0-b2a2-699be425be38">

(Clicking 'Yes' there, for example would send 'y'):
<img width="777" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/13956642/2204f0c6-40b6-4818-ab77-ab4a7fbc39c1">

**Comment by ionite34** [comment]
Interactive console added in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.0.0 with https://github.com/LykosAI/StabilityMatrix/commit/de59a796f7dcd0d8e45e3b968a3061b1252de145
