### ISSUE TITLE
Contribute German Translation to the program

### ISSUE THREAD

**Issue by mario-dg** [LykosAI/StabilityMatrix#380]
Hey there,

I would like to contribute by translating the project to German via the POEditor :)

**Comment by mohnjiles** [comment]
Hi, thanks for your interest! What email address should we send the invite to? Feel free to DM me or Ionite on Discord if you don't want to share it here on GitHub.

Thanks!

**Comment by mario-dg** [comment]
Sorry, I haven't seen your comment...
But as I've seen, I was already invited, thank you! Will get work pretty soon :)
