### ISSUE TITLE
[Feature Request] SD.Next options: Add --share, --listen, --auth

### ISSUE THREAD

**Issue by brknsoul** [LykosAI/StabilityMatrix#388]
Request addition of `--share`, `-listen`, and `--auth username:password` Under SD.Next launch options.

**Comment by brknsoul** [comment]
EDIT: Looks like someone's PRing it for me, since I couldn't code myself out of a wet paper bag.

**Comment by Aptronymist** [comment]
> EDIT: Looks like someone's PRing it for me, since I couldn't code myself out of a wet paper bag.

I apologize for the noise, I'm coming to understand he was dropped on his head. Repeatedly. I'm handling it.🙄
