### ISSUE TITLE
It is not checked when starting that Confy UI is on another drive.

### ISSUE THREAD

**Issue by Soliver84** [LykosAI/StabilityMatrix#394]
It is not checked when starting that Confy UI is on another drive.

The venv .bat file is not adjusted. In general, all paths must be adjusted when starting or there must be a tab in which you can configure all paths. emphasis on all.
I have 2.8.0 dev v3

Please install this otherwise there will always be chaos

**Comment by ionite34** [comment]
What did you mean by other drive? If you move the data folder we should set all necessary paths on launch. We don't interface or make changes to .bat files and they're not used when launching via Stability Matrix.
