### ISSUE TITLE
start-up screen always showing 

### ISSUE THREAD

**Issue by kosh66** [LykosAI/StabilityMatrix#398]
Not sure if this is an intended feature but on every start up I always get the "Welcome to Stability matrix'; splash screen asking me to install a package. I always press 'skip first-time install' but every time it comes back. I then always have to import my package every time

**Comment by ionite34** [comment]
Which version of Stability Matrix are you using? (Can check in information section at the bottom of Settings page)

**Comment by kosh66** [comment]
2.7.9
