### ISSUE TITLE
[Suggestion] Add ADetailer as an Addon

### ISSUE THREAD

**Issue by Squibeel** [LykosAI/StabilityMatrix#400]
Similar to what was done with Controlnet and FreeU

**Comment by brknsoul** [comment]
ImpactPack is what you're looking for.

**Comment by Squibeel** [comment]
> ImpactPack is what you're looking for.

I meant for the inference module of the stability matrix. Sorry for not explaining properly.

**Comment by lilcdj** [comment]
Is there ADetailer for ComfyUI? Maybe it's not possible because Inference work with ComfyUI. but I agree with Inference need some detailer to fixing face, hand and feet. needs to be modded.

**Comment by brknsoul** [comment]
> Is there ADetailer for ComfyUI? Maybe it's not possible because Inference work with ComfyUI. but I agree with Inference need some detailer to fixing face, hand and feet. needs to be modded.

https://github.com/LykosAI/StabilityMatrix/issues/400#issuecomment-1902314089
