### ISSUE TITLE
AMD Rocm/Ubuntu building my own venv folder results in better performance

### ISSUE THREAD

**Issue by schmedes2** [LykosAI/StabilityMatrix#402]
I was having issues in comfyui where the first run of a model would take a long time to load and things like sd upscale were very slow. If I installed comfy manually, I didn't have the problems and it was very fast but it was much more unstable. After building my own venv folder in packages/comfyui, its been working great

I'm not sure what the difference between the 2 builds entails. It might be that I uninstall torchvision first then reinstall rocm but, again, not really sure

**Comment by ionite34** [comment]
Hm, which pytorch version did you install in your version? And do you have any special env vars set for rocm? If you have more info we can look to improve our rocm install steps
