### ISSUE TITLE
Moving to a new storage

### ISSUE THREAD

**Issue by jippy89** [LykosAI/StabilityMatrix#404]
Are there any specific steps to move one folder to another?
I'm planning to move my folder to a new storage.
It's currently in my device's disk, but I'm thinking of moving it to a portable one.

Do I have to install new again? I forgot whether I installed portable one or not.

Thank you, keep up the good work!

**Comment by ionite34** [comment]
If it's portable there should be a "Data" folder next to the exe, otherwise check the "change data directory" settings card and it should show where the current data folder is. You can move the data folder to a new computer and select it when launching SM for the first time on the new computer.
