### ISSUE TITLE
Portuguese Translation finished

### ISSUE THREAD

**Issue by nextosai** [LykosAI/StabilityMatrix#407]
Hi friends. I have finished the Portuguese Translation of Stability Matrix. Please let me know if you guys have access to the translation in POE or if I need to export the file and send it to you. Thank You.

**Comment by leo0eloi** [comment]
Hello! I install today and I don´t has the file. Can send to me please?

**Comment by nextosai** [comment]
[Resources.pt-PT.zip](https://github.com/LykosAI/StabilityMatrix/files/13973160/Resources.pt-PT.zip)
Unpack the file in /StabilityMatrix.Avalonia/Languages/ 

I believe this file will be available natively in the next updates.

**Comment by mohnjiles** [comment]
Thank you! This should be available starting with v2.8.0 (public release soon™️)
