### ISSUE TITLE
Invoke 3.6 ControlNet Errors

### ISSUE THREAD

**Issue by RadTechDad** [LykosAI/StabilityMatrix#408]
I upgraded to Invoke 3.6 and got a bunch of errors. I then removed it completely and reinstalled. Still getting errors. Not sure if this is a StabilityMatrix issue or an Invoke issue.

Please advise.

![StabilityMatrix_fEpAwv2Bzl](https://github.com/LykosAI/StabilityMatrix/assets/1923370/8d124436-1451-4ea0-851f-a08d1abed71c)

**Comment by mohnjiles** [comment]
Hi, sorry about that, the "normal" ControlNet models aren't compatible with InvokeAI, you'll need to use the ones marked `ControlNets (Diffusers)` on the HuggingFace tab.
<img width="1056" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/33761/288142a4-2691-44a1-ad4e-4813a68efce3">
