### ISSUE TITLE
Running StabilityMatrix.exe with any command line option fails to launch

### ISSUE THREAD

**Issue by brknsoul** [LykosAI/StabilityMatrix#412]
I typically run StabilityMatrix.exe with `--disable-gpu` to prevent hardware acceleration on the user interface. Since the latest update, this (or any command line option) causes SM to fail to start. 

Task Manager shows SM in "Suspended" mode for a couple of seconds before disappearing.

**Comment by mohnjiles** [comment]
Sorry about that, looks like there's a bug when parsing unknown command line arguments. Could you try again with `--disable-gpu-rendering` ?

**Comment by brknsoul** [comment]
Ahh, the commandline option was changed on me! Works now, thanks!
(suggestion: add a `--help` and/or `-h` to list possible SM commands)
