### ISSUE TITLE
(pre3) BUG Report on 2.8.0-pre.3+862951a: Environment variables can no longer be edited

### ISSUE THREAD

**Issue by Soliver84** [LykosAI/StabilityMatrix#413]
Hello

BUG Report on 2.8.0-pre.3+862951a: Environment variables can no longer be edited

Thanks

**Comment by mohnjiles** [comment]
Should be fixed as of [v2.8.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.8.0). Thanks for the report!
