### ISSUE TITLE
StabilityMatrix downgrades Automatic1111 torch version

### ISSUE THREAD

**Issue by Razunter** [LykosAI/StabilityMatrix#415]
For some reason, StabilityMatrix downgrades Automatic1111 torch version on every update. I'm on dev branch of Automatic1111, it warns about outdated torch version. I've tried manually updating with params or via StabilityMatrix UI, but Torch and Xformers get downgraded anyway.

Warning from the log:
```
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.20.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
```

Windows 11
Stability Matrix v2.7.9

Automatic1111:
```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0-408-g94d4b3c8
Commit hash: 94d4b3c8e78df41eea431069475e1d35f75d02ff
```

**Comment by fichl** [comment]
hi, wouldnt it be better to read the actual requirements.txt and requirements_versions.txt instead of hardcoding the version numbers in StabilityMatrix.Core\Models\Packages as different branches have different requirements ?

**Comment by MGMehdi** [comment]
Is it a reason on why some checkpoint (SD 1.5) don't work with A1111 installed via StabilityMatrix but do works on standalone A1111 ?
