### ISSUE TITLE
too big interface size

### ISSUE THREAD

**Issue by eephyne** [LykosAI/StabilityMatrix#42]
I'm using linux on a laptop with a resolution of 2560x1600.

The app is showing way too big compared to others apps

![alt](https://i.ibb.co/xgv3jWz/Capture-d-cran-du-2023-07-25-19-26-06.png)

Is there an option to set this ?

I do not have scaling enabled on my DE

**Comment by ionite34** [comment]
Still trying to see how to get DPI on linux consistently, but for now you can override the scaling calculation with:
1. Get your monitor names with:
```bash
$ xrandr --listactivemonitors
Monitors: 1
 0: +*Display-1 1920/344x1080/194+0+0  Display-1
```

2. Set this environment variable globally or while starting the program to override scaling for a particular named monitor
```bash
AVALONIA_SCREEN_SCALE_FACTORS='Display-1=1;Display-2=1.5'
```

**Comment by eephyne** [comment]
Nice , thanks for the workaround in the meantime :)
