### ISSUE TITLE
Why have a venv if stab matrix won't install python packages to it?

### ISSUE THREAD

**Issue by RangerFrank** [LykosAI/StabilityMatrix#423]
Why have a venv if stab matrix won't install python packages to it?

**Comment by ionite34** [comment]
Our package install process and the python package manager menu should both install into the package's venv. Can you describe what behavior you're observing and what behavior you expect.

**Comment by RangerFrank** [comment]
Dependencies for imported nodes constantly get installed to the standalone
python rather than the venv.

**Comment by ionite34** [comment]
How did you install the imported nodes, is it the builtin extensions manager or ComfyUI manager, if so did you install ComfyUI Manager the normal way or the portable way for embedded python? The latter (portable / embedded) method only works with embedded ComfyUI and not Stability Matrix. Following their normal instructions for git cloning to extra nodes folder should work fine with the venv.

**Comment by RangerFrank** [comment]
All three, standalone, portable and stability matrix. All three run into
issues of not installing packages to the correct python location or venv.
Makes it even more difficult when there's version discrepancies for
dependencies based on which packages are needed for what components.

**Comment by ionite34** [comment]
Could you give a list of steps you took, and what you observed as a result of it not installing into the venv? This shouldn't occur with ComfyUI installs in Stability Matrix.
