### ISSUE TITLE
Linux InvokeAI install throws "Could not find a part of the path" error looking for folder node-v20.11.0-linux-x64

### ISSUE THREAD

**Issue by slogonomo** [LykosAI/StabilityMatrix#429]
It looks like this is caused by pulling node-v20.11.0-linux-x64.tar.xz when the Extract7ZAuto and Extract7ZTar functions only expect a tar.gz, leaving extraction incomplete. 

A quick fix is to change this line to pull the .tar.gz instead of .tar.xz.
https://github.com/LykosAI/StabilityMatrix/blob/f0dfa05d27edbf0b928a796c190695c21b5e0fcc/StabilityMatrix.Avalonia/Helpers/UnixPrerequisiteHelper.cs#L336

Or the helper functions could be changed to support .tar.xz files.

**Comment by ionite34** [comment]
Fixed by #430
