### ISSUE TITLE
Add support for new fork of SD

### ISSUE THREAD

**Issue by netzgiest** [LykosAI/StabilityMatrix#441]
plz add support for new optimized fork of SD - https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by SpanishHearts** [comment]
This is very needed! Can't wait!

**Comment by agarzon** [comment]
very needed!

**Comment by EriIaz** [comment]
In the closed thread you say
> Planned for v2.9 😸
Does it mean we'll have to wait for seven minor updates before Forge support as a package?
Or you're changing the versioning in the near future?

**Comment by mohnjiles** [comment]
No, first of all, version numbers don't work like that. We are not forced to release 10 bug fixes for every minor version. We (mostly) follow [Semantic Versioning](https://semver.org/).

If there are 40 patches before the next minor version, the release will be v2.8.43. There is no enforced sequence that says you have to go from v2.8.9 -> v2.9.0. We could also jump to releasing v2.9.0 tomorrow if we thought it was satisfactory enough to warrant a public release.

All that to say, it will release when it's ready 😸

**Comment by SpanishHearts** [comment]
> In the closed thread you say
> 
> > Planned for v2.9 😸
> 
> Does it mean we'll have to wait for seven minor updates before Forge support as a package? Or you're changing the versioning in the near future?

Yea I was asking the same. This sounds like a LOT of time. With the advancements this week and Stable Cascade, Forge will be obsolete until they add it to Stability Matrix.

**Comment by mohnjiles** [comment]
If you would like to try it as soon as possible, it's already available in our dev builds on [Patreon](https://www.patreon.com/StabilityMatrix), though we're still working out some kinks and it may not be perfectly stable just yet. Once it and the other planned features for v2.9.0 are stable, it will be released to the public.

**Comment by SpanishHearts** [comment]
> If you would like to try it as soon as possible, it's already available in our dev builds on [Patreon](https://www.patreon.com/StabilityMatrix), though we're still working out some kinks and it may not be perfectly stable just yet. Once it and the other planned features for v2.9.0 are stable, it will be released to the public.

I didn't know there is a way to support you, I'll do it right away. Stability Matrix is awesome and way better than Pinokio (minus the FaceFusion support)

Thanks!

**Comment by ViratX** [comment]
Please release the Forge update already! The FOMO is hard with this one.

**Comment by MaximumBlast** [comment]
Yes please!

**Comment by Heather95** [comment]
Until it gets added, just use Forge's one-click installer, go to edit webui > webui-user.bat in Notepad, and add this to set COMMANDLINE_ARGS=
--forge-ref-a1111-home "C:\Users\YourUsernameHere\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI"
Then it will share models with StabilityMatrix. Don't forget to edit in your username. Process will be different for non-Windows users.

**Comment by mohnjiles** [comment]
[v2.9.0 is now available](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.9.0) with Forge included :)
