### ISSUE TITLE
Model Browser, no longer will show TexturalInversion (if sorted by Newest) - ST v2.8.1

### ISSUE THREAD

**Issue by Manniala** [LykosAI/StabilityMatrix#445]
### [EDIT]
I went back to test the link i found on Patreon page, all Windows versions.
v2.8.0 Preview 4 - January 31
v2.8.0 Preview 3 - January 23
v2.8.0 Preview 2 - January 15

They all do the same, so the problem may be some place else, and not with the SM

With v2.8.1, i can enable Newest, AllTime, All, All, and it does show a new TexturalInversion, just not if i go to Model Type and pick TexturalInversion (may be relevant)

### [EDIT 2]
More info, if i do the Newest > AllTime > TexturalInversion > SD1.5, it shows new ones, same with SDXL 1.0, anything else i get No results found, this may just be because there are none, but it can show the newest if i pick either SD.1.5 or SDXL 1.0. But have not gotten it to show more than the first 2 pages, anything past 2 its back to the 20 results hidden by filters.

Putting in a @ for like @AceNeo it just shows that CivitAI cant be reached than.

[Before Edit]
(if this is new "bug" i do not know, i updated jut today, i have not downloaded the 2 i think latest updated, beta releases, for patreon)

Short story: Newest is not working for TexturalInversion

Long story:
If i go to Model Browser > TexturalInversion, and put in Sort: Newest, i get the usual "20 results hidden by filters".

I can switch to Most Downloaded and HighestRated, those 2 shows, but none of the other works, Newest, Installed (this one has not worked for a LOONG time, it did in the beginning when i first used, but than it stopped), Favorite.
Those 3 always shows 20 results hidden by filters.

I have tried the other with newest, they all show the newest (or at least a list, and not the 20 res...)

I did try to delete the "StabilityMatrix.db", rename my "settings.json" when i renamed the settings, i just get No results found on TexturalInvasion.
If i put in a user like @Denche354 i see it changes Page 1 / 4, but shows still 20 Result hiden by filters (I have Show NSFW Content enabled), if i were to toggle it off it than shows the VAE content, still being on TexturalInversion", pressing the Search it still keeps showing the content for VAE

**Comment by Manniala** [comment]
Hey, just tested, it is i working again 👍 
Thanks for the fast fix :)

**Comment by mohnjiles** [comment]
Sorry, what isn't working for you with the Installed sort order? It just shows no results at all? 🤔

**Comment by Manniala** [comment]
Hehe sorry.
As you can see on the image, if i pick Installed, it should than show well presume what i have installed, but it has not for month now, i have tried to remove mysettings, the .db...
So when i wrote that everything worked, and than Exept... i wanted to clarify that well this feature did not.

![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/2992709a-38b6-42e7-8241-272ae2c0b846)
