### ISSUE TITLE
Docker image possible

### ISSUE THREAD

**Issue by ghzgod** [LykosAI/StabilityMatrix#448]
First off, thank you for this amazing tool.  This is by far the best tool I've seen regarding all the various AI GUI's. Is there a way to run this in a docker container so I can view it in a web browser?  If not, are there plans in the future for such an implementation?

**Comment by jffaust** [comment]
I'm also wondering about this!

**Comment by luisalrp** [comment]
I was thinking the same. An official docker image would be awesome. Any chance to include it?

**Comment by mekler22** [comment]
Please consider docker/docker-compose support! thanks!
