### ISSUE TITLE
Add support for new package (Forge UI)

### ISSUE THREAD

**Issue by jillybob** [LykosAI/StabilityMatrix#459]
Forge UI is up to 75% faster than A1111 and ComfyUI. This UI looks and feels like Automatic 1111, but has a lot of things already integrated. It also has some extra functions that A1111 does not have. And Forge UI runs better on older cards. 

https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by mohnjiles** [comment]
Planned for v2.9 😸 
Closing this as a duplicate in favor of https://github.com/LykosAI/StabilityMatrix/issues/441
