### ISSUE TITLE
Feature Request: Stable Video Diffusion

### ISSUE THREAD

**Issue by rrouk** [LykosAI/StabilityMatrix#466]
Hello, are there any plans to add video diffusion to the settings

https://github.com/Stability-AI/generative-models

**Comment by mohnjiles** [comment]
Hi, this should be available as of v2.8.0 or later; you can click the `+` button on the tab bar for Inference to access the Image to Video project type like so:
<img width="300" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/33761/d7d83e66-f41b-4db2-aa58-b4ecdcd8ca11">
