### ISSUE TITLE
stable diffusion webui forge support ?

### ISSUE THREAD

**Issue by 9Somboon** [LykosAI/StabilityMatrix#472]
stable diffusion webui forge support ?

https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by ktee95** [comment]
same idea!

**Comment by eleius** [comment]
see https://github.com/LykosAI/StabilityMatrix/issues/441

**Comment by ViratX** [comment]
Bump

**Comment by mohnjiles** [comment]
Closing as duplicate in favor of https://github.com/LykosAI/StabilityMatrix/issues/441

Will be part of the next major release 😸
