### ISSUE TITLE
OneTrainer - Can't Find a Usable Init.tcl?

### ISSUE THREAD

**Issue by PresTrembleyIIIEsq** [LykosAI/StabilityMatrix#476]
I just installed OneTrainer through Stability Matrix in Manjaro, and on running it for the first time, I get the following error:

```
[PATH]/customtkinter/windows/ctk_tk.py", line 40, in __init__
    CTK_PARENT_CLASS.__init__(self, **pop_from_dict_by_set(kwargs, self._valid_tk_constructor_arguments))
  File "[PATH]/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    [List of directories]

This probably means that Tcl wasn't installed properly.
```

I double-checked, and I do have `tcl-8.6.13-1` and `tk-8.6.13-2` installed on my system. It also looks like [PATH]/StabilityMatrix/Assets/Python310/lib includes `Tix8.4.3` and `tcl8.6` folders that each have an `Init.tcl` file, as well, but these paths aren't included in the directories listed in the error.

Am I missing something, or does anyone have an idea on how to fix this?

**Comment by fortunefox** [comment]
Can confirm this happens. Bump

**Comment by eleius** [comment]
I also have this issue.

**Comment by PresTrembleyIIIEsq** [comment]
Just as a quick update, I tested un-installing and re-installing OneTrainer today to see if a more recent version of Stability Matrix happened to have fixed this, and it appears to install just fine, but I still get the same error on launch.

**Comment by nitrousoxXxide** [comment]
As of 26 May it's still broken

**Comment by jonidimo** [comment]
Same issue in Fedora 40 kde spin, Stability Matrix v2.11.0, still broken:
![image](https://github.com/LykosAI/StabilityMatrix/assets/400642/1d360f50-0063-4555-a312-bf9285dede0b)

**Comment by ionite34** [comment]
We've issued a fix for unified tcl/tkinter resolving across windows / macOS / linux in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.1, please try that to see if it fixes it.

On Linux GNU there seems to be other issues related to https://github.com/indygreg/python-build-standalone/issues/146 when X11 has already be initialized which we are looking into, but the "unable to find usable init.tcl" should be fixed at least.
