### ISSUE TITLE
Inference: warning, embedding:(name) does not exist, ignoring

### ISSUE THREAD

**Issue by 40inD** [LykosAI/StabilityMatrix#478]
While adding any <embedding> into promt or negative promt Comfy writes warnig "embedding:(embedding_name) does not exist, ignoring".
Version 2.8.3

**Comment by ionite34** [comment]
Hi, did you ensure that the spelling in the syntax is correct? It does not include the filename (i.e. .pth or .safetensors) Please try the newest version as well since some issues with nested folders for models have since been resolved.

**Comment by loneicewolf** [comment]
# In case someone has the same issue still:
replace `embedding_file_name` to `embedding_file_name`**extension** like Ionite34 mentioned!
I think, I have just begun using this and I just try to help others; do ping this reply if it is wrong!
