### ISSUE TITLE
Auto Open Apps on Windows Startup

### ISSUE THREAD

**Issue by SpanishHearts** [LykosAI/StabilityMatrix#488]
I just LOVE StabilityMatrix but something is eating me inside since I've installed it 4 months ago. I'm having a headless windows PC that's entirely dedicated to my local network. Is there any way to make StabilityMatrix to automatically open an app on startup? 

Before I was using Stability Matrix I just used an ComfyUi bat file on windows startup and it worked fine. Now I'm automatically starting the StabilityMatrix when Windows starts but I have no way to make StabilityMatrix launch an program on startup.

This would be a very welcomed feature!

**Comment by mohnjiles** [comment]
As of v2.9.0, you can create a shortcut with the `--launch-package` argument in the target, and then place the shortcut in the ` C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` folder. This should launch SM & the chosen web UI on Windows startup.

Shortcut example:
![image](https://github.com/LykosAI/StabilityMatrix/assets/33761/53926c8c-a218-44a5-ac8e-c78da44f434f)
