### ISSUE TITLE
BUG: missing safetensors from the models list

### ISSUE THREAD

**Issue by pavelkrupala** [LykosAI/StabilityMatrix#489]
Downloaded https://civitai.com/models/323787/ach-artstyle-ciloranko-pony?modelVersionId=362992,
put into Lora/style/artist/Ach_ciloranko-artist-final.safetensors
And I do not see it in the list (even after many refreshes). "Find connected metadata downloads all correctly"
![image](https://github.com/LykosAI/StabilityMatrix/assets/5364772/d4c2eca1-4c94-48d2-8487-54050ad05876)
ver: 2.8.3 latest

**Comment by mohnjiles** [comment]
This should be fixed as of v2.9.0. Feel free to reopen if the issue reoccurs. Thank you!

**Comment by ScreNN** [comment]
Same problem. Version 2.9.0
