### ISSUE TITLE
Install Reactor in ComfyUI failed

### ISSUE THREAD

**Issue by HeyTemp** [LykosAI/StabilityMatrix#507]
" building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension

  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for insightface

Failed to build insightface"

I have installed the Reactor extension both from the Packages->ComfyUI->extension page and from the ComfyUI Node Manager. An error message indicates an issue with the 'insightface' module, prompting to install Visual C++ 14 or higher. I tried installing Visual C++ build tool but still couldn't install it. Alternatively, attempting to install through 'insightface prebuild' using the command 'python install' that suggested from Reactor page, but the result the Stability Matrix system unusable.

Additionally, I usually do not download models directly from the model browser page because it causes Windows or the program to hang, especially when downloading multiple checkpoints simultaneously. Therefore, I often download all of them and then drag them into the model display page, press the 'find connected metadata' button. However, doing this does not show the 'installed' status in the model browser page and does not update if there are new model updates. I would like it so that when I drag a file into the model page and press 'find connected metadata,' it will display 'installed' or 'update' in the model browser page to know which ones are installed and which ones are not. This way, I can choose to download/update  files later from the model browser page later.
I also wish to be able to mark favorites on the model page.
Thank you for considering these suggestions.

**Comment by Tromazing** [comment]
Try installing Insightface through the Python Packages option within Stability Matrix.
Go to Packages, click the three dots on the ComfyUI section, then Python Packages, hit the + button and paste: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl into the Install Package box. Worked for me.
