### ISSUE TITLE
Can't install kohya_ss "ModuleNotFoundError: No module named 'packaging'"

### ISSUE THREAD

**Issue by ElevatedKitten** [LykosAI/StabilityMatrix#510]
Installing kohya_ss throws an error:

> Unpacking resources
> Unpacking resources
> Tkinter install complete
> Download Complete
> created virtual environment CPython3.10.11.final.0-64 in 383ms
> 
>   creator CPython3Windows(dest=D:\_AI\Data\Packages\kohya_ss\venv, clear=False, no_vcs_ignore=False, global=False)
> 
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\XXX\AppData\Local\pypa\virtualenv)
> 
>   added seed packages: pip==24.0, setuptools==69.1.1, wheel==0.42.0
> 
>   activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> 
> Traceback (most recent call last):
> 
>   File "D:\_AI\Data\Packages\kohya_ss\setup\setup_sm.py", line 1, in <module>
> 
>   import setup_windows
> 
>   File "D:\_AI\Data\Packages\kohya_ss\setup\setup_windows.py", line 7, in <module>
> 
>   import setup_common
> 
>   File "D:\_AI\Data\Packages\kohya_ss\setup\setup_common.py", line 13, in <module>
> 
>   from packaging import version
> 
> **ModuleNotFoundError: No module named 'packaging'**
> 
> Installed kohya_ss at [D:\_AI\Data\Packages\kohya_ss]

After this the installation shows under "Packages" but upon launching I get this error instantly: 

> Could not find part of the path: 'D:\_AI\Data\Packages\kohya_ss\library\wd14_caption_gui.py'

I use several other packages (Forge, ComfyUI etc.) without problems. 

Any help is appreciated.

**Comment by ElevatedKitten** [comment]
I just noticed that the paths are missing all a slash after the root drive. ("D:_AI\..." instead of "D:\_AI\...") 

Maybe the underscore of the "_AI" folder causes problems?

**Comment by Kagenokami** [comment]
Alright, so there are a LOT of issues with Stability Matrix in v23+ because the author separated sd_scripts into a separate github repo and also changed the location of some of the files that Stability Matrix apparently looks for. Also...seems the old working version "22.6.0" now installs in such a way that cuda is just...missing apparently.

**Comment by philmcrakin** [comment]
Sounds like you need to at least install packaging into your virtual enviroment
`pip3 install packaging`
And possibly upgrade/downgrade pip but we would need more information to know the full cause.

**Comment by highjohnconquer** [comment]
I'm having the exact same issue

**Comment by crack2483** [comment]
I'm also encountering an error with Koyha now. After Koyhas latest update today, I now get an error saying the WD14_caption_gui.py is missing from the kohya library path. Tried reverting back to previous Kohya versions but still get the same error.

**Comment by mohnjiles** [comment]
Hi everyone, sorry for the troubles, as of v2.9.1 this should be fixed for new installations and folks updating from kohya_ss version 22.x -> 23.x for the first time. 

If a fresh install is not an option, try running `git submodule update --init --recursive` inside the kohya_ss folder and then try launching it again (on v2.9.1 or later).
