### ISSUE TITLE
Assertion Error Regarding CUDA Compilation in Stability Matrix CPU Version System

### ISSUE THREAD

**Issue by JuanCPar** [LykosAI/StabilityMatrix#511]
I am not very familiar with these types of things, I'm trying to learn with Chat-GPT's help, so I'm making sure I have all the necessary software installed and up-to-date and choosing the right versions to download for CPU specific.

I have Stability Matrix WebUI by Automatic 1111 installed. During the launch portion I see this inside the process of installation
"Warning: caught exception 'Torch not compiled with CUDA enabled'" but it'll still open up Stable diffusion.

I have models installed and a control net. When I go to create an image I get the assertion error.

Any advice of what could be going wrong? You can explain it in very technical terms if necessary because I'll just use chat gpt to help me understand lol. 

I really want to learn and am hoping by working I'll learn, and not just watching tutorials.

Thanks!

**Comment by philmcrakin** [comment]
Without more information, like a copy of the log with each detail it's hard to say exactly what all is wrong. What command line arguments are you using? Running on CPU only you need all of the following
`--use-cpu all --precision full --no-half --skip-torch-cuda-test ` as outlined here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#running-on-cpu

If you can copy and paste the output next time then perhaps someone can help you get it up and running. I don't know what your OS is, or anything else that I would feel confident in assuming except this:

If your not using a GPU or certain Mac's it will be painfully slow if you do get it working.

I would suggest having a look at [FastSD CPU](https://github.com/rupeshs/fastsdcpu) if you haven't already.

Discloure: I haven't used it myself but from what I have seen it's pretty amazing how far SD and LCM's have come. I remember when I couldn't run it on my Radeon that I promptly sold and got the Nvidia RTX i'm currently using. It would run on the AMD I got rid of nowadays but I needed an upgrade in vram anyways.

Best of luck!
