### ISSUE TITLE
Sort function of model browser not working properly

### ISSUE THREAD

**Issue by nothingness6** [LykosAI/StabilityMatrix#520]
![StabilityMatrix](https://github.com/LykosAI/StabilityMatrix/assets/105210258/56c077ee-e0e5-4f2a-97bc-aa9a002e6a78)
As you can see the screenshot above, the sort function doesn't work properly. It should show the most downloaded ones first, but it looks like random view.

**Comment by KillerRu** [comment]
I've got the exact same problem. This one sneaked in in update 2.9.0 if I'm correct.

**Comment by mohnjiles** [comment]
This was an issue with civitai - https://github.com/civitai/civitai/issues/1047 - but it appears to be fixed now. It may take a few minutes for your local cache to update with the correct results.

Also, we are aware of the issue where the ratings & hearts don't appear anymore on the CivitAI model browser, as CivitAI has changed how these functions work. We'll have a fix in a future update for the incorrect rating info.
