### ISSUE TITLE
请问MAC 下载软件后，显示苹果电脑不可用，如何解决？谢谢

### ISSUE THREAD

**Issue by jacycai** [LykosAI/StabilityMatrix#526]
![截屏2024-03-17 下午2 49 28](https://github.com/LykosAI/StabilityMatrix/assets/130418411/746a61b6-cbdd-4ce4-8910-4739db122e49)
不可用

**Comment by ionite34** [comment]
Are you using an Intel Mac? It's not compatible since the packages and pytorch don't support Nvidia/AMD on Intel Macs, only Apple Silicon (M1, M2, M3, etc.)

**Comment by bluevisor** [comment]
不兼容Intel Mac
