### ISSUE TITLE
Failure installing InviokeAI package

### ISSUE THREAD

**Issue by Cad5z5** [LykosAI/StabilityMatrix#528]
Failure installing InviokeAI package:
Ubuntu 22.04.4 LTS, cuda, using symlink option and also without symlink gives the same error.

![Screenshot from 2024-03-18 07-23-12](https://github.com/LykosAI/StabilityMatrix/assets/159875370/05b5817c-6ced-4c49-8070-eea93f4cd027)

![Screenshot from 2024-03-18 07-23-50](https://github.com/LykosAI/StabilityMatrix/assets/159875370/fe924032-0b73-444c-a54b-7be99b1cc81e)

Log
[2024-03-18T05_07_52_268Z-debug-0.log](https://github.com/LykosAI/StabilityMatrix/files/14631381/2024-03-18T05_07_52_268Z-debug-0.log)

First time reporting problem in github, so sorry if formatting is not up to expected. I hope it helps. StabilityMatrix  is super.

**Comment by oroehrer** [comment]
Quick Fix. After the error window closed, close Stability Matrix, open it and under Packages  do an import.
