### ISSUE TITLE
OneTrainer can't update

### ISSUE THREAD

**Issue by abudfv** [LykosAI/StabilityMatrix#529]
When I try to update OneTrainer it stuck on 
"What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup "
requesting an answer, but I can't enter it

**Comment by karachay-b** [comment]
Same here.

Trying to start the app results in following:

> Traceback (most recent call last):
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\scripts\train_ui.py", line 6, in <module>
>     from modules.ui.TrainUI import TrainUI
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\ui\TrainUI.py", line 11, in <module>
>     from modules.trainer.GenericTrainer import GenericTrainer
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\trainer\GenericTrainer.py", line 24, in <module>
>     from modules.trainer.BaseTrainer import BaseTrainer
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\trainer\BaseTrainer.py", line 11, in <module>
>     from modules.util import create
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\util\create.py", line 15, in <module>
>     from modules.dataLoader.WuerstchenEmbeddingDataLoader import WuerstchenEmbeddingDataLoader
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\dataLoader\WuerstchenEmbeddingDataLoader.py", line 4, in <module>
>     from modules.dataLoader.WuerstchenBaseDataLoader import WuerstchenBaseDataLoader
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\dataLoader\WuerstchenBaseDataLoader.py", line 42, in <module>
>     from modules.dataLoader.wuerstchen.EncodeWuerstchenEffnet import EncodeWuerstchenEffnet
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\dataLoader\wuerstchen\EncodeWuerstchenEffnet.py", line 7, in <module>
>     from modules.model.WuerstchenModel import WuerstchenEfficientNetEncoder
>   File "A:\StabilityMatrix\Data\Packages\OneTrainer\modules\model\WuerstchenModel.py", line 7, in <module>
>     from diffusers.models import StableCascadeUNet
> ImportError: cannot import name 'StableCascadeUNet' from 'diffusers.models' (A:\StabilityMatrix\Data\Packages\OneTrainer\venv\src\diffusers\src\diffusers\models\__init__.py)
> 
> Process finished with exit code 1

**Comment by karachay-b** [comment]
Found a workaround:

> 1. git clone https://github.com/huggingface/diffusers.git in your OneTrainer root (StabilityMatrix/Data/Packages/OneTrainer)
> 2. copy the cloned folder named diffusers to venv/src and replace the files
> 3. update OneTrainer in StabilityMatrix --> Now itll skip the line where the updateprocess awaits a response
