### ISSUE TITLE
Install Stable Diffusision can´t be concluded

### ISSUE THREAD

**Issue by SamaraBlue** [LykosAI/StabilityMatrix#533]
Good morning everyone, hope your coffee was hot and good and you had a good start to the day.
Unfortunately, I'm still having problems installing Stabble Diffusin on my PC. I have seen a lot of different tutorials that basically all show the same procedure. I want to download 2 models. In principle, I can download all of them, which is indicated. In the end, however, the path required to start SD is not shown. I get the attached error message, which I just can't do anything with. Maybe someone has an idea or a tip. Unfortunately I´m not able to understand the error log file see beyound.
![99_Problem Install Stable Diffusion1](https://github.com/LykosAI/StabilityMatrix/assets/161628368/22738338-aaa0-4e89-9f04-982baa93b241)

(It doesn't need Win 11 and my PC has the necessary requirements and memory)
Best regards, Samara Blue

**Comment by mohnjiles** [comment]
You'll need to install & launch the Stable Diffusion web UI through the Stability Matrix app. Running standalone is not supported.

**Comment by SamaraBlue** [comment]
@mohnjiles , vielen Dank für die schnelle Antwort, die ich so leider nicht verstehe. Ich habe nach diesem Video installiert: https://www.youtube.com/watch?v=v-6bI2RMfxM&list=PLuyqDYq4IatpSVgvAke9IcWvHrzDZGgfO.
Wenn ich das richtig verstehe, ist das genau die korrekte Vorgehensweise. Alles funktioniert so wie beschrieben. Nur nach vollständiger  Installation aller Komponenten erhalte ich eben nicht den notwendigen Pfad für SD, sondern o.g. Fehler Protokoll. Auch alle anderen Videos, die ich mir angesehen habe, installieren auf diese Art und Weise.

@mohnjiles , thank you very much for the quick answer, which I unfortunately do not understand. I installed according to this video: https://www.youtube.com/watch?v=v-6bI2RMfxM&list=PLuyqDYq4IatpSVgvAke9IcWvHrzDZGgfO.
If I understand correctly, this is exactly the correct procedure. Everything works as described. Only after complete installation of all components I do not get the necessary path for SD, but the above mentioned error log. All other videos I have watched also install this way.

**Comment by mohnjiles** [comment]
Those instructions are for installing Stable Diffusion *without* Stability Matrix. They may still work, but we do not support that method. Please follow the setup wizard in the application to install via Stability Matrix.

Diese Anweisungen gelten für die Installation von Stable Diffusion *ohne* Stability Matrix. Sie funktionieren möglicherweise immer noch, aber wir unterstützen diese Methode nicht. Bitte folgen Sie dem Setup-Assistenten in der Anwendung, um über Stability Matrix zu installieren.

**Comment by SamaraBlue** [comment]
Vielen Dank für die schnelle Antwort. Da ich mich mit dieser Materie nicht wirklich auskenne, und eher verwirrt bin, wäre es möglich, dass Sie mir einen Link für den Set-up Assistenten zu senden. Von da aus werde ich wohl selber weiterkommen, hoffe ich :-)

Many thanks for the quick reply. As I am not really familiar with this matter and am rather confused, would it be possible for you to send me a link for the set-up wizard. From there I will probably be able to make progress myself, I hope :-)

**Comment by SamaraBlue** [comment]
Ich denke allerdings, dass ich schon mit dem Sep-up Assistenten installiert habe, denn die Schritte sehen sehr gleich aus. Nur an der Stelle, an der ich die Url bekommen soll, bekomme ich das Fehler Protokoll - siehe Anhang


However, I think I have already installed with the Sep-up wizard, because the steps look very similar. Only at the point where I am supposed to get the url, I get the error log
![Screenshot (108)](https://github.com/LykosAI/StabilityMatrix/assets/161628368/4ebb6a91-21af-4f30-9b8a-aa0f415cb73b)
