### ISSUE TITLE
[Feature Request] Download Missing Artwork for Checkpoints & Loras

### ISSUE THREAD

**Issue by Vigilence** [LykosAI/StabilityMatrix#538]
I noticed that I had a few checkpoints and Loras that I imported to stability matrix, which didn't have the artworks.  I checked but didn't see a way to download the missing artwork, aside from the downloading the entire model again.

- I would love the feature of just selecting the checkpoint, lora etc that has missing artwork and then clicking "download artwork" button.  

- It would also be cool if we can download all images associated with the model on civitai, including the authors images and the user submitted images, and then view them in a gallery underneath the checkpoint (if expanded to show).  Automatic1111 [has an extension](https://github.com/sunnyark/civitai-shortcut) similar to this for civitai.

- A [scan for new model](https://github.com/sunnyark/civitai-shortcut) version would be cool as well. 

- Another cool feature would be if we could manually drag and drop the artwork, or select and upload it for the checkpoint/lora.

- And the ability for us to generate artwork for keywords for each checkpoint/lora and then search the gallery for that keyword, so we can see how each model products images based on the keywords similar to [thumbnailizer](https://github.com/MNeMoNiCuZ/sd-webui-thumbnailizer).

**Comment by mohnjiles** [comment]
There is a button on the Checkpoints tab to scan all models for missing metadata & download them -
<img width="178" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/33761/4b11ac37-e5fd-49c8-90d7-065e7fd43b5c">

Alternatively, you can right-click any model on the Checkpoints tab and choose "Find Connected Metadata" there to just get info for one model.

The rest of the suggestions sound neat though! Will leave this issue open until we get some more done :)

**Comment by Vigilence** [comment]
Hello!

I did try the download metadata button and then refreshed and the image was not downloaded.  I checked to see if the model could be found on civitiai and it could be found.  Likewise the search for model button did find the model successfully, and even showed the cover photo for the model.
