### ISSUE TITLE
Comfyui extra_model_paths hard coded again

### ISSUE THREAD

**Issue by wardensc2** [LykosAI/StabilityMatrix#541]
Hi LykosAI

I try to add more model path into extra model path but anytime I start the stable matrix, it overwrites the new path I just add

As I already search this problem happen before and is fixed but after a few update it appear again.

Please support us to fix it

Thank you

**Comment by mohnjiles** [comment]
You'll need to add your extra paths outside of the `stability_matrix` section, as that section always gets overwritten. For example, a new category named `foobar`:

```
foobar:
  checkpoints: C:\My\path\to\checkpoints
stability_matrix:
  checkpoints: G:\SMData\Data\Data\Models\StableDiffusion
  vae: G:\SMData\Data\Data\Models\VAE
  loras: >-
    G:\SMData\Data\Data\Models\Lora

    G:\SMData\Data\Data\Models\LyCORIS
  upscale_models: >-
    G:\SMData\Data\Data\Models\ESRGAN

    G:\SMData\Data\Data\Models\RealESRGAN

    G:\SMData\Data\Data\Models\SwinIR
  embeddings: G:\SMData\Data\Data\Models\TextualInversion
... etc ...
```
