### ISSUE TITLE
wtf install error

### ISSUE THREAD

**Issue by LovelornKnight** [LykosAI/StabilityMatrix#546]
![스크린샷 2024-03-27 144259](https://github.com/LykosAI/StabilityMatrix/assets/83126102/1cedb4bf-5737-4b60-859b-566c6de5bd1d)

help me plz

**Comment by Sojou** [comment]
Same issue for me exactly. I had to reinstall windows and re-downloaded the latest SM. Is it because of the new build? Questions questions.

**Comment by mohnjiles** [comment]
Sorry folks, should be fixed now. There were some model updates that were causing issues. If you continue to have errors, try deleting your `Assets\Python310` folder and then try installing a package again.

**Comment by Sojou** [comment]
THANK YOU!!! It worked PERFECTLY!
