### ISSUE TITLE
Model Browser CivitAI only fetches the latest version of a model

### ISSUE THREAD

**Issue by Heather95** [LykosAI/StabilityMatrix#551]
The model browser for CivitAI in Matrix no longer detects or displays model versions correctly. Instead, it only shows the latest version, so if you have an older one installed, it won't be detected. The screenshots below might make more sense of my explanation.

~~Is anyone else having this issue, or is it only me?~~ Confirmed API issue, see comments below.

**Model example where I have the latest version installed. Older versions not displayed.**
![image](https://github.com/LykosAI/StabilityMatrix/assets/37752957/f96f198b-98ec-4dad-a284-462bb9924e86)

**Model example where I have an older version installed (v3.0) - It does not display. Only the latest version shows.**
![image](https://github.com/LykosAI/StabilityMatrix/assets/37752957/0bf0ef42-a650-4920-b29a-9013721ffa9b)

I tried to update metadata and reset the checkpoints cache, but nothing fixed it.

For now, I'll manage my Civit models outside of Matrix as a workaround.

**Comment by mohnjiles** [comment]
Sorry about that, it's related to an issue in civitai's API - you can follow along with the issue on their tracker here: https://github.com/civitai/civitai/issues/1100

**Comment by Heather95** [comment]
> Sorry about that, it's related to an issue in civitai's API - you can follow along with the issue on their tracker here: [civitai/civitai#1100](https://github.com/civitai/civitai/issues/1100)

That's okay, thank you for the update! I subscribed to that issue. I don't mind managing my Civit models outside Matrix for now, it's not much of a hassle for me.

**Comment by Heather95** [comment]
Everything looks normal this morning where I can see older model versions correctly, so it seems Civit fixed the API issue.
