### ISSUE TITLE
InvokeAI failing to install

### ISSUE THREAD

**Issue by styxadmin** [LykosAI/StabilityMatrix#556]
InvokeAI fails to install on version 2.92 of StabilityMatrix
![Screenshot_31](https://github.com/LykosAI/StabilityMatrix/assets/50232595/41faec93-b476-463d-81e4-6dd2c1fd25d3)

**Comment by truefriend-cz** [comment]
I have same problem

**Comment by mohnjiles** [comment]
Sorry about that, the latest v4.0 has made some significant changes to Invoke, we should have an update out soon to fix this.

**Comment by salmonrumpnova** [comment]
@mohnjiles I installed Invoke AI before the fix and it moved my models. Do you have any advice/steps on how to undo that?
