### ISSUE TITLE
InvokeAI Doesn't Recognize Models Automatically

### ISSUE THREAD

**Issue by smokelore** [LykosAI/StabilityMatrix#56]
![image](https://github.com/LykosAI/StabilityMatrix/assets/1188899/31ac86a9-d17d-4b79-838d-33311c594e06)

Hello! Love this software. Trying to do my bit.

I was excited to try out InvokeAI within StabilityMatrix, and it installed and ran without a hitch. However, it doesn't seem to be configured to automatically recognize the models that I have downloaded to `C:\Users\sebas\AppData\Roaming\StabilityMatrix\Models`. These models were already working properly within ComfyUI before I installed InvokeAI.

It seems there is a way to Import the models within the InvokeAI UI but it is quite tedious.

![image](https://github.com/LykosAI/StabilityMatrix/assets/1188899/adbf8d02-6524-4c4a-ab17-ff14a8c465bc)

I think it would be a massive improvement if StabilityMatrix would automatically import these or configure InvokeAI to recognize them. I believe this is the intended goal of StabilityMatrix so wanted to flag that it isn't working for InvokeAI yet.

I realize InvokeAI support was only added yesterday so I'm happy to wait for this feature to be ironed out.

Many thanks and keep up the great work!

**Comment by mohnjiles** [comment]
Hi, this should be fixed as of [v2.2.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.2.0). Thanks for the report!
