### ISSUE TITLE
PT-br Translation

### ISSUE THREAD

**Issue by jbostroski** [LykosAI/StabilityMatrix#562]
Hi! 

I'd like to help this project to be translated to Brazilian Portuguese. Can you guys sent me an invite? My e-mail is: bruno.ostroski@gmail.com

**Comment by faarish** [comment]
I have sent you an email.

**Comment by mohnjiles** [comment]
Thanks for reaching out! You should have received an email (probably a couple days ago) with an invite to our POEditor project. Let me know if you need me to resend it.

**Comment by jbostroski** [comment]
Hi, Sorry if this isn't the right place, but I need some context about the 'Shared Model Folder Strategy' (Label_SharedModelFolderStrategy)

**Comment by jbostroski** [comment]
Hi @mohnjiles, thanks for the opportunity. It's done! Please, feel free to contact me if you had any doubts or if I can help you with anything else.

**Comment by mohnjiles** [comment]
Thank you very much! We'll get that included soon :)
