### ISSUE TITLE
[Request] add DeeFooocus

### ISSUE THREAD

**Issue by aolko** [LykosAI/StabilityMatrix#563]
https://github.com/ehristoforu/DeFooocus / https://github.com/zachysaur/DeeFooocus

**Comment by thun-dar** [comment]
.\python_embeded\python.exe: can't open file 'D:\\AI\\DeFooocus_win64_portable\\DeFooocus\\entry_with_update.py': [Errno 2] No such file or directory
Press any key to continue . . 

when tried run.bat

**Comment by aolko** [comment]
> .\python_embeded\python.exe: can't open file 'D:\AI\DeFooocus_win64_portable\DeFooocus\entry_with_update.py': [Errno 2] No such file or directory Press any key to continue . .
> 
> when tried run.bat

try in pinokio https://github.com/aolko/deefooocus.pinokio
