### ISSUE TITLE
Broken Model Sharing Menu & Visual Bugs

### ISSUE THREAD

**Issue by ductiletoaster** [LykosAI/StabilityMatrix#568]
Hardware
- CPU AMD Ryzen 7 3800X 
- GPU AMD Radeon RX 6900XT
- 32 GB RAM
- 1 TB NVME

System 
- On Ubuntu 22.04 LTS (Dual boot Windows 11)
- Driver: https://repo.radeon.com/rocm/apt/6.0.2 jammy/main amd64
- Stability Matrix v2.9.3 (Also confirmed in v.2.9.2)

Getting some strange artifact around some menus and the Model Sharing fails to register click [unable to follow menu over].
[Screencast from 04-08-2024 09:53:50 PM.webm](https://github.com/LykosAI/StabilityMatrix/assets/595825/20f0ab57-5ff0-4c71-aea4-524a7ddd0faf)

I'm comfortable in a linux environment but don't know AppImage's well. I believe you guys are using some sort of framework to build cross platform apps in .net? 

It might be my OS is just missing some sort of dependency with GTK? I know AppImage's are portable (mostly) so just reaching at this point. Happy to help debug. 
(I did not have this issue on Windows 10 - same machine )

**Comment by ductiletoaster** [comment]
![Screenshot from 2024-04-08 21-53-39](https://github.com/LykosAI/StabilityMatrix/assets/595825/8ae42450-c757-469e-9f1f-76ab3bc01fca)
Noticed the screenshot upload failed.

**Comment by ductiletoaster** [comment]
Found another example. At this point it seems to be any small menu. 
![Screenshot from 2024-04-08 22-17-07](https://github.com/LykosAI/StabilityMatrix/assets/595825/6430a86e-9998-49a2-a344-5eac8cf6e286)

**Comment by notlet** [comment]
Me on Arch Linux here, similar issue. The tutorial popups have a rectangle behind them which for some reason shows into my desktop's background. That might just be a microsoft's UI framework issue though.

**Comment by ductiletoaster** [comment]
The visual bug is less of a concern. I can't use the model sharing though. Any workaround like a script or manual setting I can activate?

**Comment by ductiletoaster** [comment]
I found a workaround. I had to uninstall my package and reinstall with the model sharing selected as part of the install menu.
![Screenshot from 2024-04-10 05-24-51](https://github.com/LykosAI/StabilityMatrix/assets/595825/3fb0f1db-64a8-4d35-b8b0-8ad93170b894)

No ideal since I had already installed a bunch of extensions but workable.

**Comment by mohnjiles** [comment]
Sorry about that, we are continuously trying new Avalonia versions (our UI framework) to see if this fixes the issue. For now, you could try launching Stability Matrix with `--disable-gpu-rendering`, as the issue only seems to happen when using GPU rendering in our testing.
