### ISSUE TITLE
[Bug] Img2Img batch size not working

### ISSUE THREAD

**Issue by KreischerPanoptic** [LykosAI/StabilityMatrix#582]
Windows 11 x64
v2.10.0

In Img2Img projects "Batch Size" option not working. Inference always produces 1 image, no matter of Batch Size count.
Toggling "HiRes Fix" and "Upscaler" doesn't affecting that.

**Comment by mohnjiles** [comment]
This should be fixed as of [v2.11.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.0). Feel free to re-open this issue if it reoccurs. Thank you!
