### ISSUE TITLE
Can`t install Stable Diffusion WebUI

### ISSUE THREAD

**Issue by VoidDave** [LykosAI/StabilityMatrix#583]
Hi. So after break, i decided to get back to doing AI artork. I saw an update to WebUI and Stability Matrix Itself. After updates, i cant start WebUi. I decided to clean and install the stability matrix. but now I even cant install my Web UI!
I posting my logs that is saying failed to install (I tired disabling firewall)

Thanks for help

[logs.txt](https://github.com/LykosAI/StabilityMatrix/files/14963278/logs.txt)

**Comment by bosconian-dynamics** [comment]
Possible duplicate of #578, though I didn't experience the issue with `jsonmerge` as you have. There may be a [potential workaround](https://github.com/LykosAI/StabilityMatrix/issues/578#issuecomment-2052444485)

**Comment by VoidDave** [comment]
Yep adding those stuff to system variable helped thanks
