### ISSUE TITLE
After update to 24.0.1 kohya_ss does not launch from Stability Matrics

### ISSUE THREAD

**Issue by ZonSoft** [LykosAI/StabilityMatrix#600]
Kohya_ss is properly installed, set up and launches manually, but pressing Launch in Stability Matrics does nothing - terminal is not opening.

**Comment by shanafx** [comment]
Please run it manually in the C:\Users\yourname\AppData\Roaming\StabilityMatrix\Packages\kohya_ss folder

**Comment by ZonSoft** [comment]
As I wrote, it runs manually - but I believe the goal is to run it from Stable Matrix.
