### ISSUE TITLE
Output browser no longer sees Stable Diffusion Web UI pictures

### ISSUE THREAD

**Issue by Gol-D-Ace** [LykosAI/StabilityMatrix#611]
The output browser is no longer showing pictures for Stable Diffusion Web UI.

I noticed in my stable Diffusion Web UI package folder two folders:

output and outputs 

My images are in the outputs folder.

Did a migration fail to run here?

**Comment by mohnjiles** [comment]
This should be fixed now with [v2.10.3](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.10.3), sorry about that!
