### ISSUE TITLE
[Feature Request] Shared output browser should recognize JPG files

### ISSUE THREAD

**Issue by johnbrownlow** [LykosAI/StabilityMatrix#616]
Currently the shared output browser only recognizes PNG files. However, for example, StableSwarmUI outputs JPGs by default. 

(This can be changed easily in the package's settings but it took me AGES to figure out why I couldn't see them in the shared browser when they were there in the folder)

**Comment by mohnjiles** [comment]
This should be available as of [v2.11.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.0). Thank you for the suggestion!
