### ISSUE TITLE
CLIP Models in SD Next download to C: on Win

### ISSUE THREAD

**Issue by geonom** [LykosAI/StabilityMatrix#65]
Hey there, thank you for all your work first of all!

StabilityMatrix consistently downloads CLIP models, which I try to use in the Interrogater tab of SD Next to c:/User/username/.cache/ instead of the CLIP directory of the StabilityMatrix Models directory.

Also, SD Next does not find the CLIP models if moved to the CLIP directory of StabilityMatrix models and starts to download them again to the user .cache directory on drive c:

What I would expect?
For the model to be downloaded, found and used in the StabilityMatrix CLIP models folder.

In my case, that StabilityMatrix folder is on a separate much larger drive, so I really would prefer to have it all in one place as the folder structure suggests.

Thank you again.

I use StabilityMatrix on Win 10 with StabilityMatrix being Version 2.1.2 with the latest update to SD Next Version: fce48be4 Mon Aug 14 07:58:42 2023 +0000 , Latest published version: 2caee04b9a1a45b2109455eb186db820be03e8fd

**Comment by ionite34** [comment]
Seems to be something a SD.Next dependency or module is doing, we make the CLIP symlinks in the SD.Next's primary model directory but if it's not using that it's something that needs to be done on their end or on a dependency/plugin.
