### ISSUE TITLE
Ubuntu 23.04 .AppImage Problem

### ISSUE THREAD

**Issue by AyYildizPilot** [LykosAI/StabilityMatrix#66]
Hello,
It has been a very successful program.
Ubuntu 23.04 unfortunately has turned off .appimage support. I tried several ways to re-enable it.
It only has Snap support.

Will this software come in .deb version or snap support soon?

**Comment by ionite34** [comment]
I think the issue might be it no longer including FUSE 2, I'll look into it more but for now you can try `sudo apt install libfuse2` which should allow you to run existing AppImage apps on Ubuntu
