### ISSUE TITLE
[Feature Request] - File Deletion Confirmation (or send to Recycle Bin)

### ISSUE THREAD

**Issue by Judas87Swiff** [LykosAI/StabilityMatrix#665]
Issue:
When I accidently deleted a image I don't have the seed number to regenerate a similar image at that point, if I need to restore an image that has been deleted (via Stability Matrix) it currently doesn't seem possible to do so.

Solution:
Have Stability Matrix's Inference & Gallery Output have a confirmation when deleting files (can be turned off in settings), and when files are deleted send them to the Recycle Bin (Windows OS), or have a settings option to just remove them like it currently does.

**Comment by mohnjiles** [comment]
This was just added in [v2.11.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.0)! Thank you for the suggestion!
