### ISSUE TITLE
RuntimeError: "LayerNormKernellmpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by AyYildizPilot** [LykosAI/StabilityMatrix#67]
"SD.Next install now uses ROCm PyTorch backend on Linux AMD GPU machines for better performance over DirectML"

Hello, I installed the standard installation, the stable diffusion 1.5 model was downloaded, I got an error on the first run.
I encountered this error when I wrote my prompt and pressed the button to generate it.

Windows 10 pro 22H2
Amd ryzen 7 5800H
16GB Ram
GPU: AMD radeon RX 6600M 8GB VRAM

**Comment by ionite34** [comment]
Rocm's behavior on different AMD cards seems to differ quite a bit with different issues, could not reproduce this on our end to test. You can try `--skip-torch-cuda-test --no-half` or remake the issue with SD.Next since the dependency installs is handled by their install script now.
