### ISSUE TITLE
After updating cannot open checkpoint manager without crashing

### ISSUE THREAD

**Issue by CHollman82** [LykosAI/StabilityMatrix#683]
![image](https://github.com/LykosAI/StabilityMatrix/assets/3136566/ea46bb76-594b-4600-a50f-9020e3631d3c)

**Comment by ionite34** [comment]
Sorry about that, I think it's due to a change in one of the database models for civitai, looking into how to fix this for existing, but for now you can delete the `StabilityMatrix.db` file in the data directory and relaunch to fix it. 

The database file only includes cached information which can all be retrieved again when searching or reindexing your models, so there should be no loss of information.

**Comment by endersstory** [comment]
> Sorry about that, I think it's due to a change in one of the database models for civitai, looking into how to fix this for existing, but for now you can **delete the `StabilityMatrix.db` file in the data directory and relaunch to fix it.**
> 
> The database file only includes cached information which can all be retrieved again when searching or reindexing your models, so there should be no loss of information.

got the same error and just add .old to the extension StabilityMatrix.db. Now can click on the checkpoint manager and works. Thanks for the workaround.

**Comment by ionite34** [comment]
> > Sorry about that, I think it's due to a change in one of the database models for civitai, looking into how to fix this for existing, but for now you can **delete the `StabilityMatrix.db` file in the data directory and relaunch to fix it.**
> > The database file only includes cached information which can all be retrieved again when searching or reindexing your models, so there should be no loss of information.
> 
> @ionite34 I have the same issue even after removing the `StabilityMatrix.db` file. Using the latest version 2.11.1

Did you restart the app after doing so? The safest way is to delete it after the app is stopped and start the app afterwards. After make sure you're in the correct instance data directory (Can open in Settings > App Folders > Data Directory)

**Comment by CHollman82** [comment]
> Sorry about that, I think it's due to a change in one of the database models for civitai, looking into how to fix this for existing, but for now you can **delete the `StabilityMatrix.db` file in the data directory and relaunch to fix it.**
> 
> The database file only includes cached information which can all be retrieved again when searching or reindexing your models, so there should be no loss of information.

This worked for me, thank you!

**Comment by deady1000** [comment]
Renaming "~Data\StabilityMatrix.db" to "~Data\StabilityMatrix.db.old" and updating metadate worked for me.
