### ISSUE TITLE
ComfyUI  Failed to initialize NumPy

### ISSUE THREAD

**Issue by oneto8** [LykosAI/StabilityMatrix#689]
I installed StabilityMatrix and ComfyUI in it. This was on StabilityMatrix window after launching ComfyUI:

![Screenshot 2024-06-17 033604](https://github.com/LykosAI/StabilityMatrix/assets/37242602/6d9812be-fd6a-43d2-84fe-f8d132819138)
![Screenshot 2024-06-17 033626](https://github.com/LykosAI/StabilityMatrix/assets/37242602/ed0ad9c6-2dd5-43a2-b7e3-a6e9d8ebcb13)

Then I clicked "Open Web UI", clicked "Queue Promt"

![Screenshot 2024-06-17 033720](https://github.com/LykosAI/StabilityMatrix/assets/37242602/ec0d9c68-222c-43ee-86cd-bf8aee6c5ceb)
![Screenshot 2024-06-17 033730](https://github.com/LykosAI/StabilityMatrix/assets/37242602/a0ef12b9-b763-45c3-9ecb-9aa84029bfa2)
![Screenshot 2024-06-17 033805](https://github.com/LykosAI/StabilityMatrix/assets/37242602/46851d6f-0277-45a6-aef7-e91bfc9068da)

**Comment by oneto8** [comment]
Only thing I understand is that it suggests to downgrade numpy. I am going to try but I am not sure I got it right, I know little about this stuff. If someone knows for sure that I must downgrade numpy, tell me please I must downgrade numpy. Thank you!
Also I will be grateful if someone could advise me how to downgrade it.

**Comment by tombrau** [comment]
I have the same issue

**Comment by schneegor** [comment]
Ran into this problem with a fresh ComfyUI installation. If you go to https://numpy.org/ you'll see they just released NumPy 2.0 yesterday. Doh.

What I did: From within activated Python venv

1) pip uninstall numpy
-> it asks for Yes/No and shows you what it deinstalls, this should point to libs inside your Python virtual environment

2) pip install numpy==1.26.4

Restarted ComfyUI.Works.

**Comment by Fooftilly** [comment]
Numpy can be downgraded from the Packages tab. Find ComfyUI, right click on three dots menu on it -> python packages. Search for numpy and click on it. There will be version number at the top (in this case 2.0.0), select 1.26.4, and click the arrow icon (it says downgrade on hover) next to version. Wait for downgrade. Done. Relaunch ComfyUI.
