### ISSUE TITLE
Danbooru.csv 0KB

### ISSUE THREAD

**Issue by Nickdev7** [LykosAI/StabilityMatrix#698]
the auto completion file danbooru.csv has 0 bytes in it and i cant find another csv tags file thats works keeps saying: the input string " was not in a correct format

**Comment by ionite34** [comment]
Hi could you try manually downloading the file here: https://cdn.lykos.ai/tags/danbooru.csv and replacing the empty file, then relaunching the app?

**Comment by Nickdev7** [comment]
thanks it worked
