### ISSUE TITLE
Stability Matrix v.2.11.1 | Forge ] cannot import name 'packaging' from 'pkg_resources' 

### ISSUE THREAD

**Issue by JimM47** [LykosAI/StabilityMatrix#700]
Upon updating Stability Matrix and Forge UI today (6/19/2024), Forge will no longer launch, giving the following error:

> Traceback (most recent call last):
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\launch.py", line 51, in <module>
>     main()
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\launch.py", line 47, in main
>     start()
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\launch_utils.py", line 541, in start
>     import webui
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\webui.py", line 19, in <module>
>     initialize.imports()
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\initialize.py", line 53, in imports
>     from modules import processing, gradio_extensons, ui  # noqa: F401
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 18, in <module>
>     import modules.sd_hijack
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack.py", line 5, in <module>
>     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_hijack_optimizations.py", line 13, in <module>
>     from modules.hypernetworks import hypernetwork
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
>     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers.py", line 1, in <module>
>     from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\modules\sd_samplers_kdiffusion.py", line 3, in <module>
>     import k_diffusion.sampling
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
>     from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\repositories\k-diffusion\k_diffusion\evaluation.py", line 6, in <module>
>     import clip
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\clip\__init__.py", line 1, in <module>
>     from .clip import *
>   File "C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\clip\clip.py", line 6, in <module>
>     from pkg_resources import packaging
> ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\AI\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\pkg_resources\__init__.py)

Automatic1111 is working still.

Any ideas?

**Comment by ionite34** [comment]
Should be able to fix by downgrading the `setuptools` python package to version `69.5.1`, A1111 recently did this fix in their requirements https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15882, forge might need to do the same

**Comment by boudywho** [comment]
> Should be able to fix by downgrading the `setuptools` python package to version `69.5.1`, A1111 recently did this fix in their requirements [AUTOMATIC1111/stable-diffusion-webui#15882](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15882), forge might need to do the same.
> 
> Can use this interface: <img alt="image" width="302" src="https://private-user-images.githubusercontent.com/13956642/340942206-ed2bb6de-2e4a-4ce7-8918-c7028ec085f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTMwMjYsIm5iZiI6MTcxODc5MjcyNiwicGF0aCI6Ii8xMzk1NjY0Mi8zNDA5NDIyMDYtZWQyYmI2ZGUtMmU0YS00Y2U3LTg5MTgtYzcwMjhlYzA4NWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEwMjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTc5NzMxYWI0ZTJjMzc1ZDZkOTVmODllZGU0ZmE3MjUwODc1YTdjYmYzZDQ2NjUwNWNiZThkZGY2MTgyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5h42m7_l04sHxeEtkfSkej3vIkCPSCdlnpKwgdxHP8"> Search for setuptools, select 69.5.1, then click downgrade icon.

this fixed it, thanks

**Comment by JimM47** [comment]
Many thanks!
