### ISSUE TITLE
建议-增加本地模型的编辑功能。

### ISSUE THREAD

**Issue by Jojo-xqt** [LykosAI/StabilityMatrix#708]
并非所有的模型都来自huggingface和civitai，这些模型在stability Marix中是不包含数据的，希望可以手动编辑添加缩略图和其他元素信息。不胜感激。

**Comment by mohnjiles** [comment]
This should be available now, in versions [v2.12.0 or later](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.12.1). Right-click a model card to find the "edit metadata" option.

该功能现已可用，版本 [v2.12.0 或更高版本](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.12.1)。右键单击模型卡以找到“编辑元数据”选项。
