### ISSUE TITLE
ERROR - Missing display of 1.5 Hyper models

### ISSUE THREAD

**Issue by StabilityBro** [LykosAI/StabilityMatrix#717]
Dear team, I would like to report a small issue I have found in the **Checkpoint Manager**. When I try to view the "SD 1.5 Hyper" models, such as the Realistic Vision model (https://civitai.com/models/4201), they are not displayed in the interface. I would like to request that this problem be reviewed and corrected so that users can access all available information. I appreciate your attention and hope you can resolve this inconvenience as soon as possible. 🙏

**Comment by fizista** [comment]
The problem still exists!

Files with base model “SD 1.5 Hyper”, still do not display in “Checkpoint Manager”.

Here is a list of these models:
https://civitai.com/search/models?baseModel=SD%201.5%20Hyper&sortBy=models_v9

There is probably a bug in the code that is supposed to handle the “other” models.
