### ISSUE TITLE
Can't build wheels when installing requirements for several extensions

### ISSUE THREAD

**Issue by ApathyJones** [LykosAI/StabilityMatrix#72]
So far hit a wall trying to install certain requirements, such as insightface and pycuda. It attempts to build the wheels but fails with 

***   arg_to_python_base.cpp
***   bpl-subset/bpl_subset\boost/python/detail/wrap_python.hpp(50): fatal error C1083: Cannot open include file: 'pyconfig.h': No such file or directory
***   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
***   [end of output]
***   
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for pycuda
*** ERROR: Could not build wheels for pycuda, which is required to install pyproject.toml-based projects

This occurs when activating the venv manually and trying to install directly as well as when the extensions try to install. This does not occur if I do the same with a venv that is not controlled by Stability Matrix. I assume maybe it has to do with the embedded Python being used and not my local one?

**Comment by fmatulic** [comment]
Same problem here. Can't install almost any of the extensions because of various errors. Does the validation process for the UIs and main SD packages include checking that at least the most popular extensions can be correctly installed?

**Comment by ionite34** [comment]
This seems to be an [insightface](https://github.com/deepinsight/insightface) package issue in not having binary wheels and their build process not working. Not sure what we can do on our end to support it.
