### ISSUE TITLE
Cannot launch VoltaML

### ISSUE THREAD

**Issue by theDesuDesu** [LykosAI/StabilityMatrix#73]
So I'm getting this when trying to launch VoltaML:

      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pathtools
    Failed to build gpustat antlr4-python3-runtime basicsr filterpy future pathtools
    ERROR: Could not build wheels for gpustat, antlr4-python3-runtime, basicsr, filterpy, future, pathtools, which is required to install pyproject.toml-based projects
    ERROR    23:01:40 | core.install_requirements »      install_requirements.py:94
             Failed to install requirements:                                       
             requirements/pytorch.txt       

Now this is actually only one of the things that's not working for me right now - I also cannot install AUTO1111 and Invoke -  but judging by two other bug reports and the errors thrown by those other package installs I am thinking the pytorch deployment is the main bottleneck for all these problems.

I might be totally wrong though as I'm practically code-illiterate.

**Comment by ApathyJones** [comment]
This is the same issue that I posted about a few hours ago. My solution temporarily is to build the wheels via local python and copy them over, but that is somewhat complicated if you aren't familiar with all that stuff, but at least you know it isn't just you having the issue :)

**Comment by theDesuDesu** [comment]
Yeah I thought it was related but for me that is too unfamiliar indeed. Last time I tried something like that I borked all my SD Ui's :P
Also it's not a pressing issue right now as I did get ComfyUi to work fine and that is main jam so I'll just wait around till this inevitably gets fixed. 
Thanks for confirming it's not me borking things up again though!

**Comment by ApathyJones** [comment]
Gonna try a fresh install on my laptop and try a workaround. I'll post if it works and if it involves any code I'll add it to the pull requests.

**Comment by theDesuDesu** [comment]
Hey do you know what the best practice for a clean uninstal of this is? Because it hasn't got an entry in control panel and I'm worried if I just the delete the folder it will leave stuff that will mess things up in the future...

**Comment by Stax124** [comment]
> So I'm getting this when trying to launch VoltaML:
> 
> ```
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pathtools
> Failed to build gpustat antlr4-python3-runtime basicsr filterpy future pathtools
> ERROR: Could not build wheels for gpustat, antlr4-python3-runtime, basicsr, filterpy, future, pathtools, which is required to install pyproject.toml-based projects
> ERROR    23:01:40 | core.install_requirements »      install_requirements.py:94
>          Failed to install requirements:                                       
>          requirements/pytorch.txt       
> ```
> 
> Now this is actually only one of the things that's not working for me right now - I also cannot install AUTO1111 and Invoke - but judging by two other bug reports and the errors thrown by those other package installs I am thinking the pytorch deployment is the main bottleneck for all these problems.
> 
> I might be totally wrong though as I'm practically code-illiterate.

This was not a problem with Volta itself, but with a dependency that fails on Windows. We still have issues with the replacement package but it should no longer interfere with anything other that is not related to it.

If you have no other questions, please, close this issue.
Have a nice rest of your day.
