### ISSUE TITLE
Suggestion: Multiple download on same Resource

### ISSUE THREAD

**Issue by k000** [LykosAI/StabilityMatrix#734]
there are some Resources like Loras which collect multiple different Loras, lets say in some cases 50+. For now a single download on this resource, blocks it for selecting it again, which means you have to wait until the download is done to continue. Closing the app and reopen it would allow it but is for sure not the best way.

(example Resource with 80+ Loras: https://civitai.com/models/321329?modelVersionId=576343 )

**Comment by Jojo-xqt** [comment]
有一个我觉得不错的解决方法。C站的模型下载之后是依旧和网站关联的。在本地模型管理中，模型的弹出框和云端模型管理器是一样的，比如一系列的20个模型，已经下载了5个。在本地模型管理中，是有5个选项卡的。有这5个选项卡就可以实现批量下载了。=。=
