### ISSUE TITLE
[Feature Request] Please add mashb1t's Fooocus fork

### ISSUE THREAD

**Issue by thradya** [LykosAI/StabilityMatrix#741]
https://github.com/mashb1t/Fooocus

Mashb1t seems to be the only active maintainer of original Focus and he has his own enhanced fork where (I presume) he tests new features before merging into the original.

From read me:

> The purpose of this fork is to add new features / fix bugs and contribute back to [Fooocus](https://github.com/lllyasviel/Fooocus).
> 
> As a collaborator & contributor of the Fooocus repository you can find me in almost every [issue](https://github.com/lllyasviel/Fooocus/issues), [pull request](https://github.com/lllyasviel/Fooocus/pulls), [discussion](https://github.com/lllyasviel/Fooocus/discussions) etc.
> 
> Sadly the creator of Fooocus has gone dark multiple times for an extended amount of time, which is why I took matters into my own hands.

Thanks in advance.

**Comment by xx88xx** [comment]
+1 would be super useful

**Comment by Jojo-xqt** [comment]
+1，nice

**Comment by xx88xx** [comment]
any updates on this? or is it not possible?

**Comment by xx88xx** [comment]
Is this possible at all?
