### ISSUE TITLE
How to upgrade to python 3.11 ?如何升级至python 3.11？

### ISSUE THREAD

**Issue by kenic123** [LykosAI/StabilityMatrix#757]
How to upgrade to python 3.11 ?

**Comment by Jojo-xqt** [comment]
同问，我看设置里有环境变量这一项。我对python一窍不通，不知道可不可以。

**Comment by kenic123** [comment]
> 同问，我看设置里有环境变量这一项。我对python一窍不通，不知道可不可以。

不是一个概念，一个是环境，一个是环境中的一个变量
