### ISSUE TITLE
[Question] Can you perform installation operations from the command line?

### ISSUE THREAD

**Issue by za-wa-n-go** [LykosAI/StabilityMatrix#759]
Can StabilityMatrix perform package installation and other operations from the command line?

**Comment by mohnjiles** [comment]
Not currently, though that's something we could probably add. Would you want it to be completely headless (e.g. not open the UI at any point)? Or should it show the UI with install progress details?

**Comment by za-wa-n-go** [comment]
I would be happy if I could know the progress.
