### ISSUE TITLE
Webui ‘reForge’ support

### ISSUE THREAD

**Issue by lilcdj** [LykosAI/StabilityMatrix#760]
Someone recently made a new branch of WebUI Forge because there is no big update or implementation for original branch now. Can we get this package into stability matrix too? It has some good features compare to original Forge.

Github
https://github.com/Panchovix/stable-diffusion-webui-reForge

Reddit
https://www.reddit.com/r/StableDiffusion/s/UPaBt4vLVD

**Comment by Panchovix** [comment]
Was just gonna to post this haha, I'm new to Stability Matrix, but a lot of people have been requesting adding it to here!

**Comment by OneHandead** [comment]
Yes, please!

**Comment by EriIaz** [comment]
I second this feature request. The implementation should be trivial, and it's very much warranted due to the current Forge status.

**Comment by killerciao** [comment]
Right now you can switch to reforge on stabilitymatrix and it will work without problems.
Just activate the venv inside forge installation folder and then:
`git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge
git branch Panchovix/main
git checkout Panchovix/main
git fetch reForge
git branch -u reForge/main
git pull`

**Comment by drdancm** [comment]
killerciao,

Most of us, I think, do not want to switch to ReForge, but have **both Forge and ReForge**, so we can run each one.

**Comment by mohnjiles** [comment]
We currently plan to release this as part of v2.12.0, though if you would like to try it as soon as possible, it's now available in our dev builds on [Patreon](https://www.patreon.com/StabilityMatrix). We're still doing some testing so it may not be perfectly stable on all operating systems just yet, but it is coming!

**Comment by koopa990** [comment]
> Right now you can switch to reforge on stabilitymatrix and it will work without problems. Just activate the venv inside forge installation folder and then: `git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git pull`

![image](https://github.com/user-attachments/assets/ce4b7f32-03a2-48de-8dd8-2fa3b7fef39b)
What is this error of iu?

**Comment by killerciao** [comment]
> > Right now you can switch to reforge on stabilitymatrix and it will work without problems. Just activate the venv inside forge installation folder and then: `git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git pull`
> 
> ![image](https://private-user-images.githubusercontent.com/63154730/352790467-ce4b7f32-03a2-48de-8dd8-2fa3b7fef39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTMwNjksIm5iZiI6MTcyMjE1Mjc2OSwicGF0aCI6Ii82MzE1NDczMC8zNTI3OTA0NjctY2U0YjdmMzItMDNhMi00OGRlLThkZDgtMmZhM2I3ZmVmMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZmQyMTZlZWFhNDNjMGNmNjcxNTQ5MzgzOTJhOTczZmY1ZDVkZDFiYzM4MGJlYzdjZWZhNTY5ZDNhNjI1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULf7H1YQPMWmoBM6TO8IZLgnJqrRBp2vUXNub8HxaIw) What is this error of iu?

git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge
git branch Panchovix/main
git checkout Panchovix/main
git fetch reForge
git branch -u reForge/main
git reset --hard
git pull
 
 you must do one line at time. not all together

**Comment by koopa990** [comment]
> > > Right now you can switch to reforge on stabilitymatrix and it will work without problems. Just activate the venv inside forge installation folder and then: `git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git pull`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/63154730/352790467-ce4b7f32-03a2-48de-8dd8-2fa3b7fef39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTMwNjksIm5iZiI6MTcyMjE1Mjc2OSwicGF0aCI6Ii82MzE1NDczMC8zNTI3OTA0NjctY2U0YjdmMzItMDNhMi00OGRlLThkZDgtMmZhM2I3ZmVmMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZmQyMTZlZWFhNDNjMGNmNjcxNTQ5MzgzOTJhOTczZmY1ZDVkZDFiYzM4MGJlYzdjZWZhNTY5ZDNhNjI1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULf7H1YQPMWmoBM6TO8IZLgnJqrRBp2vUXNub8HxaIw) What is this error of iu?
> 
> git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git reset --hard git pull
> 
> you must do one line at time. not all together

Disregard that early message.

I got a bunch of conflicting messages in Git 
![image](https://github.com/user-attachments/assets/24437654-2b22-4163-b979-5780a10e6fbb)

**Comment by Panchovix** [comment]
> > > > Right now you can switch to reforge on stabilitymatrix and it will work without problems. Just activate the venv inside forge installation folder and then: `git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git pull`
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/63154730/352790467-ce4b7f32-03a2-48de-8dd8-2fa3b7fef39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTMwNjksIm5iZiI6MTcyMjE1Mjc2OSwicGF0aCI6Ii82MzE1NDczMC8zNTI3OTA0NjctY2U0YjdmMzItMDNhMi00OGRlLThkZDgtMmZhM2I3ZmVmMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZmQyMTZlZWFhNDNjMGNmNjcxNTQ5MzgzOTJhOTczZmY1ZDVkZDFiYzM4MGJlYzdjZWZhNTY5ZDNhNjI1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULf7H1YQPMWmoBM6TO8IZLgnJqrRBp2vUXNub8HxaIw) What is this error of iu?
> > 
> > 
> > git remote add reForge https://github.com/Panchovix/stable-diffusion-webui-reForge git branch Panchovix/main git checkout Panchovix/main git fetch reForge git branch -u reForge/main git reset --hard git pull
> > you must do one line at time. not all together
> 
> Disregard that early message.
> 
> I got a bunch of conflicting messages in Git ![image](https://private-user-images.githubusercontent.com/63154730/352815565-24437654-2b22-4163-b979-5780a10e6fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxOTgwNzAsIm5iZiI6MTcyMjE5Nzc3MCwicGF0aCI6Ii82MzE1NDczMC8zNTI4MTU1NjUtMjQ0Mzc2NTQtMmIyMi00MTYzLWI5NzktNTc4MGExMGU2ZmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDIwMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjA5Y2M0MTY5ZjAzM2Y4NDZjNTg1YjEzNGUwOTllYWIyNjBmNDNhY2U1NGVlOWE0MTA0Y2NhYjkxNzUyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kd7er3cgyOowU4_Pi9Cg-GP1d39OAJaiwVF1gm8rWy0)

That's an issue when coming from A1111, for some reason now that does happen now.

Instead of git reset --hard, git stash should work. Gonna update the README.

I can also suggest a clean install. I think when Stability Matrix adds native support it will work better as well.
