### ISSUE TITLE
OneTrainer won't launch on Linux

### ISSUE THREAD

**Issue by genevera** [LykosAI/StabilityMatrix#761]
I get the following error output from OneTrainer along with an exit code of 134.

```
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
```

**Comment by geonom** [comment]
For me at least, I get the error with OneTrainer at startup - but also Kohya_ss has the same issue as soon as I hit the button to load a model from a folder:

`--------
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.`

**Comment by noidedxyz** [comment]
I'm on arch and having the same issue. I have not tried to manually install it yet, though.

**Comment by noidedxyz** [comment]
Okay I have fixed this for myself. What I did was manually install OneTrainer with python3.10 (from the AUR) and then copying and pasting that installation into Stability's "packages" folder. I think the problem here is Stability assumes your native python installation is 3.10, I might be wrong but either way it works now.

**Comment by genevera** [comment]
I wound up installing it manually using a fresh and isolated virtual env and it was def kind of a pain.  I think there are conflicting packages in the SM venv that cause this one to not work.  Also the pytorch it wants to install is linked to cuda 11.8 so if you have 12.X that could be a problem too maybe?  Speculating.
