### ISSUE TITLE
Can't start Stable Diffusion WebUI Forge Error by Unobserved Task Exception - IOException

### ISSUE THREAD

**Issue by naoyaikeda** [LykosAI/StabilityMatrix#763]
Stable Diffusion WebUI Forge suddenly can't start.
Error is Unobserved Task Exception - IOException.

Error is maybe can't create existed file?

My environment is Japanese. Error message is Japanese Error message. 

How to manage this trouble.

**Comment by naoyaikeda** [comment]
I can start Stable Diffusion WebUI Forge from webui.bat.
Only cant't run from Stability Matrix.

**Comment by coreshock** [comment]
Just stumbled upon this issue with the latest Matrix and Forge updates (Stable v2.11.8 and main@3e25301 correspondingly). Everything was fine before.

**Comment by Creative-Geek** [comment]
> Just stumbled upon this issue with the latest Matrix and Forge updates (Stable v2.11.8 and main@3e25301 correspondingly). Everything was fine before.

yeah me too
just updated to 2.11.8 and this issue appeared

**Comment by sanookd555** [comment]
uncheck  output sharing

**Comment by coreshock** [comment]
> uncheck output sharing

thanks, this was also labeled as a bug and covered in related issue https://github.com/LykosAI/StabilityMatrix/issues/853
