### ISSUE TITLE
face ip adaptor not loading, error even after installl and refresh

### ISSUE THREAD

**Issue by 37OMKAR** [LykosAI/StabilityMatrix#773]
[

**Comment by 37OMKAR** [comment]
help any one

**Comment by mohnjiles** [comment]
You can use the builtin Python Packages menu and install insightface by pasting this link: `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl`


![image](https://github.com/user-attachments/assets/9db1739f-487e-4f69-a53a-30a366c4f135)
![image](https://github.com/user-attachments/assets/e7d47b7b-7859-47be-bfb9-108f55c6ea16)
