### ISSUE TITLE
ComfyUI update

### ISSUE THREAD

**Issue by seung-ltd** [LykosAI/StabilityMatrix#777]
ComfyUI no longer starts after recent update.

OSERROR: [WinError 126] The specified module could not be found. Error loading "...fbgemm.dll" or one of its dependencies.

**Comment by shamanicvocalarts** [comment]
same error

**Comment by mohnjiles** [comment]
Assuming nvidia GPU, try going to the Packages tab -> 3 dots menu for comfy -> Python Packages -> + Button and enter
`torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 xformers==0.0.23.post1 --extra-index-url https://download.pytorch.org/whl/cu121 --force-reinstall`

This will reinstall torch & should include the missing file as well

**Comment by shamanicvocalarts** [comment]
> Assuming nvidia GPU, try going to the Packages tab -> 3 dots menu for comfy -> Python Packages -> + Button and enter `torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 xformers==0.0.23.post1 --extra-index-url https://download.pytorch.org/whl/cu121 --force-reinstall`
> 
> This will reinstall torch & should include the missing file as well


this does fix the install but breaks most of my custom nodes, had previously tried reinstalling torch & ran into similar issues,  will go through and try to fix the errors preventing them from importing

**Comment by seung-ltd** [comment]
Would reverting the comfy ui install to a previous build fix this? Everything was stable before. If so, how do I go about reverting it?

**Comment by shamanicvocalarts** [comment]
after reinstalling a few problematic custom nodes it seems the fix posted above fixes the issue. 

with regards to @seung-ltd question about reverting the build, I believe there is no way to do this inside of the stability-matrix client, though there may be a way to do so via Pip/git. 

I wonder if having a native way to revert / install older builds directly from inside of stability matrix would be a valuable feature request. it could be worth making a feature request for this

**Comment by berguven** [comment]
Tried @mohnjiles method, but it causes a numpy-error("Numpy is not available", in KSampler) instead and when the ComfyUI is updated the original error returns.

Have tried uninstalling and reinstalling ComfyUI via StabilityMatrix, but error remains,

**Comment by ziilch** [comment]
I have the same error

**Comment by ziilch** [comment]
> Assuming nvidia GPU, try going to the Packages tab -> 3 dots menu for comfy -> Python Packages -> + Button and enter `torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 xformers==0.0.23.post1 --extra-index-url https://download.pytorch.org/whl/cu121 --force-reinstall`
> 
> This will reinstall torch & should include the missing file as well

This fixed the issue for me thanks

**Comment by ziilch** [comment]
> Tried @mohnjiles method, but it causes a numpy-error("Numpy is not available", in KSampler) instead and when the ComfyUI is updated the original error returns.
> 
> Have tried uninstalling and reinstalling ComfyUI via StabilityMatrix, but error remains,

I'm getting this too, I'm trying to use the AutoCinemagraph ComfyUI workflow and I'm getting these same errors

**Comment by ctrp1** [comment]
for me it was resolved that I installed the Visual C++ Redistributable Runtimes All-in-One
