### ISSUE TITLE
Comfui launch problem

### ISSUE THREAD

**Issue by mkmkmknknkb** [LykosAI/StabilityMatrix#780]
![Screenshot 2024-07-26 123209](https://github.com/user-attachments/assets/350df0f2-9969-4cec-ba22-5a6fd40c6264)

Guys, I faced this problem to install and launch ComfyUI

**Comment by ionite34** [comment]
Hi how did you install or import this package initially? I noticed it is shown as Fooocus package type.

**Comment by mkmkmknknkb** [comment]
> Hi how did you install or import this package initially? I noticed it is shown as Fooocus package type.

Sorry, I uploaded the picture by mistake
