### ISSUE TITLE
Conflict Dependicies Problem

### ISSUE THREAD

**Issue by sprkles3443** [LykosAI/StabilityMatrix#782]
Hi, when i am trying to update Stability Diffusion WebUI Forge i am getting this error ;

```
Cannot install fastapi==0.104.1, gradio==4.39.0 and pydantic==1.10.15 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic==1.10.15
    fastapi 0.104.1 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
    gradio 4.39.0 depends on pydantic>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict
```

Even if i try to fresh install same error occurs. Can anyone help?

**Comment by IvanFromGardarike** [comment]
Same problem

**Comment by KillerRu** [comment]
I'm getting a lot more dependency problems since the latest update...
I'm also running into dependency problems with Stable Diffusion Webui and SD Forge...

**Comment by r3b3lxxleader** [comment]
> I'm getting a lot more dependency problems since the latest update... I'm also running into dependency problems with Stable Diffusion Webui and SD Forge...

I can't even get mine to update.

**Comment by KillerRu** [comment]
Reinstall gives me this error now... So installing again is a problem too:
![2024-07-27 10_31_56-](https://github.com/user-attachments/assets/46ef45fa-9d44-459d-8040-722ba82a0b6c)

**Comment by yundin2000** [comment]
same problem here

**Comment by Nisekoi-1** [comment]
same

**Comment by junny2233** [comment]
here is a fix


thanks too on reddit [zoneender89](https://www.reddit.com/user/zoneender89/)

[r/StableDiffusion- Reddit Post](https://www.reddit.com/r/StableDiffusion/comments/1ed5fl7/comment/lf5gfny/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

if you're getting the dependency issue, you can fix it by opening your requirements_versions file in your package folder. change pydantic to pydantic==2.8.2

**Comment by sprkles3443** [comment]
> @sprkles3443
> 
> here is a fix
> 
> thanks too on reddit [zoneender89](https://www.reddit.com/user/zoneender89/)
> 
> [r/StableDiffusion- Reddit Post](https://www.reddit.com/r/StableDiffusion/comments/1ed5fl7/comment/lf5gfny/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
> 
> > if you're getting the dependency issue, you can fix it by opening your requirements_versions file in your package folder. change pydantic to pydantic==2.8.2

Yes, I actually posted in that thread 

> [Money_Worldliness159](https://www.reddit.com/user/Money_Worldliness159/)
> -
> [15 hours ago](https://www.reddit.com/r/StableDiffusion/comments/1ed5fl7/comment/lf5pp19/)
> it won't let me change it, somehow it goes back to 1.10.15. i guess we have to wait for an update.

I had changed the version to 2.8.2 and closed the txt file but this time I kept the requirements_version.txt open and updated it and it worked. 

Thank you.

**Comment by GeminiSquishGames** [comment]
You may also have to disable extensions that are causing errors. Many don't work and need updated to work with new gradio.

**Comment by sergiogbrox** [comment]
same problem

**Comment by GeminiSquishGames** [comment]
> same problem

Have you downloaded the latest release and manually replaced your .exe file yet? I think that should do it.

**Comment by sergiogbrox** [comment]
> > same problem
> 
> Have you downloaded the latest release and manually replaced your .exe file yet? I think that should do it.

i fix with this:

https://www.reddit.com/r/StableDiffusion/comments/1ed5fl7/comment/lf5gfny/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

![image](https://github.com/user-attachments/assets/49d311d8-1799-40b1-8232-9a13c18072e7)

**Comment by GeminiSquishGames** [comment]
> > > same problem
> > 
> > 
> > Have you downloaded the latest release and manually replaced your .exe file yet? I think that should do it.
> 
> i fix with this:
> 

I did too at first to get it working, but I still had to download the fixed .exe manually, or it still couldn't update properly. But if you've got it working that's good!

**Comment by CHollman823** [comment]
I also had this problem and the fix above worked... but this is ridiculous. Non-stop issues, every single time it updates it breaks in one way or another.

**Comment by Nisekoi-1** [comment]
> I also had this problem and the fix above worked... but this is ridiculous. Non-stop issues, every single time it updates it breaks in one way or another.

Then don't update it

**Comment by GeminiSquishGames** [comment]
> I also had this problem and the fix above worked... but this is ridiculous. Non-stop issues, every single time it updates it breaks in one way or another.

I've been auto updating regularly with no problems since the first hiccup where you'd have to get a fresh release manually. Maybe try using git to update the repo if the .exe auto updates always break. That sounds like something on your system doesn't like it, but that is usually made apparent by say a firewall or virus/malware protection getting false positives.
