### ISSUE TITLE
ComfyUI-Easy-Use 插件安装出现报错

### ISSUE THREAD

**Issue by sw19852006** [LykosAI/StabilityMatrix#784]
![QQ截图20240728172933](https://github.com/user-attachments/assets/f02e5b09-ed63-4fcd-be5c-3034cb5dde49)

**Comment by sw19852006** [comment]
![QQ截图20240728173122](https://github.com/user-attachments/assets/aebc2770-207f-48e7-98f3-675abb0d4fdb)
![Uploading QQ截图20240728173139.png…]()

**Comment by GeminiSquishGames** [comment]
I'm not sure but it's probably an issue for https://github.com/yolain/ComfyUI-Easy-Use? Doesn't seem related to Stability Matrix but that ComfyUI node.
