### ISSUE TITLE
InvokeAI Model Sharing is None

### ISSUE THREAD

**Issue by johnwickstyle** [LykosAI/StabilityMatrix#785]
**### when i use InvokeAI it has no link to Model Sharing so i don't want to download same model and addon for it. please provide symlink for this . thank you!**
![Screenshot 2024-07-28 213151](https://github.com/user-attachments/assets/f961a75e-c14a-4dce-a345-baf30f9d0da9)

**Comment by LadyFlames** [comment]
no its like that for a reason because if model sharing for invoke has a symlink  thats gonna make it so that invoke cant be installed at all you will get a whole bunch of errors makes your pc crash at times but  theyr working on fixing it for the next invoke version that should fix the issue
