### ISSUE TITLE
Forge cannot be updated or installed

### ISSUE THREAD

**Issue by abudfv** [LykosAI/StabilityMatrix#789]
Getting an error when try to update or install Forge. (SM latest)

ERROR: Cannot install fastapi==0.104.1, gradio==4.39.0 and pydantic==1.10.15 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic==1.10.15
    fastapi 0.104.1 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
    gradio 4.39.0 depends on pydantic>=2.0

**Comment by mohnjiles** [comment]
Please check SM for updates again, this should be fixed as of v2.11.5
