### ISSUE TITLE
Auto launch option does not seem to work

### ISSUE THREAD

**Issue by Altares** [LykosAI/StabilityMatrix#790]
I'm using the Comfy-UI option in the UI: --auto-launch. But nothing happens when I start Stability Matrix.
Expected behaviour is that Comfy-UI would launch when Stability Matrix is started (Stability Matrix is running on a server on my network that is not my main machine).
I'd also use that option on other packages, but first Comfy-UI since it's my go-to UI.
I am using the .appimage build on fedora.
Thank you
<img width="2560" alt="Screenshot 2024-07-30 at 12 48 47" src="https://github.com/user-attachments/assets/4dc6baa2-ca15-463f-916a-bea831e5870c">

**Comment by Altares** [comment]
I just realised that this option may not be about auto-launching the backend but maybe launching the frontend in the default browser.

Can you please provide the options that Comfy-UI is using when being called from within Stability Matrix? So that we'll be able to run it standalone using a script. I'm mostly referring to the way Stability Matrix handles all the extensions for packages and shared paths. If I launch Comfy using: "python3 serve.py --listen 0.0.0.0" it may not be enough to keep the settings inside Stability Matrix in sync.

**Comment by mohnjiles** [comment]
You can launch Stability Matrix with the `--launch-package` argument to start one of your UIs on launch. Check this post for more info: https://github.com/LykosAI/StabilityMatrix/issues/488#issuecomment-1975491006

Also note that if your package name contains spaces, you'll need to surround it in quotes, e.g. `--launch-package "ComfyUI with spaces"`

**Comment by Altares** [comment]
> You can launch Stability Matrix with the `--launch-package` argument to start one of your UIs on launch. Check this post for more info: [#488 (comment)](https://github.com/LykosAI/StabilityMatrix/issues/488#issuecomment-1975491006)
> 
> Also note that if your package name contains spaces, you'll need to surround it in quotes, e.g. `--launch-package "ComfyUI with spaces"`

Thanks!
