### ISSUE TITLE
Roop not working in Stability Matrix

### ISSUE THREAD

**Issue by rvpv** [LykosAI/StabilityMatrix#80]
I was using A1111 natively, however, I wanted to move to StabilityMatrix. However, the roop and [ReActor](https://github.com/Gourieff/sd-webui-reactor) plugin cannot be installed.
On a clean A1111 without Stability Matrix, it installs correctly. 

Logs are too long to paste here so i paste it on pastebin: https://pastebin.com/FFTQGDCy

**Comment by drdancm** [comment]
I have the same problem, but on A1111, outside of StabM it fails the same way. The error states that it cannot be installed because the program to do it is deprecated. My StabM computer is turned off so I will bring up the message and paste it here tomorrow.

**Comment by drdancm** [comment]
There appears to be a problem with other face-swap projects, apparently because they have the same required things (insightface, inswapper, onnxruntime, etc.) I'm wondering whether install issues are related to the portable setup feature.
