### ISSUE TITLE
"Backends are still loading on the server... " on SwarmUI

### ISSUE THREAD

**Issue by phiren839** [LykosAI/StabilityMatrix#815]
This message remains above the interface, the reboot didn't help. StabilityMatrix and SwarmUI are up to date. I have another instance of SwarmUI which works perfectly apart from StabilityMatrix.

**Comment by Mayakwang** [comment]
The installation folder name of SwarmUI must be "SwarmUI ". If you change the name, you will get an error and a red warning saying backends are still loading on the server.
Rename the installation folder to "SwarmUI "
