### ISSUE TITLE
"Cannot find ptxas" in Forge

### ISSUE THREAD

**Issue by phiren839** [LykosAI/StabilityMatrix#816]
![2024-08-11_15-02](https://github.com/user-attachments/assets/bf0ead9c-f286-4a09-8a82-71b2ca0df6d3)

**Comment by shalim2904** [comment]
same here

**Comment by j1seki** [comment]
I know it s not correct solution but i tried to upgrade the torch and torchvision python packages despite it failed it fixed ptxas issue try if you like worse case you broke smt broken

**Comment by PietHelzel** [comment]
Had this issue as well, but it seems to be fixed now with the latest version

**Comment by opisaac9001** [comment]
> I know it s not correct solution but i tried to upgrade the torch and torchvision python packages despite it failed it fixed ptxas issue try if you like worse case you broke smt broken

May i ask how you did that? Im using ubuntu if that matters.
