### ISSUE TITLE
Problems installing SD Forge

### ISSUE THREAD

**Issue by Dracanto** [LykosAI/StabilityMatrix#829]
I have already installed A1111 and ComfyUI normally, without any problems.

However, when I try to install Forge, this version and dependency conflict appears:

ERROR: Cannot install fastapi==0.104.1, gradio==4.40.0 and pydantic==1.10.15 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic==1.10.15
    fastapi 0.104.1 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
    gradio 4.40.0 depends on pydantic>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Could not install stable-diffusion-webui-forge 

Can anyone help me? I don't want to have to uninstall all the other programs. Thank you very much.

**Comment by mohnjiles** [comment]
This should be fixed on newer versions of Stability Matrix, starting with v2.11.5. Could you try updating first via the green download icon in the bottom left of the Stability Matrix window?

**Comment by Dracanto** [comment]
My Stability Matrix is ​​up to date, but I've already managed to resolve it. Apparently it was the wrong version of pydantic.

If anyone else is having this kind of problem, the solution was simple, install your SD Forge until the error appears. Then open the local forge folder, look for the requirements_versions.txt file, and change the version from "pydantic==1.10" to "pydantic==2.8.2", save the file, close the matrix, reopen it and run sd Forge.

**Comment by fbauer-kunbus** [comment]
Just installed Forge for the first time in SM - and the error didn't occur ... wrong pydantic has obviously already been fixed
