### ISSUE TITLE
Add unet extra path to ComfyUi Extra Paths Yaml

### ISSUE THREAD

**Issue by jeremydk** [LykosAI/StabilityMatrix#831]
This should resolve #813  , and #805 in the cleanest possible way, since it appears to be a missing mapped path.

I've added it locally, and confirmed everything looks good.

**Comment by hellloveyy** [comment]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/cfd7f7f1-edfa-43e2-990a-3d7063370f7a" />
<img width="893" alt="image" src="https://github.com/user-attachments/assets/d331f6f9-cd67-4de7-8b5d-df5d9efd0306" />
This happened to me too, put in the comfyui unet file, but could only find the gguf file, not the sft
