### ISSUE TITLE
[Feature Suggestion] Select multiple versions of an item to download in the browser

### ISSUE THREAD

**Issue by aurelienLavanchy** [LykosAI/StabilityMatrix#834]
Currently you have to select a version to download, which closes the version selector and forces you to wait for the download to be finished before being able to select another one. Not very user-friendly.
It would be nicer to be able to select multiple versions to download (sequentially?, depending on API limitations) rather than having to wait to be able to re-open the modal to select another version.

On the same subject being able to scale this modal would be great, it currently stays the same tiny size in the middle of the screen (even on higher resolutions)
My laptop has a 2560x1600px (built-in) monitor and it's harder to read the text and (overall) use the browser than on a lower resolution. Probably a bit less of a problem on an external monitor ?

**Comment by Targren** [comment]
This feature would be especially nice to have when assets use "versions" to break up the releases, rather than development progress (e.g. [Edg Royal Gowns](https://civitai.com/models/61135))
