### ISSUE TITLE
option to show console log on good old windows command prompt

### ISSUE THREAD

**Issue by shivshankar11** [LykosAI/StabilityMatrix#835]
in app  console log is very annoying. it can not show full logs, can not enlarge text font

S:\Ai\Visual\StabilityMatrix\Data\Packages\SD.Next Web UI\modules\scripts.p │
│                                                                             │
│   293 │   try:                                                              │
│ > 294 │   │   res = func(*args, **kwargs)                                   │
│   295 │   │   return res                                                    │
│                                                                             │
│ S:\Ai\Visual\StabilityMatrix\Data\Packages\SD.Next Web UI\extensions\--sd-w │
│                                                                             │
│   346 │   │   │   │   │   if is_img2img:                                    │
│ > 347 │   │   │   │   │   │   lock_w = self.i2i_w                           │
│   348 │   │   │   │   │   │   lock_h = self.i2i_h

**Comment by mohnjiles** [comment]
Thanks for the suggestion, we're working on adding a font size adjustment to the console. For the line width, you can try settings the `COLUMNS` Environment Variable in SM's Settings -> Environment Variables section like so to increase it:
![image](https://github.com/user-attachments/assets/3fc2f55a-f35c-48c2-8fb4-9618ed10cbf2)
