### ISSUE TITLE
Restarting ComfyUI from Manager creates "ghost" ComfyUI instance

### ISSUE THREAD

**Issue by Targren** [LykosAI/StabilityMatrix#838]
Restarting ComfyUI from within the ComfyUI Manager triggers StabilityMatrix to think that the instance is stopped and hasn't auto-restarted, leaving a running instance attached to the SM console, but  the button states are wrong - "Launch" button is up, and the only way to stop the "detached" instance is to kill and restart StabilityMatrix.

Problem occurs whether --auto-launch is checked or not. 

To reproduce:

1.  Start ComfyUI Instance
2. Open "Manager"
3. Click "Restart" and confirm
4. Look at StabilityMatrix console for ComfyUI Instance

**Comment by richardm1** [comment]
I'm seeing this as well.

**Comment by Targren** [comment]
Issue still persists on 2.11.8 with comfy running master@e813abb (latest as of the time of this comment)
