### ISSUE TITLE
Installing older commits of a package?

### ISSUE THREAD

**Issue by MBurneracc** [LykosAI/StabilityMatrix#842]
Am I missing something or is it impossible to install a package older than 10 commits?  Because no matter where I look there's no option to select anything older and the only place the option to choose is even available is limited to the ten most recent.  Forge totally f'd a bunch of core features and extensions they seen to have no intention to fix and I have no clue how to install an older functional version through this otherwise.

**Comment by richardm1** [comment]
I'd like to know about this as well.  For ComfyUI the oldest of the ten is only 2-3 days old (I hadn't realized Comfy is a "rolling distro" of SD).
