### ISSUE TITLE
[Stable Diffusion WebUI Forge] outputs images not showing up on "output browser"

### ISSUE THREAD

**Issue by bryanray** [LykosAI/StabilityMatrix#847]
![image](https://github.com/user-attachments/assets/e1cf774a-9933-4e20-ade2-99a95c1d84bb)

[Stable Diffusion WebUI Forge] outputs images not showing up on "output browser"

**Comment by TdoubleAV** [comment]
this might be a simple typo as there seems to be two folders: "output" & "output**s**"

**Comment by bryanray** [comment]
i also look into the seemingly typo issue but it is not a typo.

instead the folder only shows images that had been hit the "save" button,,,, how to show all as it should be, and also show the separate the saved image in a "saved" folder in the same app..
