### ISSUE TITLE
Error upon Forge launch: "Unobserved Task Exception - IOException"

### ISSUE THREAD

**Issue by coreshock** [LykosAI/StabilityMatrix#853]
Just stumbled upon this issue with the latest Matrix and Forge updates (Stable v2.11.8 and main@3e25301/main@852e885 correspondingly). Everything was fine before.

**Comment by fotografomedellin** [comment]
I have the same issue with update 2.11.8 and Forge main@0d8eb4c.

**Comment by fotografomedellin** [comment]
![Captura de pantalla 2024-08-21 184323](https://github.com/user-attachments/assets/840801ed-0314-46aa-a3e9-a0c9f6846755)

**Comment by coreshock** [comment]
> Could you check your outputs folder in Forge and move any images in there to another folder then try again? Once it starts successfully you can move them back.

Thanks for the suggestion! I didn't have to move anything, just unchecked the "share output" box, and the error went away.

**Comment by kuronagi66** [comment]
After updating to the latest version of Forge Neo, I'm encountering an 'Unobserved Task Exception - IOException' error, which prevents the application from launching.

I found that setting 'Model Sharing' to 'None' allows it to launch, but then all my models disappear. Has anyone else experienced this or found a fix?
