### ISSUE TITLE
Crashes Explorer.exe and previous issues when folders change.

### ISSUE THREAD

**Issue by DarkVamprism** [LykosAI/StabilityMatrix#854]
For a while I have had a small issue where if I delete a folder with Lora's in it while StabilityMatrix is closed then it will cause an error when I run StabilityMatrix that says it cannot find the directory(Only showed if I ran it from the start menu for some reason?)

But today when I launched my PC and ran StabilityMatrix then my explorer.exe constantly crashes and restarts, I am not sure what is causing it but it stops as soon as I close this and restarts as soon as it is open. I'm not getting any error messages but it is a major issue preventing me using half of my PC while StabilityMatrix is opened.

Event Viewer is showing the following Error
```
Faulting application name: Explorer.EXE, version: 10.0.22621.4076, time stamp: 0x075bf583
Faulting module name: ucrtbase.dll, version: 10.0.22621.3640, time stamp: 0x10c46e71
Exception code: 0xc0000409
Fault offset: 0x000000000007f6fe
Faulting process id: 0x0x7B30
Faulting application start time: 0x0x1DAF44E3A5BAB77
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: f9959200-e6b0-4c42-ae7f-cec7e2404366
Faulting package full name: 
Faulting package-relative application ID: 
````

**Comment by Vorrilian** [comment]
I also have this issue, except I just installed StabiltyMatrix for the first time and haven't deleted any files. Identical event viewer error as well. 
`Faulting application name: Explorer.EXE, version: 10.0.22621.4076, time stamp: 0x075bf583
Faulting module name: ucrtbase.dll, version: 10.0.22621.3640, time stamp: 0x10c46e71
Exception code: 0xc0000409
Fault offset: 0x000000000007f6fe
Faulting process id: 0x0x65A8
Faulting application start time: 0x0x1DAF4FB7E6678CE
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: ef3d5c20-f036-45fa-bce2-45ce6c1ae133
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by Vorrilian** [comment]
I also have this issue, except I just installed StabiltyMatrix for the first time and haven't deleted any files. Identical event viewer error as well. 

```Faulting application name: Explorer.EXE, version: 10.0.22621.4076, time stamp: 0x075bf583
Faulting module name: ucrtbase.dll, version: 10.0.22621.3640, time stamp: 0x10c46e71
Exception code: 0xc0000409
Fault offset: 0x000000000007f6fe
Faulting process id: 0x0x65A8
Faulting application start time: 0x0x1DAF4FB7E6678CE
Faulting application path: C:\WINDOWS\Explorer.EXE
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: ef3d5c20-f036-45fa-bce2-45ce6c1ae133
Faulting package full name: 
Faulting package-relative application ID: ```

**Comment by Demcrew** [comment]
I have the same issue here as well, explorer.exe crashing

**Comment by richardm1** [comment]
In PowerShell what's the output of Get-HotFix | sort InstalledOn?

**Comment by KilianBarbier** [comment]
Same problem for me, it had been working fine for several months and one day I launched Stability Matrix and it crashed explorer.exe over and over again.
