### ISSUE TITLE
Stability Matrix Video card problem 

### ISSUE THREAD

**Issue by pilgrimage80** [LykosAI/StabilityMatrix#858]
I'm trying to install Stability Matrix Linux. I have a Tesla V100 on my server. However, when installing, it sees the default Matrox video card of the server. What is the reason for this? However, nvidia drivers and cuda are installed.

**Comment by mohnjiles** [comment]
On Linux we run `lspci | grep VGA` and use the first result when showing the GPU there. As long as you select CUDA for your PyTorch Version during the installation, everything should still work as expected.
