### ISSUE TITLE
Taskbar flashing on and off when StableMatrix running

### ISSUE THREAD

**Issue by Mastertouch** [LykosAI/StabilityMatrix#859]
Hey guys 
Weird one but after I did a recent update to Forge, OneTrainer and Comfy a few days ago, every time I start Matrix the taskbar and the background flashes on and off. with the taskbar disapearing completely. Runing win11 with a 3060 nvidia card

**Comment by gmag11** [comment]
Same here with Windows 11 and RTX3060

https://github.com/user-attachments/assets/88c5d9c6-f0c5-4abc-8d27-02708928c5ac

**Comment by Demcrew** [comment]
Same here, starting to investigate through the logs

**Comment by mohnjiles** [comment]
Sorry about that, haven't been able to reproduce so far, does rolling back to an older version of SM make any difference?

**Comment by Vorrilian** [comment]
> Sorry about that, haven't been able to reproduce so far, does rolling back to an older version of SM make any difference?

I tried rolling back a few different versions, the oldest being 2.10.3. same issue occurs in all versions I tried.

**Comment by mohnjiles** [comment]
> > Sorry about that, haven't been able to reproduce so far, does rolling back to an older version of SM make any difference?
> 
> I tried rolling back a few different versions, the oldest being 2.10.3. The same issue occurs in all versions I tried.
> 
> I'm happy to try any versions you suggest or send any logs/etc.

Thanks for trying, what about launching SM with the `--disable-gpu-rendering` flag? Also were there any system or GPU driver updates installed recently?

**Comment by Vorrilian** [comment]
> > > Sorry about that, haven't been able to reproduce so far, does rolling back to an older version of SM make any difference?
> > 
> > 
> > I tried rolling back a few different versions, the oldest being 2.10.3. The same issue occurs in all versions I tried.
> > I'm happy to try any versions you suggest or send any logs/etc.
> 
> Thanks for trying, what about launching SM with the `--disable-gpu-rendering` flag? Also were there any system or GPU driver updates installed recently?

I tried running with that flag, still no luck unfortunately. I just installed SM for the first time yesterday and had this issue since the first install. I'm currently on Windows Insider beta (22635.4076) and running the most recent Nvidia game ready driver (560.94) on a 3070 Ti

**Comment by Demcrew** [comment]
I've tried as well using  --disable-gpu-rendering, no avail. I've investigated a bit further, from the event log I have the following (sorry, french system :/) : 

```
 AppName Explorer.EXE 
  AppVersion 10.0.22621.4076 
  AppTimeStamp 075bf583 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.4076 
  ModuleTimeStamp 145ea90b 
  ExceptionCode e06d7363 
  FaultingOffset 000000000005facc 
  ProcessId 0x7958 
  ProcessCreationTime 0x1daf5a8fe5ceed8 
  AppPath C:\WINDOWS\Explorer.EXE 
  ModulePath C:\WINDOWS\System32\KERNELBASE.dll 
  IntegratorReportId 097b1c97-19ab-495e-9518-40b72c3fecf9 
  PackageFullName  
  PackageRelativeAppId  
```
or : 

```
AppName Explorer.EXE 
  AppVersion 10.0.22621.4076 
  AppTimeStamp 075bf583 
  ModuleName ucrtbase.dll 
  ModuleVersion 10.0.22621.3640 
  ModuleTimeStamp 10c46e71 
  ExceptionCode c0000409 
  FaultingOffset 000000000007f6fe 
  ProcessId 0x3268 
  ProcessCreationTime 0x1daf5a8fca50ea4 
  AppPath C:\WINDOWS\Explorer.EXE 
  ModulePath C:\WINDOWS\System32\ucrtbase.dll 
  IntegratorReportId be5c69a5-a7f2-41ec-8dd9-a313fa2c94a1 
  PackageFullName  
  PackageRelativeAppId  
```

**Comment by BSoD38** [comment]
I have this as well, it seems that having specifically Stability Matrix open causes explorer.exe to crash loop. It just crashes, tries to start again, and crashes immediately in an endless loop until Stability Matrix is closed. I didn't have this a few days ago, so I'm pretty positive that one of the latest Windows updates broke something.

**Comment by Mastertouch** [comment]
anyone have any luck with this issue?

**Comment by glenndav** [comment]
Confirmed. Same issue here. 
Stability Matrix version 2.11.8, 
RTX 3060 560.94 game driver
Windows 11 Pro v23H2, build 22635.4076, Windows Feature Experience Pack 1000.22700.1036.0

**Comment by mohnjiles** [comment]
The common thread seems to be the Windows Insider build. Not sure what we can do on our end since it only happens on Insider builds, and doesn't seem to be tied to a specific version of SM.

**Comment by richardm1** [comment]
Curious if this month's cumulative caused this.  In PowerShell what's the output of `Get-HotFix | sort InstalledOn`?

**Comment by BSoD38** [comment]
> Curious if this month's cumulative caused this. In PowerShell what's the output of `Get-HotFix | sort InstalledOn`?

Here's what I get with this command:
```
Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
BSOD-ELEVEN   Update           KB5033055     AUTORITE NT\Système  03/12/2023 00:00:00
BSOD-ELEVEN   Update           KB5027397                          03/12/2023 00:00:00
BSOD-ELEVEN   Update           KB5031483     AUTORITE NT\Système  28/05/2024 00:00:00
BSOD-ELEVEN   Update           KB5042099     AUTORITE NT\Système  13/08/2024 00:00:00
BSOD-ELEVEN   Security Update  KB5041874     AUTORITE NT\Système  19/08/2024 00:00:00
BSOD-ELEVEN   Security Update  KB5041873     AUTORITE NT\Système  19/08/2024 00:00:00
```

**Comment by gmag11** [comment]
I've tested it today and it runs fine again. I'm running Stability Matrix 2.11.8, what did not work last week, so most probably MS fixed something with a Windows update.

**Comment by Mac48** [comment]
I am running on the Insider Preview 10.0.22635.4145 (ni_release) but I still have this issue on my side. I don't know how to solve it..
The windows explorer keeps crashing and restarting whenever StabilityMatrix is launched

**Comment by MisterMagoo1689** [comment]
I had the issue, and I was using an Insider Beta preview release. Today I've left the Insider Preview project, I've installed the latest stable version of Win 11, and I can confirm that the issue disappeared!

**Comment by ryankhart** [comment]
I'm having this same issue on Windows 11 Insider Program Beta version 22635.4145

One weird thing that also happens to me that I don't see mentioned here is that when I launch StabilityMatrix.exe, after explorer.exe starts a crash loop, I also get a popup from Windhawk Toolkit that steals the focus away from StabilityMatrix until I exit Windhawk entirely.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/b9596ea1-8b27-4b03-b70e-a55e3bc7e7fd">

I still get the flickering with or without Windhawk running before I launch StabilityMatrix.
