### ISSUE TITLE
ComfyUI updates revert to PyTorch 2.1.2+cu121

### ISSUE THREAD

**Issue by JohnnyJae** [LykosAI/StabilityMatrix#861]
As the title says. When updating through the app, ComfyUI reverts back to Pytorch 2.1.2. Any way to go around this?

**Comment by emrys218** [comment]
I am having the same problem.  When I query the PyTorch version it is correct  but when running Comfyui, it always reverts to the above version  I need the Cuda 12.4 for my Nvidia Card

**Comment by johnnyp92** [comment]
I get the same problem every time. very annoying

**Comment by lichthorizont** [comment]
same problem here. is there any solution to prevent automaticaly updating existing pytorch if updating comfyui via stabilty matrix? thank you

**Comment by Arkhaner1511** [comment]
[https://github.com/LykosAI/StabilityMatrix/commit/ca7df423a50cc66afdeb493e0066da8849b7afed#r146694503](url)

Thats the problem ... they have to fix it.
