### ISSUE TITLE
Issues loading ComfyUI Workflow backend after latest update

### ISSUE THREAD

**Issue by michaelkhboo** [LykosAI/StabilityMatrix#870]
Hi all, I've just updated comfy,swarm,forge, and the stability matrix app itself  earlier today, and ever since i have been stuck on "Failed to load ComfyUI Workflow backend. The server may still be loading." within swarmUI. i can still run the standalone comfyui. not sure what did i mess up  or is it a bug?

**Comment by DonDanDojo** [comment]
Hi! Got a simmilar problem with SwarmUI. 

![problem 15](https://github.com/user-attachments/assets/0590c4ef-1cc4-4b67-94d8-1de4a8deab7b)

[no workflow problem.txt](https://github.com/user-attachments/files/17015935/no.workflow.problem.txt)

![1](https://github.com/user-attachments/assets/33e128f4-32ec-4431-84cf-0808625de9b8)


Suddenly it doesn't show comfy workflow (simple comfyui works fine)

**Comment by Ameno-Sagiri** [comment]
I have the same problem. Every version after somewhere in September has started causing this for me. I do a clean install and it still doesn't work.

**Comment by realenuf** [comment]
I just installed SwarmUI on Ubuntu 24.04.1 CUDA, and nothing works because of constant errors about the lack of a ComfyUI back-end. The interface looks better than raw ComfyUI, so I'd really like to try it.
