### ISSUE TITLE
Unable to install 'Ruined Fooocus' in S.M.

### ISSUE THREAD

**Issue by fbauer-kunbus** [LykosAI/StabilityMatrix#875]
First time installation attempt of 'Ruined Fooocus' fails - here is the log:

Unpacking resources
Unpacking resources
Download Complete
Collecting torch==2.2.2
Downloading torch-2.2.2-cp310-cp310-win_amd64.whl.metadata (26 kB)
Collecting torchsde==0.2.6
Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting einops==0.4.1
Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting transformers==4.44.0
Using cached transformers-4.44.0-py3-none-any.whl.metadata (43 kB)
Collecting safetensors==0.4.3
Using cached safetensors-0.4.3-cp310-none-win_amd64.whl.metadata (3.9 kB)
Collecting accelerate==0.33.0
Using cached accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)
Collecting pyyaml==6.0
Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl.metadata (2.0 kB)
Collecting Pillow==9.2.0
Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl.metadata (9.0 kB)
Collecting scipy==1.10.0
Downloading scipy-1.10.0-cp310-cp310-win_amd64.whl.metadata (58 kB)
Collecting tqdm==4.66.5
Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting psutil==5.9.5
Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl.metadata (21 kB)
Collecting numpy==1.26.4
Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Collecting pytorch_lightning==1.9.4
Using cached pytorch_lightning-1.9.4-py3-none-any.whl.metadata (22 kB)
Collecting omegaconf==2.2.3
Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)
Collecting gradio==3.50.2
Downloading gradio-3.50.2-py3-none-any.whl.metadata (17 kB)
Collecting pygit2==1.12.2
Using cached pygit2-1.12.2-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Collecting aiohttp==3.8.5
Downloading aiohttp-3.8.5-cp310-cp310-win_amd64.whl.metadata (8.0 kB)
Collecting playsound2==1.3.0
Downloading playsound2-1.3.0.tar.gz (7.2 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting diffusers==0.30.0
Downloading diffusers-0.30.0-py3-none-any.whl.metadata (18 kB)
Collecting ftfy==6.1.1
Using cached ftfy-6.1.1-py3-none-any.whl.metadata (6.1 kB)
Collecting clip_interrogator==0.6.0
Using cached clip_interrogator-0.6.0-py3-none-any.whl.metadata (4.9 kB)
Collecting opencv-python==4.8.1.78
Downloading opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting kornia==0.7.2
Using cached kornia-0.7.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting sentencepiece==0.2.0
Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Collecting spandrel==0.3.4
Using cached spandrel-0.3.4-py3-none-any.whl.metadata (14 kB)
Collecting imageio==2.34.1 (from imageio[pyav]==2.34.1)
Using cached imageio-2.34.1-py3-none-any.whl.metadata (4.9 kB)
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement xformers==0.0.26 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.post1, 0.0.27, 0.0.27.post1, 0.0.27.post2, 0.0.28.dev893, 0.0.28.dev895)
ERROR: No matching distribution found for xformers==0.0.26
Could not install RuinedFooocus (StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Collecting torch==2.2.2\r\n Downloading torch-2.2.2-cp310-cp310-win_amd64.whl.metadata (26 kB)\r\nCollecting torchsde==0.2.6\r\n Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)\r\nCollecting einops==0.4.1\r\n Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)\r\nCollecting transformers==4.44.0\r\n Using cached transformers-4.44.0-py3-none-any.whl.metadata (43 kB)\r\nCollecting safetensors==0.4.3\r\n Using cached safetensors-0.4.3-cp310-none-win_amd64.whl.metadata (3.9 kB)\r\nCollecting accelerate==0.33.0\r\n Using cached accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)\r\nCollecting pyyaml==6.0\r\n Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl.metadata (2.0 kB)\r\nCollecting Pillow==9.2.0\r\n Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl.metadata (9.0 kB)\r\nCollecting scipy==1.10.0\r\n Downloading scipy-1.10.0-cp310-cp310-win_amd64.whl.metadata (58 kB)\r\nCollecting tqdm==4.66.5\r\n Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\r\nCollecting psutil==5.9.5\r\n Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl.metadata (21 kB)\r\nCollecting numpy==1.26.4\r\n Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)\r\nCollecting pytorch_lightning==1.9.4\r\n Using cached pytorch_lightning-1.9.4-py3-none-any.whl.metadata (22 kB)\r\nCollecting omegaconf==2.2.3\r\n Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)\r\nCollecting gradio==3.50.2\r\n Downloading gradio-3.50.2-py3-none-any.whl.metadata (17 kB)\r\nCollecting pygit2==1.12.2\r\n Using cached pygit2-1.12.2-cp310-cp310-win_amd64.whl.metadata (3.6 kB)\r\nCollecting aiohttp==3.8.5\r\n Downloading aiohttp-3.8.5-cp310-cp310-win_amd64.whl.metadata (8.0 kB)\r\nCollecting playsound2==1.3.0\r\n Downloading playsound2-1.3.0.tar.gz (7.2 kB)\r\n Preparing metadata (setup.py): started\r\n Preparing metadata (setup.py): finished with status 'done'\r\nCollecting diffusers==0.30.0\r\n Downloading diffusers-0.30.0-py3-none-any.whl.metadata (18 kB)\r\nCollecting ftfy==6.1.1\r\n Using cached ftfy-6.1.1-py3-none-any.whl.metadata (6.1 kB)\r\nCollecting clip_interrogator==0.6.0\r\n Using cached clip_interrogator-0.6.0-py3-none-any.whl.metadata (4.9 kB)\r\nCollecting opencv-python==4.8.1.78\r\n Downloading opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)\r\nCollecting kornia==0.7.2\r\n Using cached kornia-0.7.2-py2.py3-none-any.whl.metadata (12 kB)\r\nCollecting sentencepiece==0.2.0\r\n Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)\r\nCollecting spandrel==0.3.4\r\n Using cached spandrel-0.3.4-py3-none-any.whl.metadata (14 kB)\r\nCollecting imageio==2.34.1 (from imageio[pyav]==2.34.1)\r\n Using cached imageio-2.34.1-py3-none-any.whl.metadata (4.9 kB)\r\nERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10\r\nERROR: Could not find a version that satisfies the requirement xformers==0.0.26 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.post1, 0.0.27, 0.0.27.post1, 0.0.27.post2, 0.0.28.dev893, 0.0.28.dev895)\r\nERROR: No matching distribution found for xformers==0.0.26\r\n'
at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action1 outputDataReceived) at StabilityMatrix.Core.Models.Packages.RuinedFooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress1 progress, Action1 onConsoleOutput) at StabilityMatrix.Core.Models.Packages.RuinedFooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress1 progress, Action1 onConsoleOutput) at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress1 progress)
at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))

**Comment by vfxturjo** [comment]
same here

**Comment by hexoth** [comment]
same issue here

**Comment by dessin44** [comment]
same

**Comment by fbauer-kunbus** [comment]
@dessin44 
This actually works - but how come that neither the developers of RF not those of SM were posting this solution - not to speak of fixing it(!) - days ago already? This doesn't give me much confidence in the relevance of RM in the first place.

**Comment by hexoth** [comment]
> cmd.exe X:\StabilityMatrix\Packages\RuinedFooocus\venv\Scripts>pip install xformers==0.0.26.post1 it seems to work for me.

Crashes for me. Wish they'd fix this. Super annoying.
