### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by maakcode** [LykosAI/StabilityMatrix#881]
Hi,
I would like to contribute to this project by translating it to korean. 
- email: maakcode@gmail.com

**Comment by mohnjiles** [comment]
Thank you! An invite from our POEditor project should have been sent to that email address. If you can't find it, you can also try joining via this link: https://poeditor.com/join/project/w6487qEjqD

Thanks again!

**Comment by maakcode** [comment]
It's done.
I used the terminology by cross-referencing the following sources:
1. [Domestic papers in Korean](https://www.kci.go.kr)
2. [Hugging Face Docs Korean Translations](https://huggingface.co/docs/transformers/v4.44.2/ko/index)
3. https://github.com/36DB/stable-diffusion-webui-localization-ko_KR

**Comment by mohnjiles** [comment]
Great, thank you very much! It should be included in the next update.
