### ISSUE TITLE
Unable to install WebUI Forge

### ISSUE THREAD

**Issue by Vik71it** [LykosAI/StabilityMatrix#891]
### Package

Stable Diffusion WebUI Forge

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

Nvidia RTX4060TI 16GB

### What happened?

The installation process is just stuck in the first steps, remains like this for hours without any progress. 

If I then use the "Clear Finished" commands, in the Download menu, it closes everything, and at the following start of Stability Matrix, it shows an "unknown package" (for which also the "import"  function doesn't end up in a working package)
![Immagine 2024-09-17 110012](https://github.com/user-attachments/assets/5f3113ea-5b27-45f4-81e3-d543d92067b2)

### Console output

Unpacking resources
Unpacking resources

![Immagine 2024-09-17 105226](https://github.com/user-attachments/assets/3d1a611a-db30-4914-95d2-0a0dbeda13ba)

### Version

2.11.8

### What Operating System are you using?

Windows

**Comment by ViratX** [comment]
I'm facing the exact same issue when trying to install InvokeAI currently. Were you able to find a fix?
