### ISSUE TITLE
Fooocus 2.5.5 ModuleNotFoundError: No module named 'groundingdino.util'

### ISSUE THREAD

**Issue by orangpelupa** [LykosAI/StabilityMatrix#893]
### Package

fooocus

### When did the issue occur?

Running the Package

### What GPU / hardware type are you using?

RTX 4070ti super

### What happened?

ever since fooocus 2.5.0, stability matrix has stopped working for fooocus. same issue in 2.5.5. installing fooocus results in ModuleNotFoundError: No module named 'groundingdino.util'ModuleNotFoundError: No module named 'groundingdino.util'

### Console output

[System ARGV] ['B:\\tools\\StabilityMatrix-win-x64\\Data\\Packages\\Fooocus3\\launch.py', '--share', '--listen', '192.168.66.162']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.0
[Cleanup] Attempting to delete content of temp dir C:\Users\8492n\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 16376 MB, total RAM 32694 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : native
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "B:\tools\StabilityMatrix-win-x64\Data\Packages\Fooocus3\launch.py", line 147, in <module>
    from webui import *
  File "B:\tools\StabilityMatrix-win-x64\Data\Packages\Fooocus3\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "B:\tools\StabilityMatrix-win-x64\Data\Packages\Fooocus3\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "B:\tools\StabilityMatrix-win-x64\Data\Packages\Fooocus3\extras\inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "B:\tools\StabilityMatrix-win-x64\Data\Packages\Fooocus3\extras\GroundingDINO\util\inference.py", line 11, in <module>
    from groundingdino.util.inference import Model
ModuleNotFoundError: No module named 'groundingdino.util'

### Version

2.12.0

### What Operating System are you using?

Windows

**Comment by orangpelupa** [comment]
it can be fixed by manually downloading the files in this youtube https://www.youtube.com/watch?v=xe2Ur_QraSY 

not sure how to fix stability matrix.

**Comment by mr-september** [comment]
Please implement this fix locally. Most users don't even understand the video above because it's not in English. Should not encourage users to download random files from strangers.
