### ISSUE TITLE
Can not minimize window on MacOS

### ISSUE THREAD

**Issue by GLOUPY-RnD** [LykosAI/StabilityMatrix#899]
### What happened?

It is possible to enter full screen, close but not minimize the window in the dock/app icon.

MacOS 15.0 Sequoia
Mac Studio M2 Max 96Gb

### Steps to reproduce

1 - Open Stability Matrix
2 - Can not minimize window

### Version

v2.12.0

### What Operating System are you using?

macOS

**Comment by mohnjiles** [comment]
Sorry about that, there is a bug in the UI framework we use that has a pending fix. Once that gets released we'll be able to put out an update to fix this.

**Comment by mohnjiles** [comment]
This should be fixed as of v2.12.2
