### ISSUE TITLE
stability matirx could not find a version satisfies the requirement of jsonmerge

### ISSUE THREAD

**Issue by lurker451** [LykosAI/StabilityMatrix#901]
### Package

Stable Diffusion webui

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

Nvidia RTX 3060

### What happened?

in stability matrix, when I try to install stable diffusion AUTO1111 webui, It appears failed installation. I don't know why is this happening. error It says that it could not fins a version satisfies the requirement of jsonmerge. If anybody recognize this error I ask for help... (I'm currently using window 11 by the way)

### Console output

Unpacking resources
Unpacking resources
Download Complete
Requirement already satisfied: pip in c:\users\user\desktop\stable diffusion\stabilitymatrix-win-x64\data\packages\stable-diffusion-webui\venv\lib\site-packages (24.2)
Requirement already satisfied: wheel in c:\users\user\desktop\stable diffusion\stabilitymatrix-win-x64\data\packages\stable-diffusion-webui\venv\lib\site-packages (0.44.0)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.1.2
  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
Collecting torchvision==0.16.2
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)
Collecting setuptools==69.5.1
  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Collecting GitPython==3.1.32
  Using cached GitPython-3.1.32-py3-none-any.whl.metadata (10.0 kB)
Collecting Pillow==9.5.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl.metadata (9.7 kB)
Collecting accelerate==0.21.0
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Collecting blendmodes==2022
  Using cached blendmodes-2022-py3-none-any.whl.metadata (12 kB)
Collecting clean-fid==0.1.35
  Using cached clean_fid-0.1.35-py3-none-any.whl.metadata (36 kB)
Collecting diskcache==5.6.3
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting einops==0.4.1
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting facexlib==0.3.0
  Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting fastapi==0.94.0
  Using cached fastapi-0.94.0-py3-none-any.whl.metadata (25 kB)
Collecting gradio==3.41.2
  Using cached gradio-3.41.2-py3-none-any.whl.metadata (17 kB)
Collecting httpcore==0.15
  Using cached httpcore-0.15.0-py3-none-any.whl.metadata (15 kB)
Collecting inflection==0.5.1
  Using cached inflection-0.5.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting jsonmerge==1.8.0
  Using cached jsonmerge-0.0.0-py3-none-any.whl
Discarding https://files.pythonhosted.org/packages/37/1b/05dd6fd53a76a73e898f3d2b60d02ee90af9e11de2f8e3802a6262fa1ca9/jsonmerge-1.8.0.tar.gz (from https://pypi.org/simple/jsonmerge/): Requested jsonmerge==1.8.0 from file:///C:/users/user/appdata/local/pip/cache/wheels/5a/28/53/7c501247d1873c913eb46702f23045e4d9f565fe2a5ec13f69/jsonmerge-0.0.0-py3-none-any.whl has inconsistent version: expected '1.8.0', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement jsonmerge==1.8.0 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.9.2)
ERROR: No matching distribution found for jsonmerge==1.8.0
Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121\r\nCollecting torch==2.1.2\r\n  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)\r\nCollecting torchvision==0.16.2\r\n  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)\r\nCollecting setuptools==69.5.1\r\n  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)\r\nCollecting GitPython==3.1.32\r\n  Using cached GitPython-3.1.32-py3-none-any.whl.metadata (10.0 kB)\r\nCollecting Pillow==9.5.0\r\n  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl.metadata (9.7 kB)\r\nCollecting accelerate==0.21.0\r\n  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)\r\nCollecting blendmodes==2022\r\n  Using cached blendmodes-2022-py3-none-any.whl.metadata (12 kB)\r\nCollecting clean-fid==0.1.35\r\n  Using cached clean_fid-0.1.35-py3-none-any.whl.metadata (36 kB)\r\nCollecting diskcache==5.6.3\r\n  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)\r\nCollecting einops==0.4.1\r\n  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)\r\nCollecting facexlib==0.3.0\r\n  Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)\r\nCollecting fastapi==0.94.0\r\n  Using cached fastapi-0.94.0-py3-none-any.whl.metadata (25 kB)\r\nCollecting gradio==3.41.2\r\n  Using cached gradio-3.41.2-py3-none-any.whl.metadata (17 kB)\r\nCollecting httpcore==0.15\r\n  Using cached httpcore-0.15.0-py3-none-any.whl.metadata (15 kB)\r\nCollecting inflection==0.5.1\r\n  Using cached inflection-0.5.1-py2.py3-none-any.whl.metadata (1.7 kB)\r\nCollecting jsonmerge==1.8.0\r\n  Using cached jsonmerge-0.0.0-py3-none-any.whl\r\nDiscarding https://files.pythonhosted.org/packages/37/1b/05dd6fd53a76a73e898f3d2b60d02ee90af9e11de2f8e3802a6262fa1ca9/jsonmerge-1.8.0.tar.gz (from https://pypi.org/simple/jsonmerge/): Requested jsonmerge==1.8.0 from file:///C:/users/user/appdata/local/pip/cache/wheels/5a/28/53/7c501247d1873c913eb46702f23045e4d9f565fe2a5ec13f69/jsonmerge-0.0.0-py3-none-any.whl has inconsistent version: expected '1.8.0', but metadata has '0.0.0'\r\nERROR: Could not find a version that satisfies the requirement jsonmerge==1.8.0 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.9.2)\r\nERROR: No matching distribution found for jsonmerge==1.8.0\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

### Version

2.12.0

### What Operating System are you using?

Windows

**Comment by mohnjiles** [comment]
Hi, sorry about that, could you try deleting the `C:\Users\<username>\AppData\Local\pip\cache` folder and then try the install again?
