### ISSUE TITLE
Fooocus cannot do live previews due to missing file

### ISSUE THREAD

**Issue by carsonyl** [LykosAI/StabilityMatrix#92]
With StabilityMatrix 2.3.3 in portable mode, and after installing Fooocus, live previews in Fooocus don't work. The console says:

`Warning: TAESD previews enabled, but could not find <my local path>\Data\Models\ApproxVAE\taesdxl_decoder.pth`

Workaround: manually download https://github.com/lllyasviel/Fooocus/blob/main/models/vae_approx/taesdxl_decoder.pth into Data/Models/ApproxVAE/.

**Comment by ionite34** [comment]
It seems they no longer include the taesdxl decoder in the repo and instead download another approx vae at first launch nowhttps://github.com/lllyasviel/Fooocus/blob/6ae7de377dc65708f5dcf613cbf8502212515e8e/launch.py#L86, so this should be fixed
