### ISSUE TITLE
Cant refine face

### ISSUE THREAD

**Issue by wireinet** [LykosAI/StabilityMatrix#920]
### Package

Inference

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

Nvidia RTX 3060

### What happened?

I want to redraw face, use Inference-> face detailer -> (only one can download face_yolov8m) (how to download another? Gray download button) -> get message, that i need to restart comfyUI -> after agree i get error in right bottom corner of the screen
![2024-09-29_19-04-18](https://github.com/user-attachments/assets/4d9a587c-6786-4060-995b-58e0b6fec450)
![2024-09-29_16-13-28](https://github.com/user-attachments/assets/9c1d13ad-c159-4253-afec-a504f6b57759)

### Version

v 2.12.0

### What Operating System are you using?

Windows

**Comment by KloneBaker** [comment]
I have a similar issue: https://github.com/LykosAI/StabilityMatrix/issues/918
