### ISSUE TITLE
InvokeAI package install failed

### ISSUE THREAD

**Issue by leeumane** [LykosAI/StabilityMatrix#939]
### Package

InvokAI

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

RTX 3060 12GB

### What happened?

I had Stability Matrix installed and updated to the latest version. 
I saw that an update came up for InvokeAI (5.1.0) and that they started supporting GGUF FLUX so I decided to install and test it. 
After updating the InvokeAI package I couldn't launch it - giving an error that it couldn't find the GGUF folders. 
I uninstalled the package and tried installing it again - again, I couldn't launch it. 
I removed Stability Matrix from my computer and reinstalled it altogether. 
InvokeAI couldn't be installed at all giving an error that the package installation failed. 
I installed ComfyUI and it launches fine. 
Still can't install InvokeAI though.

### Version

2.12.1

### What Operating System are you using?

Windows

**Comment by fbauer-kunbus** [comment]
Same here ... installed version 5.0.2 crashes with =ModuleNotFoundError: No module named 'gguf'= and update to 5.1.0 fails after some time of doing a lot of stuff with errors I can not even detect in the huge log output that is being created. Invoke is dead on me now, while all other packages in S.M. run without problems.

**Comment by leeumane** [comment]
> Same here ... installed version 5.0.2 crashes with =ModuleNotFoundError: No module named 'gguf'= and update to 5.1.0 fails after some time of doing a lot of stuff with errors I can not even detect in the huge log output that is being created. Invoke is dead on me now, while all other packages in S.M. run without problems.

So far I've found that InvokeAI 5.1.0 installs fine but it doesn't run because of the gguf error.
All versions from InvokeAI 5.1.0rc5 to  5.1.0.rc2 are not installing at all probably because of the GGUF support.
The most current InvokeAI version that installs properly and runs with Stability Matrix is 5.1.0rc1
If you need InvokeAI asap, just remove the installed package, check the "Package" folder in Stability Matrix if the package left anything there. If it did - remove it probably just a folder named "InvokeAI".
Then go to +AddPackage in SM, and when choosing InvokeAI, use the Branches->Releases selector and select Release v5.1.0rc1
Works fine for me but it would be great if I could get the 5.1.0 version :)

**Comment by fbauer-kunbus** [comment]
"Then go to +AddPackage in SM, and when choosing InvokeAI, use the Branches->Releases selector and select Release v5.1.0rc1 Works fine for me but it would be great if I could get the 5.1.0 version :)" 

Isn't Stability Matrix supposed to allow parallel isolated installations of same packages?

**Comment by leeumane** [comment]
> Isn't Stability Matrix supposed to allow parallel isolated installations of same packages?

For me - once I install a package it's no longer available for installation. Only to launch our update.

**Comment by mohnjiles** [comment]
The "Add Package" button remains available at the bottom of the Packages page for you to install any number of packages, duplicate or not.

As of v2.12.0 or later, you can also Change Version directly from the package card's 3-dots menu, to change to rc1 while we work on a fix without reinstalling completely.

**Comment by fbauer-kunbus** [comment]
Is there a time horizon when we can expect this to be fixed? I'm just starting with InvokeAI and can easily wait a couple more days - but wouldn't want to wait more than a week ...

**Comment by leeumane** [comment]
> Is there a time horizon when we can expect this to be fixed? I'm just starting with InvokeAI and can easily wait a couple more days - but wouldn't want to wait more than a week ... So I am still undecided whether starting with RC1 (which seems to be the only one that is running at the moment) is the best option here.

They're quite fast with updates, but let's not give them any pressure. :) 
Nobody is obliged to do anything really especially within a given timeframe.

**Comment by mohnjiles** [comment]
Definitely won't be a week, we have the fix implemented and are just doing some final testing on various platforms. Hope to get it out later today if all looks good.

As for the "why" - Invoke 5.1.x updated to use torch 2.4.1 / cuda12.4 and our install script was still pointing it at the old cuda12.1 version, and there is no pre-built xformers wheel compatible with both torch 2.4.1 + cuda12.1, causing it to try to build xformers on your local PC. Most folks probably don't have the proper build tools to do that (and we don't install them for you cuz it's typically not necessary), hence these failures.

Fix is to just update our install to use the new cuda12.4 index. If you already build SM from source feel free to DIY in the meantime 😄

**Comment by fbauer-kunbus** [comment]
And people have complained in the past when PHP caused incompatibilities every FIVE YEARS or so :-)
I know why I don't like this JENGA tower infrastructure that the whole AI stuff is currently based on. 
Thanks for your effort...!
