### ISSUE TITLE
where to put CUDA_LAUNCH_BLOCKING=1 ?

### ISSUE THREAD

**Issue by smallmousepad** [LykosAI/StabilityMatrix#940]
### Package

Fooocus

### When did the issue occur?

Running the Package

### What GPU / hardware type are you using?

gtx 970

### What happened?

I can't find the answer anywhere on the internet.  
***Where does CUDA_LAUNCH_BLOCKING=1 go?  
Does it go in "Extra launch arguments" in settings?

### Version

2.11.8

### What Operating System are you using?

Windows

**Comment by mohnjiles** [comment]
These can go in the Settings -> Environment Variables -> Edit like so:
![image](https://github.com/user-attachments/assets/61b48753-091d-4157-b60a-1f0eab5e761e)

**Comment by smallmousepad** [comment]
ok, thank you so much 🙏
