### ISSUE TITLE
Reinstallation not possible after the crash during an update - SkiaSharp, KERNELBASE.dll, Windows 10

### ISSUE THREAD

**Issue by itsuxX** [LykosAI/StabilityMatrix#946]
### What happened?

Hi, during the update to version v2.12.2, the computer froze, requiring a restart. Since then, I have not been able to start 'Stability Matrix Portable.' A crash log appeared when starting the program, but I didn’t back it up because I thought reinstalling would fix the issue. Unfortunately, without success—I cannot perform a reinstallation. There is no crash log, no response. I can only see the following errors in the Windows event log. Can you help me?

First Error in Windows event log:

Application: StabilityMatrix.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.BadImageFormatException: An attempt was made to load a file with an incorrect format. (0x8007000B)
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

Second Error in Windows event log:

Faulting application name: StabilityMatrix.exe, Version: 2.12.2.0, Timestamp: 0x66e8bb0a
Faulting module name: KERNELBASE.dll, Version: 10.0.19041.4957, Timestamp: 0xc5225d0f
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process ID: 0x2d20
Start time of the faulting application: 0x01db1bb27c031bda
Path of the faulting application: E:\StabilityMatrix.exe
Path of the faulting module: C:\Windows\System32\KERNELBASE.dll
Report ID: f1393792-412f-4798-a882-43efdbe3ebc7
Full name of the faulting package:
Application ID relative to the faulting package:

### Version

v2.12.2

### What Operating System are you using?

Windows

**Comment by Abbydesu** [comment]
My antivirus scanned it and stopped launch of this version
![{EBE9D478-9E2C-4229-B461-4FA0F4A3A423}](https://github.com/user-attachments/assets/e64afce0-b7a7-4560-b000-c8fe4abc6316)

**Comment by cleberbr10** [comment]
quero remove do meu Windows não sei como remove deu erro quero tira achei luga remove porei eu ja coloquei sim yes etc nada faz acende lar destala preciso de ajuda quero remove ver ser consigo estava de novo
