### ISSUE TITLE
Updating Auto Webui is stuck at updating venv until the folder is deleted

### ISSUE THREAD

**Issue by PhageScope** [LykosAI/StabilityMatrix#95]
Updating Webui to 1.5.2 from 1.5.1 led it to getting stuck at the stage of installing venv, despite restarting Matrix several times in a multi-hour long period. After deleting the venv folder, it took about 15 minutes for it to finish.

**Comment by drdancm** [comment]
I have the same problem. The update moving icon simply goes around and around, never stops. My machine with STMatrix is currently off.  I will see if deleting venv folder fixes the problem.

**Comment by LeeLorenzSr** [comment]
Adding my installation to the pile having this issue, as well. Keep in mind, while the "delete VENV folder" solution kind of works, your installed modules will not match if you have installed extensions.

**Comment by drdancm** [comment]
I had this happen to my again, on my second computer, after having fixed the problem by deleting the VENV folder.
However, I then realized that at the very top line there was a choice to browse to the existing folder, which I did not do the first time. So, I'm not sure if that would have eliminated the waste of time or not.

In any case the system which is to be updated is apparently not paying attention to the current settings and it needs to be fixed. There should be no need to tell it where the folder is.

**Comment by LeeLorenzSr** [comment]
Eh.... now it's hanging on ComfyUI and SD.Next updates. Sigh....

**Comment by mohnjiles** [comment]
Hi all, this should be fixed as of v2.4.1 & later - is anyone seeing this issue after updating to the latest version?

Thanks!

**Comment by drdancm** [comment]
I'm afraid I don't remember whether the I had the 2.4.1 or an earlier version but it happened once more. I was able to fix it by having a backup of the json file.  As I have said earlier, I highly recommend making a backup of this file, prior to running any update.
I think by the time I got to the 2.4.5, I no longer had this problem. 
Thanks !

**Comment by LeeLorenzSr** [comment]
Latest update for Stability Matrix looks good so far, updating most of the packages without issues.

**Comment by PhageScope** [comment]
Not having any more issues either. I assume this is enough to consider the issue closed.
