### ISSUE TITLE
Unobserved Task Exception - FileTransferExistsException

### ISSUE THREAD

**Issue by DrSniffy** [LykosAI/StabilityMatrix#955]
### What happened?

Trying to load any package, this error pops up. I've deleted everything from all the package output folders and checked there's no output sharing switched on. I'm not sure what else to try, except it's all packages affected, so I don't think it's an update to those that caused the issue?
![image](https://github.com/user-attachments/assets/f99c4459-eb39-4a3c-b2d1-c59e2d49b536)

### Version

2.12.2

### What Operating System are you using?

Windows

**Comment by kimnzl** [comment]
I also had this issue, all systems except ComfyUI would fail to start. 
Disabling updates and then downgrading to v2.12.1 works.

**Comment by DrSniffy** [comment]
I was going to do this, then I found by re organising my models, it seemed to fix it.

**Comment by kimnzl** [comment]
In what way did you re-organise the model files?
