### ISSUE TITLE
Codeformer link folder is not being created on Stable Diffusion WebUI

### ISSUE THREAD

**Issue by agarzon** [LykosAI/StabilityMatrix#97]
![image](https://github.com/LykosAI/StabilityMatrix/assets/339828/46a25b28-c359-418d-bac3-2fa7c03c844d)

**Comment by agarzon** [comment]
Just checked and the bug has not been fixed yet.

Same applies to LDSR and GFPGAN

**Comment by Seantourage** [comment]
Seems the LDSR folder is still not being linked in the latest version

**Comment by agarzon** [comment]
GFPGAN is still broken
