### ISSUE TITLE
SwarmUI Installed error

### ISSUE THREAD

**Issue by HEITAOKAKA** [LykosAI/StabilityMatrix#971]
### Package

An error will be reported when installing SwarmUI, and SwarmUI will not start normally

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

NVIDIA 4090

### What happened?

![image](https://github.com/user-attachments/assets/4be7bcf2-5eff-4760-8445-fb0bcbe49309)
![image](https://github.com/user-attachments/assets/0999a893-a877-4bb4-a502-4969f78a275f)

### Console output

Unpacking resources
Unpacking resources
Download Complete
error: 指定的源已添加到可用程序包源的列表中。请提供唯一的源。

Usage: dotnet nuget add source [arguments] [options]

Arguments:
  PackageSourcePath  包源的路径。

Options:
  -n|--name                       源的名称。
  -u|--username                   连接到已验证源时要使用的用户名。
  -p|--password                   连接到已验证源时要使用的密码。
  --store-password-in-clear-text  通过禁用密码加密来启用存储可移植包源凭据。
  --valid-authentication-types    此源的有效身份验证类型的列表(用逗号分隔)。如果服务器公布 NTLM 或 Negotiate，并且你的凭据必须使用基本机制发送(例如将 PAT 与本地 Azure DevOps Server 一起使用时)，请将此项设置为 basic。其他有效值包括 negotiate、kerberos、ntlm 和 digest，但这些值很可能没有用。
  --protocol-version              The NuGet server protocol version to be used. Currently supported versions are 2 and 3. See https://learn.microsoft.com/nuget/api/overview for information about the version 3 protocol. Defaults to 2 if not specified.
  --configfile                    NuGet 配置文件。如果指定，将仅使用此文件中的设置。如果未指定，则将使用当前目录中的配置文件的层次结构。有关详细信息，请参阅 https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior。
  -h|--help                       Show help information

适用于 .NET MSBuild 版本 17.8.3+195e7f5a3
  正在确定要还原的项目…
  已还原 I:\AI\StabilityMatrix\Data\Packages\SwarmUI\src\SwarmUI.csproj (用时 2.08 sec)。
  SwarmUI -> I:\AI\StabilityMatrix\Data\Packages\SwarmUI\src\bin\live_release\SwarmUI.dll

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:04.91
Installed StableSwarmUI at [I:\AI\StabilityMatrix\Data\Packages\SwarmUI]

### Version

v2.12.2

### What Operating System are you using?

Windows

**Comment by mohnjiles** [comment]
Assuming that was the only error, that is expected if the nuget source already exists. 

By the looks of the last message: "Installed SwarmUI at [I:\AI\StabilityMatrix\Data\Packages\SwarmUI]", it finished successfully, so just ignore it and try launching Swarm?
