### ISSUE TITLE
[Feature Request] Model Browser enhancements

### ISSUE THREAD

**Issue by gayspacegems** [LykosAI/StabilityMatrix#98]
I love the program and the model browser in particular, but there are a few things I think could improve the experience.

1. Allow downloading to a specific folder within the models folders.  I like to keep my models organized into category subfolders, so it would be nice to be able to download straight to each folder instead of needing to move them manually.  I'm able to view and import manually to the subfolders within the "Checkpoints" page, which is great, so downloading to them is the last missing piece.  It also seems like there isn't a way to move models in the "Checkpoints" page, which would also be a nice addition.  I also think the "Checkpoints" page could be named something like "Installed Models" to be more clear and consistent.
2. This might only matter to a model hoarder like me, but I would love to be able to queue several model downloads.  When I try to download more than 2 models at a time, it will cause at least one to fail.  I'm fine with the limitation of only being able to download 1 or 2 models at a time, but it would be nice to at least be able to queue up the downloads.  Otherwise, I'm forced to wait until at least one of the downloads has finished before initiating another one.
3. Add the "Installed" tag to models that were manually imported as connected.  That would help prevent accidentally redownloading a model that was imported.

**Comment by mohnjiles** [comment]
Thanks for the suggestions! Regarding the 3rd one, as a temporary solution, you should be able to go to the Settings page and click "Reset Checkpoints Cache" to fix up any missing "installed" tags on models.

**Comment by jurandfantom** [comment]
It is possible to move imported checkpoint (lora in my case) to specific folder or we just need play with folders in windows ? Let say I want move SDXL Offset example LoRA to "Contrast folder. I can head to windows and do that there, but want to be sure after reading above messages :) Thank you for your work - just discovered your project and its best I ever seen so far.


![image](https://github.com/LykosAI/StabilityMatrix/assets/30580568/e7b91954-a857-4622-89bd-3566b7fdafda)

**Comment by adan89lion** [comment]
@jurandfantom, you can now move model files into subfolders, but there are some issues:

- Folders expand too quickly, making drag-and-drop difficult. A 1–3 second delay could help.
- When dragging models to the screen's top/bottom edge, the library doesn't scroll. With many folders, drag-and-drop management becomes impractical.

Stability Matrix could improve by adding checkboxes for models. This would allow users to select multiple models and right-click to move/copy/delete or bulk update metadata. As a model hoarder myself, I would appreciate the implementation.

**Comment by Targren** [comment]
Since the API removed pages, I've noticed that opening the model browser automatically searches on an empty query on whatever my last selected options were. If the API is slow and my last search was SD 1.5 LoRAs, it can hang for some time before it finishes. 

Maybe it shouldn't search automatically when the Browser is opened, just when the "style" button is clicked/enter key is pressed, like when already in the UI?
