### ISSUE TITLE
CivitAI Search is broken . 

### ISSUE THREAD

**Issue by nikolatesla20** [LykosAI/StabilityMatrix#985]
### What happened?

If you search with a term it will work but then you clear the term out and search again it doesn't get any new data. Maybe it's not clearing the search terms?

### Version

2.12.2

### What Operating System are you using?

Windows

**Comment by mohnjiles** [comment]
This may have been improved/fixed in v2.12.3, could you update and report back please?

**Comment by nikolatesla20** [comment]
This seems to be working better, thank you
